### ISSUE TITLE
Pipeline ignores cores setting

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#135]
Despite my cluster having each machine with 24 cores, the latest git master from bcbio-nextgen forces aligners and all other bits to run on 2 cores. 

I've set cores for bwa and samtools in the YAML configuration file, here posted for reference:

``` yaml

resources:
  log:
    dir: log
  ucsc_bigwig:
    memory: 36G
  bwa:
    cmd: bwa
    cores: 24
  samtools:
    memory: 36G
    cores: 24
  novoalign:
    cores: 8
    memory: 36G
  gemini:
    cores: 24
  gatk:
    jvm_opts: ["-Xms750m", "-Xmx32G"]
    dir: /mnt/data/programs/gatk/
  picard:
    dir: /mnt/data/programs/picard/
  snpEff:
    jvm_opts: ["-Xms750m", "-Xmx32G"]
    dir: /mnt/data/software/snpeff/
  bcbio_variation:
    dir: /mnt/data/programs/bcbio.variation
  mutect:
    jvm_opts: ["-Xms750m", "-Xmx32G"]
    dir: /mnt/data/programs/muTect/
  varscan:
    dir: /mnt/data/programs/varscan/
    jvm_opts: ["-Xms750m", "-Xmx32G"]
```

When starting the aligner, I get this log bit (formatted for clarity):

```
013-10-08 10:31:29.594 [IPClusterStart] Config changed:
2013-10-08 10:31:29.595 [IPClusterStart] {'SGELauncher': {'queue': 'main.q'}, '
BcbioSGEEngineSetLauncher': {'mem': '46', 'cores': 2, 'pename': u'orte', 'resources': ''}, 
'IPClusterEngines': {'early_shutdown': 240}, 'Application': {'log_level': 10},
'ProfileDir': {'location': u'/mnt/data/projects/OV159/work/log/ipython'},
'BaseParallelApplication': {'log_to_file': True,
'cluster_id': u'f5c4299b-f5b0-4a57-8620-0cc8598ff5a8'}, 
'IPClusterStart': {'delay': 10, 'controller_launcher_class': u'cluster_helper.cluster.BcbioSGEControllerLauncher', 'daemonize': True, 
'engine_launcher_class': u'cluster_helper.cluster.BcbioSGEEngineSetLauncher',
 'n': 6}}
```

Notice the "cores" section. It's 2 despite the settings above.
