### ISSUE TITLE
Error during gemini database creation

### ISSUE THREAD

**Issue by pfujita** [bcbio/bcbio-nextgen#1452]
Hello,

We just updated to the latest dev version yesterday and I've been trying to test gvcf generation with various callers. I'm running into an error when our process gets to gemini database creation. I don't know if this is at all related to this other issue with gemini support #1284 or maybe this check-in (69bb98ac8abb3ab68ab320410ef584df696124d3) - grasping at straws. Here is the sample.yaml file we're using (and below it is the error output we're seeing):

<pre>
fc_date: 2016-05-07 00:00:15.708284
fc_name: 160208_SN404_0473_AHHFLHBCXX
upload:
  dir: /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106
details:
  - files: [/mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/Sample_R14-18106_R1.fastq, /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/Sam
    description: R14-18106
    analysis: 'variant2'
    genome_build: GRCh37
    lane: R14-18106
    algorithm:
      aligner: bwa
      trim_reads: false
      mark_duplicates: true
      recalibrate: true
      realign: true
      variantcaller: [gatk, gatk-haplotype, freebayes, samtools, vardict]
      ensemble:
       numpass: 1
       use_filtered: false
      tools_on: [qualimap_full, gvcf]
      coverage: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      clinical_reporting: true
</pre>

[2016-06-30T21:31Z] Timing: structural variation validation
[2016-06-30T21:31Z] multiprocessing: validate_sv
[2016-06-30T21:31Z] Timing: heterogeneity
[2016-06-30T21:31Z] Timing: population database
[2016-06-30T21:31Z] multiprocessing: prep_gemini_db
[2016-06-30T21:31Z] Create gemini database for /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/R14-18106-ensemble-decompose-effects.vcf.gz : R14-18106
[2016-06-30T21:31Z] CADD scores are being loaded (to skip use:--skip-cadd).
[2016-06-30T21:31Z] Traceback (most recent call last):
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/gemini", line 6, in <module>
[2016-06-30T21:31Z]     gemini.gemini_main.main()
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
[2016-06-30T21:31Z]     args.func(parser, args)
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
[2016-06-30T21:31Z]     gemini_load.load(parser, args)
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
[2016-06-30T21:31Z]     load_singlecore(args)
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
[2016-06-30T21:31Z]     gemini_loader.populate_from_vcf()
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
[2016-06-30T21:31Z](variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
[2016-06-30T21:31Z]   File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 358, in _prepare_variation
[2016-06-30T21:31Z]     hom_ref = var.num_hom_ref
[2016-06-30T21:31Z]   File "cyvcf2/cyvcf2.pyx", line 642, in cyvcf2.cyvcf2.Variant.num_hom_ref.__get__ (cyvcf2/cyvcf2.c:16261)
[2016-06-30T21:31Z]   File "cyvcf2/cyvcf2.pyx", line 697, in cyvcf2.cyvcf2.Variant.gt_types.**get** (cyvcf2/cyvcf2.c:17047)
[2016-06-30T21:31Z] ValueError: range() step argument must not be zero
[2016-06-30T21:31Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /mnt/speed/qc/sequencing/bcbio/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/R14-18106-ensemble-decompose-effects.vcf.gz -t snpEff --cores 1 --tempdir /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/tx/tmp3IC13v /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/tx/tmp3IC13v/R14-18106-ensemble.db
CADD scores are being loaded (to skip use:--skip-cadd).
Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 358, in _prepare_variation
    hom_ref = var.num_hom_ref
  File "cyvcf2/cyvcf2.pyx", line 642, in cyvcf2.cyvcf2.Variant.num_hom_ref.__get__ (cyvcf2/cyvcf2.c:16261)
  File "cyvcf2/cyvcf2.pyx", line 697, in cyvcf2.cyvcf2.Variant.gt_types.**get** (cyvcf2/cyvcf2.c:17047)
ValueError: range() step argument must not be zero
' returned non-zero exit status 1
Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 185, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 281, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in **call**
    return [func(_args, *_kwargs) for func, args, kwargs in self.items]
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, _args, *_kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 232, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 36, in prep_gemini_db
    gemini_db = create_gemini_db(gemini_vcf, data, gemini_db, ped_file)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 79, in create_gemini_db
    do.run(cmd, "Create gemini database for %s" % gemini_vcf, data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/speed/qc/sequencing/bcbio/anaconda/bin/gemini  load  --passonly --skip-gerp-bp  -v /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/R14-18106-ensemble-decompose-effects.vcf.gz -t snpEff --cores 1 --tempdir /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/tx/tmp3IC13v /mnt/speed/qc/sequencing/ihg-pipeline/EV-13-5-8/Sample_R14-18106/gemini/tx/tmp3IC13v/R14-18106-ensemble.db
CADD scores are being loaded (to skip use:--skip-cadd).
Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1185, in main
    args.func(parser, args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 203, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 358, in _prepare_variation
    hom_ref = var.num_hom_ref
  File "cyvcf2/cyvcf2.pyx", line 642, in cyvcf2.cyvcf2.Variant.num_hom_ref.__get__ (cyvcf2/cyvcf2.c:16261)
  File "cyvcf2/cyvcf2.pyx", line 697, in cyvcf2.cyvcf2.Variant.gt_types.**get** (cyvcf2/cyvcf2.c:17047)
ValueError: range() step argument must not be zero
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Pauline;
I don't believe GEMINI is compatible with gVCF output, as the gVCF output from callers is pretty heterogeneous right now. If you're using the experimental `tools_on: [gvcf]` functionality you should skip GEMINI with `tools_off: [gemini]`. Hope that gets things working cleanly for you.

**Comment by pfujita** [comment]
Hi again,

We're trying to get joint sample calling with gvcf output. We did find this other thread about gvcfs and FreeBayes #1134, but we're not sure if it's the same issue. We have 

tools_on: [gvcf] 

in our sample.yaml but we're getting this GATK error:

```
##### ERROR MESSAGE: Invalid command line: 
Argument emitRefConfidence has a bad value: Can only be used in single sample mode currently. Use the sample_name argument to run on a single sample out of a multi-sample BAM file.
```


This is a snippet of the sample.yaml file we're using:

```
fc_date: 20160726
fc_name: HHFLHBCXX
upload:
  dir: /mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/
details:
  - files: [/mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_Water-EX-17/Sample_Water_R1.fastq, /mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_Water-EX-17/Sample_Water_R2.fastq]
    description: Sample_Water_EX-17
    analysis: 'variant2'
    genome_build: GRCh37
    lane: Sample_Water_EX-17
    algorithm:
      aligner: bwa
      trim_reads: false
      recalibrate: gatk
      realign: gatk
      variantcaller: [gatk-haplotype,freebayes,samtools,gatk]
      ensemble:
       numpass: 1
       use_filtered: true
      tools_off: [gemini]
      tools_on: [qualimap_full,gvcf]
      coverage: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      clinical_reporting: true
    metadata: 
      batch: Batch1
  - files: [/mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_NA19678/Sample_NA19678_R1.fastq, /mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_NA19678/Sample_NA19678_R2.fastq]
    description: Sample_NA19678
    analysis: 'variant2'
    genome_build: GRCh37
    lane: Sample_NA19678
    algorithm:
      aligner: bwa
      trim_reads: false
      recalibrate: gatk
      realign: gatk
      variantcaller: [gatk-haplotype,freebayes,samtools,gatk]
      ensemble:
       numpass: 1
       use_filtered: true
      tools_off: [gemini]
      tools_on: [qualimap_full,gvcf]
      coverage: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      clinical_reporting: true
    metadata:
      batch: Batch1
  - files: [/mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_HG03727/Sample_HG03727_R1.fastq, /mnt/speed/qc/sequencing/ihg-pipeline/joint-calling/Sample_HG03727/Sample_HG03727_R2.fastq]
    description: Sample_HG03727
    analysis: 'variant2'
    genome_build: GRCh37
    lane: Sample_HG03727
    algorithm:
      aligner: bwa
      trim_reads: false
      recalibrate: gatk
      realign: gatk
      variantcaller: [gatk-haplotype,freebayes,samtools,gatk]
      ensemble:
       numpass: 1
       use_filtered: true
      tools_off: [gemini]
      tools_on: [qualimap_full,gvcf]
      coverage: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /mnt/speed/qc/sequencing/biodata/capture_regions/xgen-exome-research-panel-targets-cols1-2-noChr.bed
      clinical_reporting: true

```

**Comment by chapmanb** [comment]
Pauline;
Apologies about the issue. To use gVCF joint calling you want to specify `jointcaller` rather than forcing on gVCF usage with `tools_on`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#population-calling

What's happening in your case is that you specified gVCF but standard pooled calling (all samples together), which GATK can't handle. Practically, `gatk` does not work with joint calling so you should remove that from your configuration as well.

How many samples are you analyzing? You might be better off using standard pooled calling where everything gets called together for FreeBayes and samtools. Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

We are using 56 control samples and when we use pooled calling, it takes about 15 days just to run gatk-halplotyper. So we want to go with gvcf approach where it can handle N+1 issue and also take less time. 

If we use joint calling approach for  gatk-haplotype-joint, freebayes-joint and samtools-joint will it use gvcf approach for all these 3 callers?

**Comment by DiyaVaka** [comment]
Will the below setup run in gvcf mode?

- description: Sample1
  algorithm:
    variantcaller: gatk-haplotypefreebayes,samtools
    jointcaller: gatk-haplotype-joint,freebayes-joint,samtools-joint
  metadata:
    batch: Batch1
- description: Sample2
  algorithm:
    variantcaller: gatk-haplotype,freebayes,samtools
    jointcaller: gatk-haplotype-joint,freebayes-joint,samtools-joint
  metadata:
    batch: Batch1

**Comment by chapmanb** [comment]
Thanks for the additional details. The algorithm setup you described will run joint calling using the three methods. Practically, GATK is gVCF based while FreeBayes and samtools using a custom recalling method implemented in bcbio. We're hoping to migrate to a gVCF-based approach with FreeBayes using GLnexus but that is not currently in place. The GATK based joint calling approach is pretty stable while the other current methods do work but have more issues with disk IO.

If you want to run multiple callers and only have 50 samples I'd suggest running only gatk-haplotype joint with the others pooled:
```
- description: Sample1
  algorithm:
    variantcaller: [gatk-haplotype, freebayes, samtools]
    jointcaller: [gatk-haplotype-joint]
  metadata:
    batch: Batch1
```
Hope this helps.
