### ISSUE TITLE
Is it possible to start bwa + freebayes workflow from mixed input, FASTQ + BAM files?

### ISSUE THREAD

**Issue by NeillGibson** [bcbio/bcbio-nextgen#1641]
Hi, 

I know it is possible to start a variant calling analysis where all samples have FASTQ files or BAM files but I am looking for a solution where there are  pre-aligned BAM files for some samples and a smaller set of new samples with FASTQ files. 

Is it possible to start bwa + freebayes workflow from mixed input, FASTQ + BAM files?

Such that the the samples with the BAM files are used as pre-aligned samples were no further alignment has to be done, and only the samples with the FASTQ files are aligned by BWA?

When all samples have BAM files the joint variant calling can then be started. 

Is this possible? If so how should the sample CSV file and the YAML file look in this case? 
Or can you recommend another approach to this kind of case. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
This will work fine as long as the BAM files are compatible and aligned against the same reference genome. There is no special need for configuration, you'll just need to specify which ones you want alignment and which ones you don't:
```
details:
  - description: sample1
    metadata:
        batch: b1
    files: [input.bam]
    algorithm:
         aligner: false
         variantcaller: gatk-haplotype
         jointcaller: gatk-haplotype-joint
  - description: sample2
    metadata:
        batch: b1
    files: [input1.fq, input2.fq]
    algorithm:
         aligner: bwa
         variantcaller: gatk-haplotype
         jointcaller: gatk-haplotype-joint
```
Hope this helps.
