### ISSUE TITLE
Feature Request: TruSeq custom amplicon workflow

### ISSUE THREAD

**Issue by rjsicko** [bcbio/bcbio-nextgen#1837]
I want to use bcbio to process TruSeq Custom Amplicon (TSCA) data. However, I notice the performance of bcbio's variant2 workflow is not great (comparison to MiSeq reporter workflow below). 

I compared bcbio calls for NA12878 to the [MSR workflow](https://support.illumina.com/help/BaseSpaceHelp/Content/Vault/Informatics/Sequencing_Analysis/BS/swSEQ_mBS_AmpliconWorkflow.htm) and found it performs better than bcbio variant2 workflow (untrimmed or primer trimmed reads**, bwa aligned, ensemble calling with freebayes/gatk-haplotype/samtools).

I used the MSR bam files as input into a couple variant callers and get results close to MSR workflow. MSR workflow keeps primer sequences and aligns against target amplicon sequences and I believe soft-clips the primer sequences prior to variant calling. 

** - I used scripts discussed in[ this paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1189-0) to trim primers identified in the manifest file from the fastq files. Trimming primer sequences helps somewhat, but as implemented it is very slow. 

**Comparison**
![image](https://cloud.githubusercontent.com/assets/7218576/23414392/b8eb6296-fda9-11e6-8d44-ce6333840fa7.png)

Also discussed [here](https://groups.google.com/forum/#!topic/biovalidation/PsHnBCP1pM0).

**Comment by ohofmann** [comment]
I'm interested in this as well as we will have to run some amplicon samples soon, though I was looking at AstraZeneca's VarDict in Amplicon mode. Did you limit variant calls to the regions of the amplicons or call across the whole genome? The F-measure for bcbio/FreeBayes with trimmed reads is pretty much identical to the MSR workflow, but the drop in precision makes me wonder if this was for global calls or just calls in the Amplicon sequences.

**Comment by rjsicko** [comment]
I provided the target regions bed to bcbio so calls are limited to those regions. For the comparison numbers (rtg vcfeval)  I used bcbios "callable bed" which is the intersection of the targets bed and calculated callable regions based on coverage. Yes trimming gets it close for this sample, but I think the extra FN is causing the precision drop. Trimming as I'm currently doing it (scripts from paper above) is also slow and outside of bcbio.

I too was interested in Vardict in amplicon mode but creation of the necessary bed file from the manifest (provides primer sequences not locations) was an issue. I did try VarDict within bcbio and using the MSR bam file but results were not good (all default parameters)

**Comment by chapmanb** [comment]
Bob;
Thanks for the discussion on improving amplicon and panel sequencing. Are you able to share any of this NA12878 data for validation work? There might be some tweaks to bcbio alignment or variant calling we could do to improve sensitivity and specificity.

The data point that stands out to me is freebayes performing well on the MiSeq aligned data. This indicates that bwa-mem alignment heuristics might not be well tuned to this type of data. Have you tried using novoalign instead of bwa for the `aligner` to see how that impacts the results? Another idea is to force use of bwa-mem (`tools_on: [bwa-mem]`) or bwa aln (`tools_off: [bwa-mem]`):

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#tweaking-defaults

This would help determine if the algorithm or alignment approach helps, or if this is all down to the trimming and other custom work that is done in the MiSeq pipeline. Thanks for helping look at this.

**Comment by rjsicko** [comment]
Hi Brad,
Sure I can share NA12878 data. Are google drive links OK? 

I attempted to use novoalign but it generated an error (I think the unlicensed version only supports single core) and I never pushed forward with it. The RTG alignment (RTG trimmed) did miss a few variants though.

I'll add I did find [Katana](https://github.com/umich-brcf-bioinf/Katana) which can soft-clip primer sequences from a bam file, but as with VarDict in amplicon mode, primer locations must be provided.

**Comment by chapmanb** [comment]
Bob;
Thanks much for sharing the NA12878. As a starting point I've been working on replicating your analysis and I'm not getting similar numbers. I used the BED file in the drive folder (`SCIDv2-2_targets_sorted_no_chr.bed`) and I get a lot of off-target reads (65%) and smaller numbers than what you list above:

http://i.imgur.com/NNGoif8.png

Is this the right regions file or are there other tweaks in your bcbio run that I missed? Thanks again for helping share data for improving this.

**Comment by rjsicko** [comment]
The targets file looks right. The fastq I uploaded are from the 'align_prep' folder... I thought they were full fastq files just compressed and indexed by bcbio. In case they aren't what I thought they were, I've uploaded the original fastq files from the 'input' folder. I've also created checksum files for both trimmed and untrimmed fastq. 

Looking at multiqc I got around ~70% on target. 

Here is the yaml for the run
````
details:
  - files: [../input/12_S12_L001_R1_001.fastq.trim.fastq, ../input/12_S12_L001_R2_001.fastq.trim.fastq]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      variantcaller: [freebayes, gatk-haplotype, samtools]
      mark_duplicates: false
      recalibrate: false
      realign: false
      coverage_interval: amplicon
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: ../input/SCIDv2-2_targets_sorted_no_chr.bed
      coverage: ../input/170213_SCID_Exons_w_20bp_Padding.sorted.b37.bed
      ensemble:
        numpass: 2
````
