### ISSUE TITLE
RNA-seq: transcriptome index not getting picked up

### ISSUE THREAD

**Issue by mjafin** [bcbio/bcbio-nextgen#201]
For some reason the tophat alignment commands do not include the transcriptome index and it gets generated for each sample. Here's my hg19-resources.yaml rnaseq section, which I think is correct:

```
rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  transcriptome_index:
    tophat: ../rnaseq/tophat/hg19_transcriptome
```

Does the tophat section need to be an absolute path maybe?

Here's the code using the resources I believe:

```
def _set_transcriptome_option(options, data, ref_file):
    # prefer transcriptome-index vs a GTF file if available
    transcriptome_index = data["genome_resources"]["rnaseq"].get("transcriptome_index", {}).get("tophat")
    if transcriptome_index and file_exists(transcriptome_index + ".1.bt2"):
        options["transcriptome-index"] = transcriptome_index

    gtf_file = data["genome_resources"]["rnaseq"].get("transcripts")
    if gtf_file:
        options["GTF"] = gtf_file
    return options

```
