### ISSUE TITLE
feature request: start from vcf

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2068]
Hi Brad,

We're starting to feel some storage constraints through our usage of bcbio. We'd like to be able to reannotate the resulting vcf files using the bcbio framework, but without having to keep all of the other intermediate files around.

Would it be possible to let the pipeline start from vcf files and perform just the annotations?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
We currently have some support for this, using `vrn_file` instead of `files` in the input configuration. Here's an example from the tests of including a pre-built VCF in a validation:

https://github.com/chapmanb/bcbio-nextgen/blob/a6676f45cafbe9f0ca24ce798a61c27ede36a36c/tests/data/automated/run_info-bam.yaml#L11

I don't use this extensively so am not sure if it does everything you need but that would be the best place to get started. I'd like to expand this to support pre-built gVCF inclusion in joint calling workflows, so let us know if you run into issues.

**Comment by matthdsm** [comment]
Allright, sounds great! Happy to hear there's already some support. We're starting from pre-built GVCF's so it'd be a huge help if this would work.
I'll give it a shot and get back to you if I run into any issues.

Cheers and thanks for the foresight.
M

**Comment by matthdsm** [comment]
Hi Brad,

I've finally come around to testing this feature (better late than never I suppose).
So here's the case. I've got some gvcf's from previous runs, which I'm now trying to combine into one multisample gemini db. 
I'd like to get bcbio to 
- take the gvcf's and perform joint calling per batch
- reannotate the joint vcf
- create a gemini db

To do this, I'm using the following config with bcbio v1.0.9:
```
fc_name: family1
upload:   
  dir: ../final
globals:
  analysis_regions: /genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: D1712121
    vrn_file: ../input/D1712121-gatk-haplotype.vcf.gz
    metadata:
      batch: family1
    algorithm:
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
  - analysis: variant2
    genome_build: hg38
    description: D1611710
    vrn_file: ../input/D1611710-gatk-haplotype.vcf.gz
    metadata:
      batch: family1
    algorithm:
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
  - analysis: variant2
    genome_build: hg38
    description: D1712122
    vrn_file: ../input/D1712122-gatk-haplotype.vcf.gz
    metadata:
      batch: family1
    algorithm:
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
```

This does work, but there's no joint calling, no db's are created, and no results ,except some QC, is copied to the final directory.

Do you have any pointers on how to get where I want to be?

Thanks a lot
M
