### ISSUE TITLE
Confused: Identical output for different subjects

### ISSUE THREAD

**Issue by biocyberman** [bcbio/bcbio-nextgen#209]
Hi, 
I am running bcbio-nextgen 0.76a. Following is excerpt of my yaml file, where each `files` group is for one distinct subject/person:

``` yaml
upload:
  dir: ../final
details:
- algorithm:
    aligner: false
    coverage_depth: high
    coverage_interval: exome
    mark_duplicates: picard
    platform: SOLiD
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variant_regions: ../bed_files/exome_kits/S04380110_Covered_editted.bed
    variantcaller: gatk
  analysis: variant2
  metadata:
    batch: Project02
  description: 5_MRKH_1
  files: 
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L01-1-Idx_1-1.bam
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L02-2-Idx_1-1.bam
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L03-3-Idx_1-1.bam
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L04-4-Idx_1-1.bam
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L05-5-Idx_1-1.bam
    - ../input/Project02_BC1/Project02_FC2_B3_5TO10_L06-6-Idx_1-1.bam
  genome_build: GRCh37wd
# some more subjects
- algorithm:
    aligner: false
    coverage_depth: high
    coverage_interval: exome
    mark_duplicates: picard
    platform: SOLiD
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variant_regions: ../bed_files/exome_kits/S04380110_Covered_editted.bed
    variantcaller: gatk
  analysis: variant2
  metadata:
    batch: Project02
  description: 10_MRKH_6
  files:
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L01-1-Idx_6-6.bam
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L02-2-Idx_6-6.bam
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L03-3-Idx_6-6.bam
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L04-4-Idx_6-6.bam
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L05-5-Idx_6-6.bam
    - ../input/Project02_BC6/Project02_FC2_B3_5TO10_L06-6-Idx_6-6.bam
  genome_build: GRCh37wd
fc_date: '131205'
fc_name: Project02
```

After running, I got identical output (variants) for different subjects. Following diff commands compared outputs for first and last subjects:

``` diff
diff ./final/10_MRKH_6/10_MRKH_6-gatk.vcf ./final/5_MRKH_1/5_MRKH_1-gatk.vcf                                                                                                                                                   [11:21AM]
14c14
< ##GATKCommandLine=<ID=SelectVariants,Version=2.6-5-gba531bd,Date="Thu Dec 05 20:31:58 CET 2013",Epoch=1386271918842,CommandLineOptions="analysis_type=SelectVariants input_file=[] read_buffer_size=null phone_home=AWS gatk_key=null tag=NA read_filter=[BadCigar, NotPrimaryAlignment] intervals=null excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37wd/seq/GRCh37wd.fa nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 allow_bqsr_on_reduced_bams_despite_repeated_warnings=false validation_strictness=SILENT remove_program_records=false keep_program_records=false unsafe=LENIENT_VCF_PROCESSING disable_auto_index_creation_and_locking_when_reading_rods=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false logging_level=INFO log_to_file=null help=false version=false variant=(RodBinding name=variant source=./work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_6-6-variants-ploidyfix.vcf) discordance=(RodBinding name= source=UNBOUND) concordance=(RodBinding name= source=UNBOUND) out=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub no_cmdline_in_header=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sites_only=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub bcf=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sample_name=[] sample_expressions=null sample_file=null exclude_sample_name=[] exclude_sample_file=[] select_expressions=[] excludeNonVariants=false excludeFiltered=false restrictAllelesTo=ALL keepOriginalAC=false mendelianViolation=false mendelianViolationQualThreshold=0.0 select_random_fraction=0.0 remove_fraction_genotypes=0.0 selectTypeToInclude=[INDEL, MIXED, MNP, SYMBOLIC, NO_VARIATION] keepIDs=null fullyDecode=false forceGenotypesDecode=false justRead=false maxIndelSize=2147483647 ALLOW_NONOVERLAPPING_COMMAND_LINE_SAMPLES=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">

---
diff ./final/10_MRKH_6/10_MRKH_6-gatk.vcf ./final/5_MRKH_1/5_MRKH_1-gatk.vcf                                                                                                                                                   [11:21AM]
14c14
< ##GATKCommandLine=<ID=SelectVariants,Version=2.6-5-gba531bd,Date="Thu Dec 05 20:31:58 CET 2013",Epoch=1386271918842,CommandLineOptions="analysis_type=SelectVariants input_file=[] read_buffer_size=null phone_home=AWS gatk_key=null tag=NA read_filter=[BadCigar, NotPrimaryAlignment] intervals=null excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37wd/seq/GRCh37wd.fa nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 allow_bqsr_on_reduced_bams_despite_repeated_warnings=false validation_strictness=SILENT remove_program_records=false keep_program_records=false unsafe=LENIENT_VCF_PROCESSING disable_auto_index_creation_and_locking_when_reading_rods=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false logging_level=INFO log_to_file=null help=false version=false variant=(RodBinding name=variant source=./work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_6-6-variants-ploidyfix.vcf) discordance=(RodBinding name= source=UNBOUND) concordance=(RodBinding name= source=UNBOUND) out=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub no_cmdline_in_header=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sites_only=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub bcf=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sample_name=[] sample_expressions=null sample_file=null exclude_sample_name=[] exclude_sample_file=[] select_expressions=[] excludeNonVariants=false excludeFiltered=false restrictAllelesTo=ALL keepOriginalAC=false mendelianViolation=false mendelianViolationQualThreshold=0.0 select_random_fraction=0.0 remove_fraction_genotypes=0.0 selectTypeToInclude=[INDEL, MIXED, MNP, SYMBOLIC, NO_VARIATION] keepIDs=null fullyDecode=false forceGenotypesDecode=false justRead=false maxIndelSize=2147483647 ALLOW_NONOVERLAPPING_COMMAND_LINE_SAMPLES=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">

---
> ##GATKCommandLine=<ID=SelectVariants,Version=2.6-5-gba531bd,Date="Thu Dec 05 20:31:58 CET 2013",Epoch=1386271918720,CommandLineOptions="analysis_type=SelectVariants input_file=[] read_buffer_size=null phone_home=AWS gatk_key=null tag=NA read_filter=[BadCigar, NotPrimaryAlignment] intervals=null excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=/usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37wd/seq/GRCh37wd.fa nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 allow_bqsr_on_reduced_bams_despite_repeated_warnings=false validation_strictness=SILENT remove_program_records=false keep_program_records=false unsafe=LENIENT_VCF_PROCESSING disable_auto_index_creation_and_locking_when_reading_rods=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false logging_level=INFO log_to_file=null help=false version=false variant=(RodBinding name=variant source=./work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_1-1-variants-ploidyfix.vcf) discordance=(RodBinding name= source=UNBOUND) concordance=(RodBinding name= source=UNBOUND) out=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub no_cmdline_in_header=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sites_only=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub bcf=org.broadinstitute.sting.gatk.io.stubs.VariantContextWriterStub sample_name=[] sample_expressions=null sample_file=null exclude_sample_name=[] exclude_sample_file=[] select_expressions=[] excludeNonVariants=false excludeFiltered=false restrictAllelesTo=ALL keepOriginalAC=false mendelianViolation=false mendelianViolationQualThreshold=0.0 select_random_fraction=0.0 remove_fraction_genotypes=0.0 selectTypeToInclude=[INDEL, MIXED, MNP, SYMBOLIC, NO_VARIATION] keepIDs=null fullyDecode=false forceGenotypesDecode=false justRead=false maxIndelSize=2147483647 ALLOW_NONOVERLAPPING_COMMAND_LINE_SAMPLES=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">
127c127
< ##SnpEffCmd="SnpEff  -1 -i vcf -o vcf GRCh37.71 ./work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_6-6-variants-ploidyfix-combined.vcf "

---
> ##SnpEffCmd="SnpEff  -1 -i vcf -o vcf GRCh37.71 ./work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_1-1-variants-ploidyfix-combined.vcf "
(bcbio-dev)user@localhost[final] diff ../work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_6-6-variants-ploidyfix.vcf ../work/gatk/Project02_FC2_B3_5TO10_L06-6-Idx_1-1-variants-ploidyfix.vcf 
```

What am I doing wrong here? 
Thanks
