### ISSUE TITLE
gatk-variant template non-zero exit status 250

### ISSUE THREAD

**Issue by alongalor** [bcbio/bcbio-nextgen#2190]
Hello!

I am using the `gatk-variant` template and have encountered some issues I would really appreciate any help with.

Upon executing the following command:

`bcbio_nextgen.py /n/data1/hms/dbmi/park/alon/software/bcbio/project2/config/project2.yaml -t ipython -n 64 -s lsf -q park_long
`

things run smoothly for a few hours and then an error appears. 

the `bcbio-nextgen-debug.log`  is attached.
[bcbio-nextgen-debug.log](https://github.com/chapmanb/bcbio-nextgen/files/1569477/bcbio-nextgen-debug.log)

The commands I used are as follows:
```
# Installation
mkdir /n/data1/hms/dbmi/park/alon/software/bcbio
cd /n/data1/hms/dbmi/park/alon/software/bcbio
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python ./bcbio_nextgen_install.py /n/data1/hms/dbmi/park/alon/software/bcbio/share/bcbio-nextgen --tooldir=/n/data1/hms/dbmi/park/alon/software/bcbio --genomes GRCh37 --aligners bwa
gatk-register /n/data1/hms/dbmi/park/alon/software/gatk/GenomeAnalysisTK-3.8-0.tar.bz2 
bcbio_setup_genome.py -f /n/data1/hms/dbmi/park/alon/software/gatk/human_g1k_v37_decoy.fasta -i bwa -n hs37d5 -b hs37d5

# gatk-variant pipeline
cd /n/data1/hms/dbmi/park/alon/software/bcbio/
bcbio_nextgen.py -w template gatk-variant project2
# manually edit template file: /n/data1/hms/dbmi/park/alon/software/bcbio/project2/config/project2-template.yaml, eddited as shown below*
nano /n/data1/hms/dbmi/park/alon/software/bcbio/project2.csv
# enter the following:
samplename,batch,sex
A10_S10_L008,batch1,male
bcbio_nextgen.py -w template /n/data1/hms/dbmi/park/alon/software/bcbio/project2/config/project2-template.yaml /n/data1/hms/dbmi/park/alon/software/bcbio/project2.csv /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/sourceData/fastq/Vaccarino/A10_S10_L008_R1_001.fastq.gz /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/sourceData/fastq/Vaccarino/A10_S10_L008_R2_001.fastq.gz 
cd /n/data1/hms/dbmi/park/alon/software/bcbio/project2/work
bcbio_nextgen.py /n/data1/hms/dbmi/park/alon/software/bcbio/project2/config/project2.yaml -t ipython -n 64 -s lsf -q park_long
```

*for reference, my `project2-template.yaml` reads as follows:

```
# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - analysis: variant2
    genome_build: GRCh37
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: gatk
      realign: gatk
      variantcaller: false
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

Thanks a lot for your help!

Alon
