### ISSUE TITLE
Support for STAR on the fly use of GTF file, ie. specied in analysis yaml

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2223]
I would like to run some RNA-seq data trough the RNA-seq pipeline in bcbio, using STAR as the aligner. 

I installed the reference genome without specifying an GTF file.  This because I would like to be able to specify a (different) GTF file per analysis. 

Star support using the GTF file on the fly at the mapping step:

`--sjdbGTFfile species the path to the file with annotated transcripts in the standard GTF format. STAR will extract splice junctions from this file and use them to greatly improve accuracy of the mapping. While this is optional, and STAR can be run without annotations, using annotations is highly recommended whenever they are available. Starting from 2.4.1a, the annotations can also be included on the fly at the mapping step.`

 
I tried to `--sjdbGTFfile ` as an extra star argument in the my yaml:

```
details:
- algorithm:
    aligner: star
    coverage_interval: genome
    quality_format: standard
    strandedness: unstranded
    transcript_assembler:
    - stringtie
    - cufflinks
    variantcaller: gatk-haplotype
  analysis: RNA-seq
  description: DA_1078_01
  files:
  - /data/run/Projects/DA_1078/input_fastq/concat/DA_1078_01_R1.fastq.gz
  - /data/run/Projects/DA_1078/input_fastq/concat/DA_1078_01_R2.fastq.gz
  genome_build: UC_Illumina_pseudochr_6
  lane: DA_1078_01
  metadata:
    batch: DA_1078
fc_name: DA_1078_samples-merged
resources:
  star:
    options:
    - --sjdbGTFfile /tools/bioinfo/app/snpeff/data/UC_Illumina_pseudochr_6/genes.gtf
upload:
  dir: ../final
```

This extra star argument does not seem to be used. If I look at the star command used in the `bcbio-command.log` file I see:

`--sjdbGTFfile None`

I doesn't look like this functionality is already in the bcbio star wrapper. 
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/star.py

Would it be possible to add the functionality to have gtf file specified in the yaml file and then looked up during creation of the star command?
