### ISSUE TITLE
Is or could STAR multi-sample 2 pass mapping of RNA-seq be supported in bcbio? 

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2237]
Hi, 

Is it already possible, or would it be possible, so support 2 pass RNA-seq mapping via STAR in bcbio?

From the star manual I understand that it its recommended to do 2 pass multi-sample mapping:

```
For a study with multiple samples, it is recommended to collect 1st pass junctions from all samples.
1. Run 1st mapping pass for all samples with "usual" parameters. Using annotations is recom-
mended either a the genome generation step, or mapping step.
2. Run 2nd mapping pass for all samples , listing SJ.out.tab files from all samples in
--sjdbFileChrStartEnd /path/to/sj1.tab /path/to/sj2.tab ....
```

https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf

I ran a multiple sample RNA-seq analysis in bcbio with the following yaml. 

```
# Template for  RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: UC_Illumina_pseudochr_6
    algorithm:
      aligner: star
      strandedness: unstranded
      transcript_assembler: [stringtie, cufflinks]
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
upload:
   dir: ../final
```

I don't see the `sjdbFileChrStartEnd ` arguments used in the bcbio command log, so I think currently STAR is always just run in a single pass. 
`grep sjdbFileChrStartEnd log/bcbio-nextgen-commands.log`

Would it be possible to add the STAR multi-sample 2 pass mapping of RNA-seq functionality in bcbio? The manual says it's always recommended, and I guess it especially makes sense when not having a good existing gene model, but do having multiple RNA-seq samples. 

Thank you.
