### ISSUE TITLE
Improving the memory usage and time to restart for bcbio_nextgen.py

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#2275]
Hi,

I have noticed that for large analysis the amount of memory required by the main bcbio controller script (bcbio_nextgen.py) can become (very) high. 

For example this analysis starting from BAM described below requires more than 110GB of memory for the main bcbio controller script. 
Also the analysis takes several hours (4+) to restart from a previous crash or abort. 

```
details:
  - analysis: variant2
    genome_build: my_reference
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: DA_1234
    algorithm:
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy:
          default: 2
      nomap_split_targets: 3000
      effects: false
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

See also these log statements that show that already the `piped_bamprep` step (which has already finished in a previous analysis) takes 1 hours and 40 minutes. Preparing for / or checking the variant calling  `variantcall_sample` is already running 2 hours  and did not yet finish. 

I am waiting for GVCF merge to start (which previously crashed because of Picard wrong Java version error, which is now fixed by upgrading to bcbio 1.0.8)

```
[2018-02-17T09:50Z] machinex2: multiprocessing: calculate_sv_bins
[2018-02-17T09:50Z] machinex2: multiprocessing: calculate_sv_coverage
[2018-02-17T09:50Z] machinex2: multiprocessing: normalize_sv_coverage
[2018-02-17T09:50Z] machinex2: Timing: hla typing
[2018-02-17T09:50Z] machinex2: Resource requests: gatk, gatk-haplotype, picard; memory: 3.50, 3.00, 3.00; cores: 1, 16, 16
[2018-02-17T09:50Z] machinex2: Configuring 74 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2018-02-17T09:51Z] machinex2: Timing: alignment post-processing
[2018-02-17T09:56Z] machinex2: ipython: piped_bamprep
[2018-02-17T11:40Z] machinex2: Timing: variant calling
[2018-02-17T11:52Z] machinex2: ipython: variantcall_sample
```

I guess this has to do with the high number of (GVCF) outputs created by this analysis. For example 200 samples * 3000 regions = 600.000 GVCF outputs. 
The main controller script probably has a dictionary or something that keeps track of which BAM, BED and GVCF outputs have been created. 

Would it be possible to reduce the amount of memory needed by the main controller script for tracking large analysis? 
And maybe also to improve the restart speed?

This is not (yet) a blocking issue but more of an nice to have. 

It might be(come) more of a blocking issue for very large analysis of multiple thousands or 10 thousands of samples. Of course there is then the option to reduce the number of `nomap_split_targets` .

Thank you.
