### ISSUE TITLE
Trimming for adapter and read length in small RNA

### ISSUE THREAD

**Issue by markdunning** [bcbio/bcbio-nextgen#2291]
Hi all,

We have some small-RNA data where the manufacturer protocol recommends removing adapter and trimming some bases at the beginning and end of reads. The procedure is described here as two separate cutadapt operations

http://www.biooscientific.com/Portals/0/NGS/NEXTflex_Small_RNA_v3_Trimming_Instructions.pdf

Is there a way we can perform these operations via the small-rnaseq pipeline of bcbio? I know you can specify an adapter, but from my understanding trimming reads (`trim_ends` argument) only seems to be used for variant calling?

Thanks,

**Comment by lpantano** [comment]
Hi,

Thanks for the question. It is actually implemented. You need to add this to your yaml file under resources:

`atropos:options:["-u 4", "-u -4"]`

More information here:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#smallrna-sequencing

So, with that, first it will remove the adapter and then cut 4 nts from both sides. 

Let me know if that works.

**Comment by markdunning** [comment]
Hi,

I'm still having some problems I'm afraid. I've run bcbio both with and without the extra resources specified, and the contents of `work/trimmed` seem the same to me. In the log files for trimming, I can't see any mention of the `-u` and `-U` arguments. 

```

This is cutadapt 1.16 with Python 2.7.14
Command line parameters: -a TGGAATTCTCGGGTGCCAAGG --untrimmed-output=/shared/bioinformatics_core1/Shared/wip/parker_miRNA_biomarkers/all_samples-merged/work/trimmed/102_v1/102_v1.fragments.fastq.gz -o /shared/bioinformatics_core1/Shared/wip/parker_miRNA_biomarkers/all_samples-merged/work/bcbiotx/tmpmQ9DDu/102_v1.clean.fastq.gz -m 17 --overlap=8 /shared/bioinformatics_core1/Shared/wip/parker_miRNA_biomarkers/merged_fastq/102_v1.fastq.gz --too-short-output 102_v1
Running on 1 core
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
Finished in 372.91 s (34 us/read; 1.78 M reads/minute).

```

How do I know if addition trimming has been performed? Should I get extra / different fastq files? Here are the contents of my yaml file

```
details:
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirdeep2
    species: hsa
  analysis: smallRNA-seq
  description: 102_v1
  files:
  - /shared/bioinformatics_core1/Shared/wip/parker_miRNA_biomarkers/merged_fastq/102_v1.fastq.gz
  genome_build: GRCh37
  metadata: {}
  resources:
    atropos:
        options: ["-u 4", "-u -4"]

```

Thanks!
