### ISSUE TITLE
atropos not using multi-core?

### ISSUE THREAD

**Issue by hliang** [bcbio/bcbio-nextgen#2332]
The trimming step was taking too long, so I looked into the commands.log and found that atropos command did not use multi-threading:
```
atropos trim   --quality-base 33 --format fastq \
-a AAAAAAAAAAAAA -a TTTTTTTTTTTTT -a AGATCGGAAGAG \
-a CTCTTCCGATCT -a AACACTCTTTCCCT -a AGATCGGAAGAGCG \
-a AGGGAAAGAGTGTT -a CGCTCTTCCGATCT -A AAAAAAAAAAAAA \
-A TTTTTTTTTTTTT -A AGATCGGAAGAG -A CTCTTCCGATCT \
-A AACACTCTTTCCCT -A AGATCGGAAGAGCG -A AGGGAAAGAGTGTT \
-A CGCTCTTCCGATCT --no-default-adapters \
-pe1 /path/to/rnabcbio/input/LM_74_1.clean.fq.gz \
-pe2 /path/to/rnabcbio/input/LM_74_2.clean.fq.gz \
-o >(bgzip -c > /path/to/rnabcbio/work/bcbiotx/tmpjSlIeq/LM_74_1.clean-trimmed.fq.gz) \
-p >(bgzip -c > /path/to/rnabcbio/work/bcbiotx/tmpjSlIeq/LM_74_2.clean-trimmed.fq.gz) \
--report-file /path/to/rnabcbio/work/bcbiotx/tmpjSlIeq/LM_74_1.clean-report.json -\
-report-formats json --sample-id LM74 --quality-cutoff=5 \
--minimum-length=25 --nextseq-trim=25
```
I'm using the development version installed in late Feb. Below is my config yaml file.
```
---
fc_date: '20180312'
fc_name: hyyfcid
details:
  - description: 'LM74'
    files: [../input/LM_74_1.clean.fq.gz, ../input/LM_74_2.clean.fq.gz]
    analysis: RNA-seq
    genome_build: mm10
    algorithm:
      quality_format: Standard
      aligner: tophat2
      trim_reads: read_through
      adapters: [truseq, polya, illumina]
      strandedness: unstranded
upload:
  dir: ../final
```
Is there a 'cores' setting for trimming/atropos?
