### ISSUE TITLE
expression_caller sailfish failed for hg19

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2337]
Hi, I am trying to run bcbio RNA-seq pipeline for six human samples. The yaml file is as below:
```
upload:
  dir: upload
details:
  - analysis: RNA-seq
    algorithm:
      fusion_caller: [oncofuse]
      variantcaller: [gatk-haplotype]
      #transcriptome_align: True
      aligner: star
      quality_format: standard
      #trim_reads: read_through
      #adapters: [truseq, polya]
      #tools_on: [gatk4]
      expression_caller: [cufflinks, stringtie, sailfish]
      transcript_assembler: [cufflinks, stringtie]
      #spikein_fasta: ../data/spikeins/spikeins.fa
    metadata:
      batch: TestBatch1
    description: Test1
    genome_build: hg19

```
However, error occurred when bcbio call sailfish to estimate the expression. The error information is as follows. 

> [2018-03-16T10:16Z] Warning: Using default Gaussian distribution due to insufficient paired-end reads in open ranges.  It is recommended that correct parameters (--frag-len-mean and --frag-len-std-dev) be provided.
> [2018-03-16T10:16Z] > Map Properties:
> [2018-03-16T10:16Z] >   Normalized Map Mass: 23325.37
> [2018-03-16T10:16Z] >   Raw Map Mass: 23325.37
> [2018-03-16T10:16Z] >   Number of Multi-Reads: 725 (with 1252 total hits)
> [2018-03-16T10:16Z] >   Fragment Length Distribution: Truncated Gaussian (default)
> [2018-03-16T10:16Z] >                 Default Mean: 200
> [2018-03-16T10:16Z] >              Default Std Dev: 80
> [2018-03-16T10:16Z] [18:16:54] Learning bias parameters.
> [2018-03-16T10:20Z] Processed 33749 loci.
> [2018-03-16T10:20Z] [18:20:03] Loading reference annotation.
> [2018-03-16T10:20Z] [18:20:04] Re-estimating abundances with bias and multi-read correction.
> [2018-03-16T11:13Z] Processed 33749 loci.
> [2018-03-16T11:13Z] multiprocessing: run_stringtie_expression
> [2018-03-16T11:13Z] multiprocessing: run_sailfish_index
> [2018-03-16T11:13Z] Converting /app/smartngs/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf to FASTA format.
> [2018-03-16T11:14Z] Creating sailfish index for /app/datamart/RNAseq-example/seqc/work/inputs/transcriptome/hg19.fa with 31 bp kmers.
> [2018-03-16T11:16Z] Version Info: Could not resolve upgrade information in the alotted time.
> [2018-03-16T11:16Z] Check for upgrades manually at www.cs.cmu.edu/~ckingsf/sailfish.
> [2018-03-16T11:16Z] writing log to /app/datamart/RNAseq-example/seqc/work/bcbiotx/tmp_vIEqC/hg19/logs/sailfish_index.log
> [2018-03-16T11:16Z] RapMap Indexer
> [2018-03-16T11:16Z] [Step 1 of 4] : counting k-mers
> counted k-mers for 190000 transcriptsElapsed time: 8.16884s
> [2018-03-16T11:16Z] Replaced 0 non-ATCG nucleotides
> [2018-03-16T11:16Z] Clipped poly-A tails from 1480 transcripts
> [2018-03-16T11:16Z] Building rank-select dictionary and saving to disk done
> [2018-03-16T11:16Z] Elapsed time: 0.59684s
> [2018-03-16T11:16Z] Writing sequence data to file . . . done
> [2018-03-16T11:16Z] Elapsed time: 2.49467s
> [2018-03-16T11:16Z] [info] Building 32-bit suffix array (length of generalized text is 286511308)
> [2018-03-16T11:17Z] Building suffix array . . . success
> [2018-03-16T11:17Z] saving to disk . . . done
> [2018-03-16T11:17Z] Elapsed time: 19.5162s
> [2018-03-16T11:17Z] done
> [2018-03-16T11:17Z] Elapsed time: 46.8833s
> processed 286000000 positions
> [2018-03-16T11:19Z] khash had 118643244 keys
> [2018-03-16T11:19Z] saving hash to disk . . . done
> [2018-03-16T11:19Z] Elapsed time: 32.9192s
> [2018-03-16T11:19Z] multiprocessing: run_sailfish
> Traceback (most recent call last):
>   File "/app/smartngs/bcbio/anaconda/bin/bcbio_nextgen.py", line 241, in <module>
>     main(**kwargs)
>   File "/app/smartngs/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
>     run_main(**kwargs)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
>     fc_dir, run_info_yaml)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 249, in rnaseqpipeline
>     samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 134, in quantitate_expression_parallel
>     samples = run_parallel("run_sailfish", samples)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 82, in run_multicore
>     items = [config_utils.add_cores_to_config(x, parallel["cores_per_job"]) for x in items]
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 305, in add_cores_to_config
>     return _update_config(args, _update_cores)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 320, in _update_config
>     raise ValueError("Could not find configuration in args: %s" % str(args))
> ValueError: Could not find configuration in args: {'files': ['..........

Can you help me??
