### ISSUE TITLE
rnaseq gffread error: improper genomic coordinate

### ISSUE THREAD

**Issue by skanwal** [bcbio/bcbio-nextgen#2341]
Hi Rory/Brad,

I am trying to create a workflow using the following yaml description:
```
details:
- algorithm:
    aligner: star
    expression_caller: kallisto
    fusion_caller: pizzly
    quality_format: Standard
    strandedness: unstranded
    #trim_reads: read_through
  analysis: RNA-seq
  description: RNA-Test2
  files:
  - /data/cephfs/punim0010/extras/sehrish/RNAseq/seqc-test/input/sampleA2_1.fq.gz
  - /data/cephfs/punim0010/extras/sehrish/RNAseq/seqc-test/input/sampleA2_2.fq.gz
  genome_build: GRCh37
  metadata:
    panel: E-MTAB
fc_name: seqc
upload:
  dir: ../final
```

It is returning a non-zero exit status 1 with the following error message:
```
CalledProcessError: Command 'set -o pipefail; gffread -g /data/cephfs/punim0010/extras/sehrish/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -w /data/cephfs/punim0010/extras/sehrish/RNAseq/seqc-test/rna-seq/work/bcbiotx/tmp0gPiLj/GRCh37.fa.tmp /data/cephfs/punim0010/extras/sehrish/bcbio/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.gtf
GffObj::getSpliced() error: improper genomic coordinate 92824 on 10 for ENST00000416477
```

Looking at the log files, the alignment using star is finished successfully, however it fails at the `run_kallisto_index` step. 
The complete log files are provided at the following gist:
https://gist.github.com/skanwal/a9fe258f3f02129a2133916041303509 

I am not using any custom genome installation. Not sure what might be the root cause of the issue?
Any help will be appreciated.

Thanks.
