### ISSUE TITLE
bcbio-nextgen for coverage QC only

### ISSUE THREAD

**Issue by vladsaveliev** [bcbio/bcbio-nextgen#2343]
I often run bcbio just to get coverage statistics (indexcov, mosdepth, qualimap, samtools stats, multiqc) for a set of (external) BAM files. For e.g. my yaml would look like this:

```
  - analysis: variant2
    algorithm:
        aligner: none
        recalibrate: false
        realign: false
        mark_duplicates: false
        remove_lcr: false
        maxcov_downsample: false
        coverage: /data/cephfs/punim0010/extras/2018-02-16_PMCC_Panel_Regions.bed
        tools_on: [gatk4, qualimap_full, noalt_calling]
        tools_off: [upload_alignment]
        bam_clean: fixrg

    description: longranger_pos_sorted
    files: /data/cephfs/punim0010/projects/Saveliev_10X/NA12878-10x/bcbio_grch37/bams/longranger_pos_sorted.bam
    genome_build: GRCh37
```

However, there are two issues with that. 

1. Firstly, some QC is not done when `aligner` is set to `none`:
   - it skips running `goleft indexcov` 
   - the `mosdepth` command is not feed with coverage thresholds (`-T 1,5,10,20,50,100,250,500,1000,5000,10000,50000`), leading to missing `*-coverage.mosdepth.dist.txt` files, preventing bcbio coverage MultiQC plots from being generated.

2. Secondly, `RG` for external BAMs is unpredictable and in most cases bcbio requires me to add `bam_clean: fixrg`, and this clean up is often as slow as doing full alignment. I don't really think read groups are used by any QC program, can this check be optional by any chance?

No urgency with this issue - I even wanted to leave it to take a look by myself when I have some time, but leaving it for record here (and just in case if anyone else would pick it up or it's 5 minutes of work for Brad :)

Vlad
