### ISSUE TITLE
gemini db not generated in v1.0.9

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2370]
Hi Brad,

I've got a fresh install of bcbio v1.0.9, which runs smoothly. I only just noticed that there's no mention whatsoever of gemini db's in the work/final dir, nor in the log. It seems the step is skipped altogether.

I'm using the following config:
```
#bcbio-nextgen v1.0.9
---
#include an experiment name here
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: RefSeqExomeAndPanels.bed
  coverage_regions: RefSeqExomeAndPanels.bed
resources:
  tmp:
    dir: $SCRATCH/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      exclude_regions: [altcontigs]
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - coverage_perbase
      tools_off:
        - gatk4
    # add the path to your files here
    files:
```

Any idea what could be causing this behaviour? Or could this be the same issue where no db's are generated if the "gemini" datatarget isn't installed?

Cheers
M
