### ISSUE TITLE
VEP run twice, resulting in longer runtimes

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2373]
Hi Brad,

as a small follow up on the issue yesterday, I noticed the resulting vcf files are annotated twice. Is the normal behavior? 
VEP runs right after GATK is done genotyping, and is then run again after decomposing the vcf. For one exome, this causes about a 20 min slowdown (12 cores), but when analyzing 50+ samples, this starts to add up.

Is there a way to avoid the extra step?

extra info: bcbio v1.0.9 stable
config:
```
#bcbio-nextgen v1.0.9
---
#include an experiment name here
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: RefSeqExomeAndPanels_20171003.bed
  coverage_regions: RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: $VSC_SCRATCH_VO_USER/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      exclude_regions: [altcontigs]
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - coverage_perbase
      tools_off:
        - gatk4
    # add the path to your files here
    files:
```

Cheers
M
