### ISSUE TITLE
inconsistencies in joint variant calling + ensemble VCF creation

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2412]
Hello,

I've been testing the jointcaller feature of Bcbio, as I'm planning to run this later on a large number of samples (several hundred up to a few thousand). My settings are as such:

```
algorithm:
      mark_duplicates: false
      bam_clean: fixrg
      recalibrate: false
      realign: false
      tools_off: gemini
      tools_on: svplots
      variantcaller: [gatk-haplotype, freebayes, platypus, samtools]
      jointcaller: [gatk-haplotype-joint, freebayes-joint, platypus-joint, samtools-joint]
      ensemble:
        numpass: 2
      ploidy: 1
```

I've noticed a couple of things that appear suspicious or inconsistent:

1. I have recently installed the latest version of Bcbio and also updated it to the current development version. Later, while testing the `jointcaller` feature, I got errors such as `gatk-framework: command not found`. To mitigate this, I installed the `gatk-framework` bioconda package by running:

`bcbio_conda install -c conda-forge -c bioconda gatk-framework`

This installed an older version of GATK: 

```
gatk-framework --version
3.6-24-g59fd391
```

However, this means that Bcbio is now running two versions of GATK, the older one and the latest at this moment (4.0.3.0), which was installed automatically. I am guessing that GATK4 is used by default, while GATK3 is only used for joint genotyping. Is this correct? 

Would it somehow be possible to use the latest GATK4 for joint genotyping as well? 

2. I've managed to run the analysis correctly. My intention was to create an ensemble set with variants found by at least two of the four variant callers that I enabled. However, when checking the final ensemble VCF file, I noticed that all variants have the CALLERS value as such:

```
CALLERS=samtools,samtools-joint;
CALLERS=gatk-haplotype,gatk-haplotype-joint,freebayes,freebayes-joint,platypus,platypus-joint,samtools,samtools-joint;
CALLERS=gatk-haplotype,gatk-haplotype-joint;
```

Why does Bcbio report the callers twice? Even though I had the `numpass: 2` option enabled, this essentially resulted in reporting variants that were found by only one variant caller. Would it be possible to only report variants whose callers are `samtools-joint`, `gatk-haplotype-joint` etc. when the `jointcaller` option is present?

Which part of the source code handles joint genotyping in Bcbio-nextgen?
