### ISSUE TITLE
GATK4 GatherVcfs "first record in file ... is not after first record in previous file"

### ISSUE THREAD

**Issue by sxv** [bcbio/bcbio-nextgen#2420]
Hi,

I am excited to be using the new gatk4 workflow on a fresh bcbio development install. In this case I'm running a tumor/normal pair of targeted DNA-Seq from pre-aligned bam files. I've read mixed opinions about whether or not recalibration is recommended for gatk4, so advice on that would be helpful as well. Anyway, I'm getting the following error message:

> [Wed Jun 20 10:54:08 PDT 2018] Executing on Linux 4.13.0-43-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_144-b01; Deflater: Intel; Inflater: Intel; Picard version: Version:4.0.3.0
> INFO    2018-06-20 10:54:08     GatherVcfs      Checking inputs.
> INFO    2018-06-20 10:54:08     GatherVcfs      Checking file headers and first records to ensure compatibility.
> [Wed Jun 20 10:54:08 PDT 2018] picard.vcf.GatherVcfs done. Elapsed time: 0.00 minutes.
> Runtime.totalMemory()=460259328
> To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
> java.lang.IllegalArgumentException: First record in file /15/mutect2/chr1/prostate_lcm_15_19-chr1_109811749_142535913.vcf.gz is not after first record in previous file /15/mutect2/prostate_lcm_15_19-chrM_0_16571-fixheader.vcf.gz
>         at picard.vcf.GatherVcfs.assertSameSamplesAndValidOrdering(GatherVcfs.java:128)
>         at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:74)
>         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
>         at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
>         at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
>         at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
>         at org.broadinstitute.hellbender.Main.main(Main.java:289)
> ' returned non-zero exit status 3

Here are the first lines of the vcfs:

`$ zcat /15/mutect2/chr1/prostate_lcm_15_19-chr1_109811749_142535913.vcf.gz | grep -v ^# | head -1
`
> chr1    121484118       .       G       A       .       artifact_in_normal;clustered_events;mapping_quality     ClippingRankSum=0;DP=176;ECNT=6;FS=18.372;MQ=30.56;MQ0=0;MQRankSum=0.498;NLOD=3.95;N_ART_LOD=1.28;POP_AF=5e-08;P_CONTAM=0;P_GERMLINE=-21.79;ReadPosRankSum=1.505;TLOD=19.33  GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB  0/1:105,13:0.178:118:52,7:53,6:26:172,0:29:39:0.111,0,0.11:0.0009419,0.689,0.31      0/0:29,2:0.111:31:15,1:14,1:22:213,251:29:47:.:.

`$ zcat /15/mutect2/prostate_lcm_15_19-chrM_0_16571-fixheader.vcf.gz | grep -v ^# | head -1
`
> chrM    12169   .       G       C       .       MinAF;clustered_events;mapping_quality  ClippingRankSum=0;DP=160;ECNT=5;FS=15.473;MQ=57.08;MQ0=0;MQRankSum=-6.637;NLOD=2.41;N_ART_LOD=-0.9542;POP_AF=5e-08;P_CONTAM=0;P_GERMLINE=-37.9;ReadPosRankSum=-2.453;TLOD=14.65      GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:PGT:PID:SA_MAP_AF:SA_POST_PROB  0/1:145,6:0.043:151:80,5:65,1:25:196,251:29:9:0|1:12169_G_C:0.04,0,0.04:0.001676,0.149,0.849 0/0:8,0:3.162e-05:8:6,0:2,0:0:248,0:0:0:0|1:12169_G_C:.:.

Is the error because chr1 shouldn't follow chrM, or something else going on?

Here's my config:
```
---
fc_date: "20180619"
fc_name: "prostate_lcm.15_19"
upload:
  dir: /prostate.lcm/
resources:
  tmp:
    dir: /tmp
details:
  - analysis: variant2
    genome_build: hg19
    metadata:
       batch: prostate.lcm.15_19
       phenotype: tumor
    description: 15.tumor
    files: [PC_AP-14_CAGATC_15_1_2_T34.bam]
    algorithm:
      mark_duplicates: true
      recalibrate: true
      bam_clean: fixrg
      platform: illumina
      tools_off: [gemini]
      tools_on: gatk4
      variantcaller: mutect2
      variant_regions: ../PC_baits.target.bed
  - analysis: variant2
    genome_build: hg19
    metadata:
       batch: prostate.lcm.15_19
       phenotype: normal
    description: 19.normal
    files: [N_AP-14_ATGTCA_19_1_ST1_ST1.bam]
    algorithm:
      mark_duplicates: true
      recalibrate: true
      bam_clean: fixrg
      platform: illumina
      tools_off: [gemini]
      tools_on: gatk4
      variantcaller: mutect2
      variant_regions: ../PC_baits.target.bed
```

Thanks!
