### ISSUE TITLE
Minimal config for RNA-seq variant calling using gatk-haplotype

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2450]
Hi all,

This is not an issue per se but I would like to know if there any documentation on specifically how to turn off all the other tools that aren't necessarily required for variant calling on RNA-seq using `gatk-haplotype`?  

Right now my config file doesn't have anything turned-off: 

```
details:
- algorithm:
    aligner: star
    variantcaller: gatk-haplotype
    # tools_off: gatk4
  analysis: RNA-seq
  description: 'Sample 1: CDL-634-13P'
  files:
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_1.fq.gz
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: CDL-634-13P
fc_name: CDL-634-13P-CDLS
upload:
  dir: /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/final
```
