### ISSUE TITLE
fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2453]
Hi,

I am facing another issue related to Java. I have tried this on 3 different servers, with different memory and core settings but all have the same problem. Here are the logs: 
[logs.txt](https://github.com/bcbio/bcbio-nextgen/files/2198051/logs.txt)

Here is my command:
```
/mnt/isilon/cbmi/variome/bin/bcbio-nextgen/local/bin/bcbio_nextgen.py config.yaml -n 20
```

Config file:

```
details:
- algorithm:
    aligner: star
    variantcaller: gatk-haplotype
    # tools_off: gatk4
  analysis: RNA-seq
  description: 'Sample 1: CDL-634-13P'
  files:
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_1.fq.gz
  - /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/fastq/CDL-634-13P/CDL-634-13P_pe_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: CDL-634-13P
fc_name: CDL-634-13P-CDLS
upload:
  dir: /mnt/isilon/cbmi/variome/rathik/mendelian_rnaseq/bcbio_out/final
resources:
  gatk:
    jvm_opts: ["-Xms2g", "-Xmx4g"]
```

Also, if there is no way this can be fixed then as an alternative how can I skip this step? My goal is to finish the pipeline and just get variant calls in a normal vcf format (I also don't care about the gvcf) from a single sample.
