### ISSUE TITLE
Ericscript not found

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2477]
Hi,

While trying to run ericscript, I ran into the message: Skipping ericscript because ericscript database not found. After skipping ericscript, the run continued to completion.
However I am pretty sure I have upgraded Bcbio with the ericscript database already, found here: 
```
[dlho@n068 ~]ls -R /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/rnaseq/ericscript
/mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/rnaseq/ericscript:
ericscript_db_homosapiens_ensembl84

/mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/rnaseq/ericscript/ericscript_db_homosapiens_ensembl84:
data

/mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/rnaseq/ericscript/ericscript_db_homosapiens_ensembl84/data:
homo_sapiens

/mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/rnaseq/ericscript/ericscript_db_homosapiens_ensembl84/data/homo_sapiens:
allseq.fa                       EnsemblGene.Reference.fa
allseq.fa.amb                   EnsemblGene.Reference.fa.amb
allseq.fa.ann                   EnsemblGene.Reference.fa.ann
allseq.fa.bwt                   EnsemblGene.Reference.fa.bwt
allseq.fa.pac                   EnsemblGene.Reference.fa.pac
allseq.fa.sa                    EnsemblGene.Reference.fa.sa
EnsemblGene.GeneInfo.RData      EnsemblGene.Sequences.RData
EnsemblGene.GeneNames.RData     EnsemblGene.Structures.RData
EnsemblGene.GenePosition.RData  EnsemblGene.Transcripts.RData
EnsemblGene.Paralogs.RData
```

This is my config file:
```
details:
- algorithm:
    aligner: star
    mark_duplicates: true
    coverage: /home/dlho/references/bedfiles/Cancer216-full-targets_hg38.bed
    fusion_caller: ericscript
    save_diskspace: true
    tools_off: [gemini]
  analysis: RNA-seq
  genome_build: hg38
```
How can I get ericscript to run? Thank you.
