### ISSUE TITLE
How to specify fields to load in gemini database by vcf2db?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2478]
Hello!

Thanks for the excellent pipeline!

When using (on grch37)
```
    vcfanno:
    - gemini
    - gnomad_genome
    - dbnsfp
```
some fields go to the gemini database, some not. For example, CADD_phred, Ensembl_geneid are present in annotated-decomposed.vcf.gz, but absent in gemini db.

Is it possible to load them, or the current state-of-art is to query annotated vcf files with bcftools to prioritize variants rather than using gemini db for that?

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for the question. vcf2db should be loading everything from the info field into the database so I'm not sure why you're missing these. Is this with the latest development version of bcbio or an older version? The current development is working to make vcfanno more of the first approach, so would definitely apply these before GEMINI now.

The only cases where vcf2db skips by default is if the INFO field has `Number=A` and will have multiple values so doesn't fit into the schema. Is it possible that's another explanation for the missing annotations?

**Comment by naumenko-sa** [comment]
Thanks for the quick response, Brad!

Just for the record:
1.1.0a0 (unfortunately, cannot test the latest dev right now) does the job for me when gemini is on.
All fields from vcf go to gemini.db.
```
details:
- algorithm:
  tools_on:
  - gemini
  variantcaller: false
  vcfanno:
  - gemini
  - gnomad_genome
  - dbnsfp
  analysis: variant2
  vrn_file: ../input/project.vcf.gz
  genome_build: GRCh37
```
This is an example on how to re-annotate previously called variants.

S.
