### ISSUE TITLE
SM tags in BAM and sample names in the final VCF file

### ISSUE THREAD

**Issue by biocyberman** [bcbio/bcbio-nextgen#248]
I use BAM files as inputs to do realignment and variant calling. The BAM files were generated with reads from the same lane but different barcodes. 

``` bash
@RG ID:GESL_257_9   PL:SOLID    PU:1_6  LB:GESL_257 PI:0    DS:75F  DT:2013-12-02T11:41:58+0000 SM:HBOC00001_L6
@RG ID:GESL_514_10  PL:SOLID    PU:1_6  LB:GESL_514 PI:0    DS:75F  DT:2013-12-02T11:41:58+0000 SM:HBOC00001_L6
@RG ID:GESL_639_11  PL:SOLID    PU:1_6  LB:GESL_639 PI:0    DS:75F  DT:2013-12-02T11:41:58+0000 SM:HBOC00001_L6 
```

This is my YAML file:

``` YAML
upload:
  dir: ../final
details:
- algorithm:
    aligner: false
    bam_clean: picard
    coverage_depth: high
    coverage_interval: exome
    mark_duplicates: picard
    platform: SOLiD
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variant_regions: ../input/bed/abed.bed
    variantcaller: gatk
  analysis: variant2
  metadata:
    batch: HBOC00001
  description: GESL_257_09
  files: 
    - ../input/GESL_257/HBOC00001-Idx_9-9.bam
  genome_build: GRCh37
- algorithm:
    aligner: false
    bam_clean: picard
    coverage_depth: high
    coverage_interval: exome
    mark_duplicates: picard
    platform: SOLiD
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variant_regions: ../input/bed/abed.bed
    variantcaller: gatk
  analysis: variant2
  metadata:
    batch: HBOC00001
  description: GESL_514_10
  files:
    - ../input/GESL_514/HBOC00001-Idx_10-10.bam
  genome_build: GRCh37
- algorithm:
    aligner: false
    bam_clean: picard
    coverage_depth: high
    coverage_interval: exome
    mark_duplicates: picard
    platform: SOLiD
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variant_regions: ../input/bed/abed.bed
    variantcaller: gatk
  analysis: variant2
  metadata:
    batch: HBOC00001
  description: GESL_639_11
  files:
    - ../input/GESL_639/HBOC00001-Idx_11-11.bam
  genome_build: GRCh37
fc_date: '140112'
fc_name: HBOC00001
```

The problem is, in the final VCF file, I only get one sample named `HBOC00001_L6` 
as in the VCF table header like following:
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HBOC00001_L6`

I expect the output to be like:
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  GESL_257_09     GESL_541_10     GESL_639_11`

How do I get this done without modifying BAM headers in the first place? Will the changing of "description:" to "lane:" in the YAM file help?
