### ISSUE TITLE
vcfanno and gemini don't work in RNA-seq analysis?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2511]
Hello, bcbio developers and users!

Thanks for the great pipeline!
I've read in the history that it is now possible to use vcfanno in RNA-seq analysis.

When trying this:
```
details:
- algorithm:
    aligner: star
    tools_off:
    - gatk4
    tools_on:
    - bcbiornaseq
    - gemini
    variantcaller: gatk-haplotype
    vcfanno:
    - /home/naumenko/cre/cre.vcfanno.conf
  analysis: RNA-seq
  description: 181_121141J
  files:
  - /hpf/largeprojects/ccmbio/amahalanabis/181/input/181_121141J_1.fq.gz
  - /hpf/largeprojects/ccmbio/amahalanabis/181/input/181_121141J_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: 181
fc_name: '181'
resources:
  default:
    cores: 2
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 15G
upload:
  dir: ../final
```

vcf file is not annotated and there is no gemini database.

Should I specify parameters differently in RNA-seq analysis, or this functionality is not available in RNA-seq?

Thanks!
Sergey

**Comment by matthdsm** [comment]
Hi Brad,

I'm having the same issue, but with the standard pipeline, annotations seem to be okay, but no gemini db is created.

Cheers
M

**Comment by chapmanb** [comment]
Sergey -- thanks much for the report. bcbio doesn't currently try to create gemini databases for RNA-seq variant call pipelines, so this is not yet supported. However, it should run vcfanno with your custom input configuration (`/home/naumenko/cre/cre.vcfanno.conf`). When you specify your own vcfanno this overrides the defaults which include a gemini and rnaseq editing annotation: https://github.com/bcbio/bcbio-nextgen/blob/8436b2e6cdb143ef98849e33c24dffb9c17e57da/bcbio/variation/vcfanno.py#L89

Does this running of only your input configuration match what you're seeing? More generally, would you prefer different behavior here when you specify your own vcfanno inputs? Also, would it be possible to move the custom annotations you're doing into something bcbio could support? We're going to have problems supporting arbitrary vcfanno inputs and files with CWL as we move towards that and trying to think how to phase this support out.

Matthias, would it be possible to see your configuration so we can figure out what is going on? `tools_on: [gemini]` should build gemini databases and you should be running vcfanno either way, so I'm not sure how to reproduce/debug.

Thanks much.

**Comment by naumenko-sa** [comment]
Hi Brad!

Thanks for the quick response!

I see, bcbio was trying to find this config in 
```.../bcbio/genomes/Hsapiens/GRCh37/config/vcfanno```

My custom config file is not using any annotation sources outside of bcbio - just gnomad_exome, and gnomad_genome provided by bcbio. So I can put my config in the proper folder, and it should work.

I'd propose the flexible approach, if possible: to allow users having their custom vcfanno configs (because it is easier to store them in the repo rather than in bcbio folder), but those config should use only bcbio annotation sources - there is more than enough data for any annotation.

Are vep annotation also available in RNA-seq?

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for following up on this. What do you think about including your custom annotation file as a standard choice distributed with bcbio? Then it'll be installed and managed within the standard vcfanno config directory. It should be able to find your conf file outside of this, but longer term in CWL we won't be able to support these custom inputs so I'd like to build up a set of useful community annotations and have them supported in bcbio.

We also haven't added effects prediction with snpEff into RNA-seq outside of CWL runs, as the idea was to migrate this there. Is effects prediction useful right now in standard pipelines?

Thanks again for all the discussion and feedback.

**Comment by matthdsm** [comment]
Hi Brad,

I'm using the following config:
```
#bcbio-nextgen v1.1.0a
---
#include an experiment name here
fc_name: v1.1.0a_test
upload:
  dir: ../final
globals:
  analysis_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: NA12878K12
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: /ref/NA12878_truth_regions.bed
      tools_on:
        - vep_splicesite_annotations
        - gemini
        - coverage_perbase
    files: [../input/NA12878K12_R1.fastq.gz,../input/NA12878K12_R2.fastq.gz]
```

I suppose the config is allright? All the annotations seem to be in place, but no db's are created.

Thanks for the help, and Sergey, sorry for hijacking your issue ;) 
Cheers
M
