### ISSUE TITLE
gatk4 mutect2 produces unexpected SNV calls

### ISSUE THREAD

**Issue by sxv** [bcbio/bcbio-nextgen#2518]
I have tumor/normal paired-read targeted sequencing data.

Using bcbio gatk 4.0.3.0 and mutect2, I get 3749 calls in the output vcf file.
Using the "ready.bam" produced by bcbio/bwa, I tried running gatk4/mutect2 without bcbio and the vcf produced has only 121 calls, which seems more reasonable.
41 of the calls are found in both results. What could be causing this discrepancy?

bcbio config snippet:
```
- analysis: variant2  
  genome_build: hg19  
  metadata:  
     batch: xx2  
     phenotype: normal  
  description: Normal.AGTTCC  
  files: [R1.fastq.gz, R2.fastq.gz]  
  algorithm:  
    aligner: bwa  
    mark_duplicates: true  
    recalibrate: true  
    platform: illumina  
    tools_off: [gemini]  
    tools_on: gatk4  
    variantcaller: mutect2  
    variant_regions: Baits.bed
```

and the gatk4 command:
```
/gatk-4.0.8.1/gatk --java-options "-Xmx2g" Mutect2 \  
-R hg19.fa \  
-I tumor.bam \  
-I normal.bam \  
-tumor tt \  
-normal nn \  
-L Baits.bed \  
-O ttnn.vcf.gz
```
