### ISSUE TITLE
RNA-seq: Using star option twopassMode produces empty bam file

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2577]
Hello, bcbio developers and users!

Thanks for the very useful bcbio framework!

This story is related to https://github.com/bcbio/bcbio-nextgen/issues/2237 and https://github.com/bcbio/bcbio-nextgen/issues/1629, i.e. the goal is to have twopassMode (first pass discovers splice junctions and inserts them in the reference, second pass does the alignment) when aligning RNA-seq reads with STAR in bcbio.

As now it is possible to specify STAR options in the config file, I decided to switch to that instead of hardcoding the option in star.py:
```
details:
- algorithm:
    aligner: star
    variantcaller: gatk-haplotype
    tools_off:
    - gatk4
    tools_on:
    - bcbiornaseq
    expression_caller: [cufflinks, express, stringtie, sailfish, dexseq, kallisto, salmon]
  analysis: RNA-seq
  description: project_sample
  files:
  - /hpf/largeprojects/ccmbio/naumenko/RIVAL/bcbio_run/input/SRR307897_1.fq.gz
  - /hpf/largeprojects/ccmbio/naumenko/RIVAL/bcbio_run/input/SRR307897_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: project
resources:
  default:
    cores: 2
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 15G
  star:
    options: ["--twopassMode Basic"]
upload:
  dir: ../final
```
Unfortunately, this config produces an empty bam file during the alignment, and the pipeline fails after the alignment step on featureCounts which is not expecting an empty bam.
If you remove STAR options, then everything works fine. STAR is working, STAR genome index is working (bam is produced in bcbio without twopassMode option, bam is produced outside of bcbio using bcbio's STAR and index).

Could somebody please help me with this? I ran out of ideas. I tried to upgrade STAR to the latest version - same behavior.

Thanks!
Sergey
