### ISSUE TITLE
issues generating ped file for gemini

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2596]
Hi Brad,

We've just updated to the latest stable bcbio version and are having the following issue:
When trying to do a trio analysis starting from gvcfs, the autogenerated ped file only inludes one of the individuals, causing vcf2db to fail.

Joint calling using GATK4 seems to work fine, the resulting vcf contains all 3 samples, the ped file however, does not.

We're using the following config:
```
fc_name: Research_trio_001
fc_date: '20181213'
upload:   
  dir: ../final
globals:
  analysis_regions: /data/gent/vo/000/gvo00082/bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /data/gent/vo/000/gvo00082/bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: $VSC_SCRATCH_VO_USER/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: D1603027
    vrn_file: ../input/D1603027-gatk-haplotype.vcf.gz
    metadata:
      batch: Research_trio_001
    algorithm:
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - gemini
  - analysis: variant2
    genome_build: hg38
    description: D1516264
    vrn_file: ../input/D1516264-gatk-haplotype.vcf.gz
    metadata:
      batch: Research_trio_001
    algorithm:
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - gemini
  - analysis: variant2
    genome_build: hg38
    description: D1603034
    vrn_file: ../input/D1603034-gatk-haplotype.vcf.gz
    metadata:
      batch: Research_trio_001
    algorithm:
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - gemini
```

I don't seem to be able to find anything wrong in the config, so I suppose a bug snuck in with the reconfiguring of the gemini approach.
Any ideas?

Thanks
M
