### ISSUE TITLE
No gemini.db created with tools_on: gemini in bcbio1.1.2 and grch37?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2624]
Hello, bcbio developers and users!

It seems that gemini database is not created in the latest stable release 1.1.2 with tools_on: gemini for grch37?

The config file:
```
details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: true
    recalibrate: true
    save_diskspace: true
    tools_off:
    - gatk4
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - samtools
    - platypus
    - freebayes
    vcfanno:
    - /home/naumenko/cre/cre.vcfanno.conf
  analysis: variant2
  description: WES_NA12878_202214
  files:
  - /hpf/largeprojects/ccmbio/naumenko/validation/WES/input/WES_NA12878_202214_1.fq.gz
  - /hpf/largeprojects/ccmbio/naumenko/validation/WES/input/WES_NA12878_202214_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: WES
fc_name: WES
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
```
There is no error message, vcfs are annotated with vep/vcfanno, no vcf2db call in the log, no gemini.db in the final folders and in work/gemini.

Could you please help to debug this issue?

Thanks!
Sergey
