### ISSUE TITLE
Small RNA report issue. (only see R codes, not generating full reports)

### ISSUE THREAD

**Issue by jxshi** [bcbio/bcbio-nextgen#2647]
Hi @lpantano ,

I am using bcbio-nextgen small RNA pipeline to analyze miRNA sequencing data. The whole process executed correctly after upgrading to latest development version of bcbio-nextgen. There is a Rmarkdown file named ```srna_report.rmd``` in the ```final``` directory. Here is the full address to the rmarkdown file: ```/mnt/data/proj/guo/miRNA/brainTrauma/final/2019-01-25_brainTrauma/report```. I tried to generate report by using the rmarkdown file but I did not get the full report. I can see some R codes, but no results.

Can you look into this please? Thank you in advance!

Best regards,

Jianxiang

**Comment by lpantano** [comment]
Hi,

bcbio will only generate the source code, so it helps the user to use R to
run the Rmd file.

You say you tried to run the code in R but nothing happened at all?

Anyways, that is deprecated, I will remove it from bcbio. I started a R
package to analyze data from bcbio:
https://lpantano.github.io/bcbioSmallRna/

You can create a template with this package for the QC at least, similar to
this: https://lpantano.github.io/bcbioSmallRna/articles/qc-example.html

You need to install the package and the go to New File in Rstudio, select
Rmd, select Templates and you will see the one for small RNA.

Sorry about the confusion.

Cheers

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by jxshi** [comment]
Hi, @lpantano

**Comment by jxshi** [comment]
Hi @lpantano ,


Thank you for your reply. bcbio generated rmarkdown file actually generated some figures for miRNA QC.

I have installed bcbioSmallRna R package, but I didn't get how to use the QC rmarkdown template. Can you show me how to get the ```sbcb``` object please? Thank you very much!

Best regards,

Jianxiang

**Comment by lpantano** [comment]
Hey,

thanks for spotting that!

Can you send the figure that shows that about the non-annotated miRNA?

Cheers

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io

**Comment by jxshi** [comment]
Hi,

Here is [the link to the figure](https://imgur.com/a/bQhbzIf) that shows non-annotated small RNAs.

Thank you！

Best,

Jianxiang

**Comment by lpantano** [comment]
I see, can you remember me the species you were using?

**Comment by jxshi** [comment]
Homo sapiens.

**Comment by lpantano** [comment]
What version did you use?

Can you copy here what is contained in the genome folder of that version.

For instance, I have this:

genomes/Hsapiens/hg19/srnaseq/

and in genomes/Hsapiens/hg19/seq/hg19-resources.yaml:

srnaseq:
  srna_transcripts: ../srnaseq/srna-transcripts.gtf
  mirbase_hairpin: ../srnaseq/hairpin.fa
  mirbase_mature: ../srnaseq/mature.fa
  mirdeep2_fasta: ../srnaseq/Rfam_for_miRDeep.fa
  trna_fasta: ../srnaseq/trna_mature_pre.fa
  mint_lookup: ../srnaseq/LookupTable.tRFs.MINTmap_v1.txt
  mint_space: ../srnaseq/tRNAspace.Spliced.Sequences.MINTmap_v1.fa
  mint_other: ../srnaseq/OtherAnnotations.MINTmap_v1.txt

Thanks

**Comment by jxshi** [comment]
Sorry for the late reply due to Chinese New Year vacation. Happy Chinese New Year!

I have the following folder in genome folder:
```genomes/Hsapiens/GRCh37/srnaseq```
And in ```genomes/Hsapiens/GRCh37/seq/GRCh37-resources.yaml```:

```
srnaseq:
  srna_transcripts: ../srnaseq/srna-transcripts.gtf
  mirbase_hairpin: ../srnaseq/hairpin.fa
  mirbase_mature: ../srnaseq/mature.fa
  mirdeep2_fasta: ../srnaseq/Rfam_for_miRDeep.fa
  trna_fasta: ../srnaseq/trna_mature_pre.fa
  mint_lookup: ../srnaseq/LookupTable.tRFs.MINTmap_v1.txt
  mint_space: ../srnaseq/tRNAspace.Spliced.Sequences.MINTmap_v1.fa
  mint_other: ../srnaseq/OtherAnnotations.MINTmap_v1.txt
```

Thank you!

Jianxiang
