### ISSUE TITLE
Somatic analysis with background: variant: vcf

### ISSUE THREAD

**Issue by gabeng** [bcbio/bcbio-nextgen#2654]
I intended to run validation on a high-depth targeted panel consisting of an NA12878-NA24385 mixture using the following configuration:
```
---
details:
  - analysis: variant2
    genome_build: GRCh37
    algorithm:
      variantcaller: [mutect2, vardict]
      min_allele_fraction: 1
      tools_off: [gemini, coverage_qc, fastqc, contamination]
      effects: false
      background:
        variant: /usr/local/share/bcbio-nextgen/genomes/Hsapiens/GRCh37/validation/giab-NA24385/truth_small_variants.vcf.gz
    metadata:
      phenotype: tumor
```
Validation is performed against the `giab-NA12878-NA24385-somatic` ground truth.

It seems that the background is only subtracted in Mutect2 using `--panel-of-normals` , but not in Vardict. What is the recommended way to subtract a background from the Vardict results?
