### ISSUE TITLE
ValueError: MuTect, MuTect2 and Strelka2 somatic calling requires normal sample or panel

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2662]
Hi, I am using Mutect2 to call variants for a tumor-only sample. My yaml file is as below:
```
upload:
  dir: ../final_mutect2
details:
  - files: [../input/L103_R1.fastq.gz, ../input/L103_R2.fastq.gz]
    description: liuqingfeng
    metadata:
      batch: L103
      phenotype: tumor
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: gatk
      realign: false
      effects: snpeff
      variantcaller: [mutect2]
      variant_regions: /bio/zhengu/Corectical_22.bed
      remove_lcr: true
```

Then, I got the followng error:
`ValueError: MuTect, MuTect2 and Strelka2 somatic calling requires normal sample or panel: 
`
