### ISSUE TITLE
Error with hg19 and GGD recipe: hg19 srnaseq 20180710

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2664]
Hi, I'm getting an error while installing bcbio_vm data for genome hg19:

```
localhost] local: export PATH=/usr/local/bin:$PATH && export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg format -o rtg/hg19.sdf /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg19/seq/hg19.fa
Running GGD recipe: hg19 GA4GH_problem_regions 20181016
Running GGD recipe: hg19 capture_regions 20161202
Running GGD recipe: hg19 MIG 20150730
Running GGD recipe: hg19 prioritize 20181227
Running GGD recipe: hg19 dbsnp 151-20180423
Running GGD recipe: hg19 hapmap 3.3
Running GGD recipe: hg19 1000g_omni_snps 2.5
Running GGD recipe: hg19 ACMG56_genes 20160629
Running GGD recipe: hg19 1000g_snps 2.8
Running GGD recipe: hg19 mills_indels 2.8
Running GGD recipe: hg19 clinvar 20170905
Running GGD recipe: hg19 cosmic 68-20180114
Running GGD recipe: hg19 ancestral 20141010
Running GGD recipe: hg19 qsignature 20140703
Running GGD recipe: hg19 genesplicer 2004.04.03
Running GGD recipe: hg19 effects_transcript 2017-03-16
Running GGD recipe: hg19 varpon 20181105
Running GGD recipe: hg19 vcfanno 20190119
Running GGD recipe: hg19 viral 2017.02.04
Running GGD recipe: hg19 transcripts 2014-07-17
Running GGD recipe: hg19 RADAR v2-20180202
Running GGD recipe: hg19 rmsk 20180319
Running GGD recipe: hg19 srnaseq 20180710
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 105, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 366, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
    configure_instance(options, actions)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 269, in configure_instance
    setup_biodata(options)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 251, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 340, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 469, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 836, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file, gid)
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 31, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "/home/amizeranschi/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 63, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg19/txtmp/ggd-run.sh']' returned non-zero exit status 4
```

I'm guessing the file `/usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg19/txtmp/ggd-run.sh` is inside the bcbio-vc:latest container, as it doesn't exist on the host Linux system. What could be causing this?

This is the YAML template that I'm using:

```
# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - analysis: variant2
    genome_build: hg19
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      effects: false
      tools_on: gvcf
      tools_off: gemini
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy: 2
      variant_regions: ../config/variant_regions.bed
```
