### ISSUE TITLE
Out-of-order VCF files produced during variant calling

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#269]
When running an analysis with ensemble (UnifiedGenotyper, HaplotypeCalller and freebayes), I ended up with this error during the VariantAnnotator run (edited for formatting):

```
##### ERROR We saw a record with a start of chr13:32973279 after a record with a start
of chr13:32973304, for input source:
/mnt/data/projects/lines/work/freebayes/chr13/
1_2014-01-23_lines-sort-chr13_32972172_32973806-prep-variants-raw.vcf
```

I'm not sure where to pinpoint the issue exactly. I can provide the configuration if needed.

Relevants bit from algorithm section (equal for all the 3 samples I'm running):

``` yaml
- algorithm:
    aligner: bwa
    coverage_depth: high
    coverage_interval: regional
    mark_duplicates: false
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: [freebayes, gatk, gatk-haplotype]
    variant_regions: /mnt/data/projects/regions/regions_new.bed
    ensemble:
        format-filters: [DP < 10]
        classifier-params:
            type: svm
        classifiers:
            balance: [AD, FS, Entropy]
            calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        trusted-pct: 0.5

```
