### ISSUE TITLE
Minimal config for RNA-seq variant calling

### ISSUE THREAD

**Issue by komalsrathi** [bcbio/bcbio-nextgen#2830]
Hi

Is it possible to just do `variant calling` on input RNA-sequencing fastq or bam files?

Here is my config.yaml file, I am trying to hide a bunch of tools but looks like they are still running:

```
details:
- algorithm:
    aligner: false
    bam_sort: false
    variantcaller: gatk-haplotype
    tools_off: [gatk4, gemini, vcfanno, gatk-haplotype-joint, salmon, htseq-count, fastqc, multi-qc]
  analysis: RNA-seq
  description: 'Sample 1: 27571P'
  files:
  - Sample_1__27571P-dedup.splitN_chrX.bam
  genome_build: GRCh37
  metadata:
    batch: 27571P
fc_name: 27571P-CDLS
upload:
  dir: 27571P_gatk3_test

```

The reason I want to do that, is because I want to test the pipeline with GATK3.8 that I have recently installed. It would make it so much easier and faster to test it if all the qc/counting steps did not run.

Thanks
Komal
