### ISSUE TITLE
question: gatk-cnv

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2849]
Hi,

I've been taking some first steps in calling CNV's with GATK and I have several questions.

First, where do the results go? I can't find any mention of CNV data in the `final` directory.
It'd be nice to get the log2 ratio's from gatk.

Second, I'm seeing the following tree in the `structural` subdir of the `work` directory
```
├── bins
│   ├── D1310723-joint
│   ├── D1504778-joint
│   ├── D1518155-joint
│   │   ├── D1310723-target-gcannotated.tsv
│   │   ├── D1310723-target.interval_list
│   │   ├── D1504778-target-gcannotated.tsv
│   │   ├── D1504778-target.interval_list
│   │   ├── D1518155-target-gcannotated.tsv
│   │   ├── D1518155-target.interval_list
│   │   ├── D1701936-target-gcannotated.tsv
│   │   ├── D1701936-target.interval_list
│   │   ├── D1800492-target-gcannotated.tsv
│   │   ├── D1800492-target.interval_list
│   │   ├── D1804155-target-gcannotated.tsv
│   │   ├── D1804155-target.interval_list
│   │   ├── FD1800075-target-gcannotated.tsv
│   │   └── FD1800075-target.interval_list
│   ├── D1701936-joint
│   ├── D1800492-joint
│   ├── D1804155-joint
│   └── FD1800075-joint
├── D1310723
│   ├── bins
│   │   ├── D1310723-crdenoised.tsv
│   │   ├── D1310723-crstandardized.tsv
│   │   ├── D1310723-target.bed
│   │   ├── D1310723-target.bed.gz
│   │   ├── D1310723-target.bed.gz.tbi
│   │   └── D1310723-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
├── D1504778
│   ├── bins
│   │   ├── D1504778-crdenoised.tsv
│   │   ├── D1504778-crstandardized.tsv
│   │   ├── D1504778-target.bed
│   │   ├── D1504778-target.bed.gz
│   │   ├── D1504778-target.bed.gz.tbi
│   │   └── D1504778-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
├── D1518155
│   ├── bins
│   │   ├── D1518155-crdenoised.tsv
│   │   ├── D1518155-crstandardized.tsv
│   │   ├── D1518155-target.bed
│   │   ├── D1518155-target.bed.gz
│   │   ├── D1518155-target.bed.gz.tbi
│   │   └── D1518155-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
├── D1701936
│   ├── bins
│   │   ├── D1701936-crdenoised.tsv
│   │   ├── D1701936-crstandardized.tsv
│   │   ├── D1701936-target.bed
│   │   ├── D1701936-target.bed.gz
│   │   ├── D1701936-target.bed.gz.tbi
│   │   └── D1701936-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
├── D1800492
│   ├── bins
│   │   ├── D1800492-crdenoised.tsv
│   │   ├── D1800492-crstandardized.tsv
│   │   ├── D1800492-target.bed
│   │   ├── D1800492-target.bed.gz
│   │   ├── D1800492-target.bed.gz.tbi
│   │   └── D1800492-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
├── D1804155
│   ├── bins
│   │   ├── D1804155-crdenoised.tsv
│   │   ├── D1804155-crstandardized.tsv
│   │   ├── D1804155-target.bed
│   │   ├── D1804155-target.bed.gz
│   │   ├── D1804155-target.bed.gz.tbi
│   │   └── D1804155-target-coverage.hdf5
│   ├── cnvkit
│   └── validate
└── FD1800075
    ├── bins
    │   ├── FD1800075-crdenoised.tsv
    │   ├── FD1800075-crstandardized.tsv
    │   ├── FD1800075-target.bed
    │   ├── FD1800075-target.bed.gz
    │   ├── FD1800075-target.bed.gz.tbi
    │   └── FD1800075-target-coverage.hdf5
    ├── cnvkit
    └── validate
```

I get the per-sample directories, but why are all `target` files thrown together under one sample in the `bin` top dir?

If it's any help, I'm using the following config template:
```
#bcbio-nextgen v1.1.6
---
#include an experiment name here
fc_name: exome_cnv
upload:
  dir: ../final
globals:
  analysis_regions: /bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /bcbio/genomes/Hsapiens/hg38/regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      svcaller: gatk-cnv
      svprioritize: coverage_regions
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,eog,dbscsnv,dbnsfp]
      archive: cram
      tools_on:
        - gemini
        - vep_splicesite_annotations
        - coverage_perbase
    # add the path to your files here
    files:
```

Thanks
M
