### ISSUE TITLE
Failure with small RNA-seq pipeline

### ISSUE THREAD

**Issue by kthlnktng** [bcbio/bcbio-nextgen#2850]
Hello,

I'm a new user of bcbio and am running into errors with the small RNA-seq pipeline. I would appreciate some assistance in debugging.

I'm using the O2 cluster and the `bcbio/latest` module.

My config file is:

<details>
<summary>Click to view.</summary>

```yaml
[kmk34@login06 config 2019-06-06 20:42:00]$ cat test_project3.yaml
details:
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-16.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-16.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-17.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-17.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-18.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-18.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-19.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-19.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-20.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-20.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-21.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-21.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
- algorithm:
    #adapters:
    #- TGGAATTCTCGGGTGC
    aligner: star
    expression_caller:
    - trna
    - seqcluster
    - mirge
    trim_reads: false
    species: hsa
  analysis: smallRNA-seq
  description: SMGX86-22.fastq.gz.trimmed
  files:
  - /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/SMGX86-22.fastq.gz.trimmed.fastq.gz
  genome_build: hg38
resources:
  star:
    cores: 6
    memory: 60G
  mirge:
    options: ["-lib /n/groups/rccg/kmk34/consults/zw59/2019_05_smallRNA/data/"]
fc_name: test_project3
upload:
  dir: ../final
```

</details>

The last error reported in the log file is:

```bash
971 Traceback (most recent call last):
972   File "/n/app/bcbio/dev/anaconda/bin/seqcluster", line 11, in <module>
973     load_entry_point('seqcluster==1.2.4', 'console_scripts', 'seqcluster')()
974   File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/seqcluster/command_line.py    ", line 31, in main
975     report(kwargs["args"])
976   File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/seqcluster/create_report.p    y", line 30, in report
977     data = make_profile(data, os.path.join(args.out, "profiles"), args)
978   File "/n/app/bcbio/dev/anaconda/lib/python3.6/site-packages/seqcluster/libs/report.py"    , line 61, in make_profile
979     data[0][c]['precursor'].update(run_rnafold(data[0][c]['precursor']['seq']))
980 TypeError: 'NoneType' object is not iterable
981 ^M                                                                               ^M^M100    % (704 of 704) |######################| Elapsed Time: 0:00:10 Time:  0:00:10
982 ' returned non-zero exit status 1.
```

I'm attaching the full log, as there are some upstream errors in the seqcluster step:
[bcbio.42464738.out.zip](https://github.com/bcbio/bcbio-nextgen/files/3264051/bcbio.42464738.out.zip)

Please let me know if there is any other information I can provide!

Best,
Kathleen
