### ISSUE TITLE
SGE mem_free requirement is larger than expected for bcbio-e job array

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2860]
Hello,

I'm running VC with bcbio using IPython on an SGE cluster and, at the variant calling stage, the job array that is being created for the bcbio engines is getting a larger `mem_free` requirement than I would expect, given the memory requirement from the YAML template. The worker nodes have around 124 GB of memory, but some of that can remain used by previous misbehaved processes with memory leaks. Although I'm requesting a full node (32 cores) and 2 GB of memory per node, the hard resource requirement causes some of the jobs in the array to never start:

```
$ qstat -u a.mizeranschi
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
1095729 0.50689 run-this-b a.mizeransch r     06/20/2019 14:49:58 campus-haswell.q@haswell-wn42.     4        
1095737 0.50500 bcbio-c    a.mizeransch r     06/21/2019 19:38:34 campus-haswell.q@haswell-wn36.     1 1
1095738 0.52450 bcbio-e    a.mizeransch r     06/21/2019 19:38:49 campus-haswell.q@haswell-wn37.    32 1
1095738 0.52450 bcbio-e    a.mizeransch qw    06/21/2019 19:38:34                                   32 2-5:1
```

```
$ qstat -j 1095738
[...]
hard resource_list:         mem_free=114688M
```

This is the YAML template:

```
# Template for whole genome Illumina variant calling with GATK pipeline
---
details:
  - analysis: variant2
    genome_build: bosTau6
    resources:
      default:
        memory: 2G
        cores: 32
        jvm_opts: ["-Xms800m", "-Xmx2000m"]
      gatk-haplotype:
        options: ["--verbosity ERROR"]
      gatk:
        options: ["--verbosity ERROR"]
      picard:
        options: ["VERBOSITY=ERROR"]
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: false
      realign: false
      effects: false
      tools_off: [gemini, contamination, peddy]
      nomap_split_targets: 1000
      nomap_split_size: 50
      variantcaller: gatk-haplotype
      ploidy: 2
      variant_regions: ../config/variant_regions.bed
```

Why is the `bcbio-e` job array being created with a `mem_free` requirement of 112 GB?
