### ISSUE TITLE
HaplotypeCaller --emit-ref-confidence  has a bad value

### ISSUE THREAD

**Issue by zzupmc** [bcbio/bcbio-nextgen#2892]
Hi,

I use germline variant calling pipeline with the gvcf output on, and the template yaml is as follows. 
gatk-haplotype produces an error:
`
A USER ERROR has occurred: Argument --emit-ref-confidence has a bad value: Can only be used in single sample mode currently. Use the --sample-name argument to run on a single sample out of a multi-sample BAM file`

the last command in the log file is 
`[2019-07-27T08:33Z] unset JAVA_HOME && export PATH=/public/home/pmi/share/anaconda/bin:"$PATH" && gatk --java-options '-Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/bcbiotx/tmp6lr74da_' HaplotypeCaller -R /public/home/pmi/share/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --annotation MappingQualityRankSumTest --annotation MappingQualityZero --annotation QualByDepth --annotation ReadPosRankSumTest --annotation RMSMappingQuality --annotation BaseQualityRankSumTest --annotation FisherStrand --annotation MappingQuality --annotation DepthPerAlleleBySample --annotation Coverage -I /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/align/100001-01/100001-01-sort-recal.bam -I /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/align/100001-02/100001-02-sort-recal.bam -I /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/align/100001-03/100001-03-sort-recal.bam -I /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/align/100001-04/100001-04-sort-recal.bam -I /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/align/100001-05/100001-05-sort-recal.bam -L /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/gatk-haplotype/GL000192.1/100001-GL000192.1_0_546231-regions.bed --interval-set-rule INTERSECTION --annotation ClippingRankSumTest --annotation DepthPerSampleHC --native-pair-hmm-threads 1 --emit-ref-confidence GVCF -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 60 -GQB 80 -ploidy 2 --output /public/home/pmi/Projects/1shenbing/bcbio/family-100001/work/bcbiotx/tmp6lr74da_/100001-GL000192.1_0_546231.vcf.gz`

this command run on five bam files. I modified the command line to analyze only one sample, it works. The same problem is also posted on biostars, [https://www.biostars.org/p/321213/](url), but has no solutions. Any suggestions ?

my gatk version:
gatk4-4.1.2.0-1
 
my yaml template: 

```
---
details:
  - analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      platform: Illumina
      save_diskspace: true
      mark_duplicates: true
      realign: false
      recalibrate: gatk
      variantcaller: gatk-haplotype
      vcfanno: [dbnsfp]
      tools_off: [upload_alignment]
      tools_on: [qualimap_full,gvcf]
```

my yaml file 

```
details:
- algorithm:
    aligner: bwa
    coverage: /public/home/pmi/Projects/bedfiles/Exome-Agilent_CREV2.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: gatk
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    - gvcf
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 100001-01
  files:
  - /home/pmi/Projects/1shenbing/merged/100001-01_R1.fastq.gz
  - /home/pmi/Projects/1shenbing/merged/100001-01_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 100001
    maternal_id: 100001-03
    paternal_id: 100001-02
    phenotype: 2
    sex: male
- algorithm:
    aligner: bwa
    coverage: /public/home/pmi/Projects/bedfiles/Exome-Agilent_CREV2.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: gatk
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    - gvcf
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 100001-02
  files:
  - /home/pmi/Projects/1shenbing/merged/100001-02_R1.fastq.gz
  - /home/pmi/Projects/1shenbing/merged/100001-02_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 100001
    maternal_id: 0
    paternal_id: 0
    phenotype: 1
    sex: male
- algorithm:
    aligner: bwa
    coverage: /public/home/pmi/Projects/bedfiles/Exome-Agilent_CREV2.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: gatk
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    - gvcf
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 100001-03
  files:
  - /home/pmi/Projects/1shenbing/merged/100001-03_R1.fastq.gz
  - /home/pmi/Projects/1shenbing/merged/100001-03_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 100001
    maternal_id: 0
    paternal_id: 0
    phenotype: 1
    sex: female
- algorithm:
    aligner: bwa
    coverage: /public/home/pmi/Projects/bedfiles/Exome-Agilent_CREV2.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: gatk
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    - gvcf
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 100001-04
  files:
  - /home/pmi/Projects/1shenbing/merged/100001-04_R1.fastq.gz
  - /home/pmi/Projects/1shenbing/merged/100001-04_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 100001
    maternal_id: 100001-03
    paternal_id: 100001-02
    phenotype: 1
    sex: male
- algorithm:
    aligner: bwa
    coverage: /public/home/pmi/Projects/bedfiles/Exome-Agilent_CREV2.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: gatk
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    - gvcf
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 100001-05
  files:
  - /home/pmi/Projects/1shenbing/merged/100001-05_R1.fastq.gz
  - /home/pmi/Projects/1shenbing/merged/100001-05_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 100001
    maternal_id: 100001-03
    paternal_id: 100001-02
    phenotype: 1
    sex: female
fc_name: family-100001
upload:
  dir: ../final
```
