### ISSUE TITLE
Debugging a CWL job on GCP

### ISSUE THREAD

**Issue by conkiztador** [bcbio/bcbio-nextgen#2904]
Hi again,

I'm seeing some odd behaviour with running a CWL pipeline on GCP and wondering if anyone has suggestions for debugging this.

Basically during the get_parallel_regions_jointvc step in the workflow, the job seems to "hang" forever - in the background a single GCP instance is created and gets deleted after almost exactly 10 minutes. It goes on forever like this creating and deleting instances. There's nothing logged by bcbio when this happens. Oddly, I see the GCP pipelines API itself issuing a delete request to the compute API, rather than the instance shutting itself down after completing the work (I'm not sure if this is just normal behaviour or not).

The pipeline disables SSH so there doesn't appear to be a way to get a log from the workload itself. There are no logs in the working dir in the bucket for this step either.

The template looks like this:
```
# Variant calling with GATK pipeline - WES
---
details:
  - analysis: variant2
    genome_build: GRCh37
    metadata:
      batch: KC_ANZRAG_WES_GATK_batch
    algorithm:
      aligner: bwa
      recalibrate: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      tools_off: fastqc
      # for targetted projects, set the region
      variant_regions: S03723314_Padded_noCHR.bed
```

This particular run has only 20 samples as I'm gradually ramping up to control our GCP spend. The same job with only one sample finished without error.

Cheers,
Kieran
