### ISSUE TITLE
bam to fastq (quality values differs from original fastq)

### ISSUE THREAD

**Issue by xexpanderx** [bcbio/bcbio-nextgen#2910]
Hi!

I try to convert a bam (created by bcbio version 1.0.7a) back to fastq using bedtools bamtofastq.

The number of rows in the generated fastq is exactly the same as the original fastq (made by bcl2fastq). However, the quality values differs. Any idea why and how I can convert bam to match the quality values as well?

Original fastq files are generated by:
```
bcl2fastq -i Data/Intensities/BaseCalls -o ../Outputs/Raw_data --sample-sheet *.csv --use-bases-mask 'Y*n,I*,I*,Y*n' --barcode-mismatches 1 --no-lane-splitting -r 16 -d 16 -p 16
```

The generated fastq files from bam:
```
$ samtools sort -n aln.bam aln.qsort
$ bedtools bamtofastq -i aln.qsort.bam \
                      -fq aln.end1.fq \
                      -fq2 aln.end2.fq
```

**Comment by roryk** [comment]
Hi @xexpanderx,

I think you might be wanting the `bedtools` mailing list: 
https://groups.google.com/forum/#!forum/bedtools-discuss

It is hard to answer the question without knowing how the BAM file was created. Often times there are steps where the quality scores get reformatted or binned depending on what is happening.

**Comment by xexpanderx** [comment]
Well, the bam files were created through bcbio...

I am gonna ask at that mail-list too.

**Comment by roryk** [comment]
Oh, I see it is from bcbio. If you can post your input YAML file, we can figure out why the quality scores might be different. I'm guessing the relative quality scores are the same, but there is some offset that was added to them.

**Comment by roryk** [comment]
If you can post ten reads that are before and after to compare that would be helpful.

**Comment by xexpanderx** [comment]
sample config file:

```
details:
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-02926
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-02926_S1_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-02926_S1_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04064
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04064_S2_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04064_S2_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04065
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04065_S3_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04065_S3_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04110
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04110_S4_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04110_S4_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04131
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04131_S5_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04131_S5_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04202
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04202_S7_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04202_S7_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04204
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04204_S6_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04204_S6_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04232
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04232_S9_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04232_S9_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04245
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04245_S8_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04245_S8_R2_001.fastq.gz
  genome_build: hg19_consensus
- algorithm:
    aligner: bwa
    coverage_interval: exome
    mark_duplicates: true
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk-haplotype
    effects: false
  analysis: variant2
  description: D19-04296
  files:
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04296_S10_R1_001.fastq.gz
  - /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/Raw_data/D19-04296_S10_R2_001.fastq.gz
  genome_build: hg19_consensus
fc_date: '2019-08-09'
fc_name: CCP17
upload:
  dir: /projects/wp3/nobackup/CCP17/INBOX/SS130_190809/Outputs/final/
```

D19-02926_read1 (original):
```
@NB501298:158:HN5TJAFXY:1:11101:24876:1050 1:N:0:TAAGGCGA+NCGATCTA
NAGGATCCCCGAGGTGTCCTCGGCTGAGGTGACCCCCCCTAGCGTGCTGCAGTTGGCACCAGAGGACTGCAGCTTGTACTGGACGTTGATGCCCCTGAACGCCTGGCAGTTTTCCACACAGACTTTCCCGATCTAGGGGGGCACAGGGGA
+
#AAAAE/EE//EA/EEA</E</AAEAEAEA/E///EAA//A/E/</EE/EE/A//EE<EEEEEEE//E///6A/AE/AEEE/E</E//E/EEE/6E/</EEE/EE/EEAEEE//E///E/EEEEEEE///EA//EEEEA/E</<A/E<AA
```

D19-02926_read2 (original):
```
@NB501298:158:HN5TJAFXY:1:11101:24876:1050 2:N:0:TAAGGCGA+NCGATCTA
GCTGCCTGGCTAAGGTGTTCCCCTGTGCCCCCCTAGATCGGGAAAGTCTGTGTGGAAAACTGCCAGGCGTTCAGTGGCATCAACGTCCAGTACAAGCTGCATTCCTCTGGTGCCAACTGCAGCACGCTAGGGGTGGTCCCCTCAGCCGAG
+
6/AAAEA/EEEE6AEEAEE/EE/E/EE/EAEE/E//EE/EEEEE/E6EEEEEA<EE6E6A/AEEEE///EEEE<EAAE/EEEE/<A/EEEEEEA/E/EEEEE<6/EEA/<EE//E/<EEE//</E<<</EEEAE/A<6/A/E6/<<A6AA
```

D19-02926_read1 (bedtools bam2fastq):
```
@NB501298:158:HN5TJAFXY:1:11101:24876:1050/1
NAGGATCCCCGAGGTGTCCTCGGCTGAGGTGACCCCCCCTAGCGTGCTGCAGTTGGCACCAGAGGACTGCAGCTTGTACTGGACGTTGATGCCCCTGAACGCCTGGCAGTTTTCCACACAGACTTTCCCGATCTAGGGGGGCACAGGGGA
+
#@CCDE3EE1-EE3DIA@1F@-BBFEEEEA3E.//EAA.4?1F*>2FF2FF1A02EF=FEFHEHE/-F2,.8C3BI/@FFI/E=)D/1E.IFE-;F1=.F@F-FI/FFFDEE//E-,-F-HEFFEEF--)EC/3CHEED/E?->B0@??>
```
D19-02926_read2 (bedtools bam2fastq):
```
@NB501298:158:HN5TJAFXY:1:11101:24876:1050/2
GCTGCCTGGCTAAGGTGTTCCCCTGTGCCCCCCTAGATCGGGAAAGTCTGTGTGGAAAACTGCCAGGCGTTCAGTGGCATCAACGTCCAGTACAAGCTGCATTCCTCTGGTGCCAACTGCAGCACGCTAGGGGTGGTCCCCTCAGCCGAG
+
6-BFDDB2EFFB0BDDCCD/DE-E1CH+D>DD-E+0DD/?DDDD.G3EEHCH>ADD3D3>2BEDEG.*(CDEE?CB?E,DEED+9?.DEGCBE>-G*DGDDD;7,EEB0=CH*,E-;EHE,/<,E:<@*GDDCC0C>:,B,E:-A<?5=A
```
