### ISSUE TITLE
exclude_regions should also apply to copy number calling

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2918]
As the subject says, I want to get rid of alt contigs in hg38: this happens (or should happen) when setting `altcontigs` in `exclude_regions`. 

In my configuration file I have, for example

```yaml
- algorithm:
    aligner: bwa
    exclude_regions:
    - altcontigs
    - highdepth
    - polyx
```

This seems to work for variant callers, but it does *not* work for structural variants, where alt contigs are still included (and muddle up the plots). 

As an example, these are some contigs found in a GATK4 CNV processed file:

- chr1_KI270706v1_random
- chr1_KI270711v1_random 
- chr4_GL000008v2_random
