### ISSUE TITLE
Error: dkfzbiasfilter_summarize.py - Invalid header

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2931]
Hi,

I temporarily solved issue [#2838](https://github.com/bcbio/bcbio-nextgen/issues/2838) by adding `BCBIO_DIR` to my`PATH`. However, while this leads to successful execution of `dkfzbiasfilter`, the process still fails while summarizing the variants with `dkfzbiasfilter_summarize.py`:

```
Traceback (most recent call last):
  File "/mnt/tools/bin/dkfzbiasfilter_summarize.py", line 156, in <module>
    main(args[0], options)
  File "/mnt/tools/bin/dkfzbiasfilter_summarize.py", line 42, in main
    if len(set(rec.filter) & damage_filters) == len(rec.filter) or rec.info.get("DKFZBias"):
  File "pysam/libcbcf.pyx", line 2659, in pysam.libcbcf.VariantRecordInfo.get
ValueError: Invalid header
```

How could we fix this problem?
Thanks a lot once again for your help,

Federico

**Comment by roryk** [comment]
Thanks-- could you pass on the variant file that is failing? You should be able to see which file it is in the `log/bcbio-nextgen-commands.log` file.

**Comment by FedericoComoglio** [comment]
Hi @roryk,

sure. This is the call to `dkfzbiasfilter_summarize.py`

```
<BCBIO>/dkfzbiasfilter_summarize.py --sample=5_T_Post --outfile=<PROJECT_DIR>/<SAMPLE>/work/tmp/tmpjspn971l/<SAMPLE>-damage.yaml <PROJECT_DIR>/<SAMPLE>/work/ensemble/<SAMPLE>/<SAMPLE>-ensemble-effects.vcf.gz
```

**Comment by roryk** [comment]
Thanks, sorry I mean can you pass on the actual variant file? Or at least a piece of it that has the error?

**Comment by FedericoComoglio** [comment]
Thanks @roryk, in this case it's sensitive data and I can't share the VCF, unfortunately.

Based on previous similar issues [#1965](https://github.com/bcbio/bcbio-nextgen/issues/1965) and [#1963](https://github.com/bcbio/bcbio-nextgen/issues/1963) it seems a likely explaination would be an invalid INFO field value. I can say this occurs systematically for all samples I processed in parallel.

**Comment by roryk** [comment]
Thanks-- could you share the YAML configuration you are using so I can try to see if I can reproduce it locally? It doesn't have to be the one with the samples, the basic template would work.

**Comment by FedericoComoglio** [comment]
Sure, here it is:

```
details:
  - analysis: variant2
    genome_build: hg38
    metadata:
       batch: #your-batch-name
       phenotype: #tumor # or "normal"
    algorithm:
      aligner: bwa
      mark_duplicates: true
      remove_lcr: true
      variant_regions: <Regions.bed> # this a WES panel
      exclude_regions: [lcr, polyx, highdepth, altcontigs]
      min_allele_fraction: 10
      variantcaller:
        somatic: [vardict, mutect2, varscan, freebayes, strelka2]
      ensemble:
        numpass: 2
      svcaller: [manta, cnvkit]
      effects: snpeff 
      tools_on: [damage_filter]
    resources:
      tmp:
        dir: ./tmp
```

Thanks a lot!
