### ISSUE TITLE
Force skip re-bgzip of fastq data

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#2940]
Hi, 

I'm noticing the issue mentioned in #1760 has returned. 
Is there a way to force skip the recompressing of our input fastq's since this creates an enormous amount of overhead?

Thanks
Matthias

**Comment by roryk** [comment]
Thanks-- could you post the configuration YAML file that you are running? I want to see if I can reproduce it, I'm thinking there might be a specific configuration where we are not handling this properly.

**Comment by matthdsm** [comment]
Hi Rory,

We're not doing anything special as far as I can see. The config template is as found below
```
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
      ped:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - gemini
        - coverage_perbase
      tools_off:
        - gatk4
      archive: cram-lossless
    # add the path to your files here
    files:
```
