### ISSUE TITLE
bcbio cram support

### ISSUE THREAD

**Issue by Fazulur** [bcbio/bcbio-nextgen#2944]
Dear Bcbio team,

I have seen bcio gatk-variant & rna-seq pipeline has options to specify to get cram instead of bam.
here is example sample configuration i used
details:
```
- algorithm:
    aligner: star
    archive: cram
  analysis: RNA-seq
  description: 'test'
  files:
  - test_1.fastq.gz
  - test_2.fastq.gz
  genome_build: GRCh37
fc_name: 'test'
resources:
  default:
    cores: 8
upload:
  dir: test-rna-cram
```
From your manual, you are recommending to archive cram-lossless. 
When I check results, I didn't found cram file eventhough I specified archive:cram in configuration.
Could you please help me to get resolve this issue.

Thanks In Advance
Fazulur Rehaman
