### ISSUE TITLE
What is the difference between Cancer variant calling pipeline and Somatic with germline variants?

### ISSUE THREAD

**Issue by hliu2016** [bcbio/bcbio-nextgen#2951]
Hi, If I have paired tumor/normal samples and want to find the tumor-specific somatic variants, which pipeline should I used? 

For the pipeline of somatic with germline variants, I wonder if the somatic variant caller outputs which type of mutations, somatic or germline? If somatic, what is the underlying process of bcbio to tackle this?

```
description: your-normal
variantcaller:
   somatic: vardict
   germline: freebayes
```
