### ISSUE TITLE
Which variant callers are compatible to TitanCNA?

### ISSUE THREAD

**Issue by leiendeckerlu** [bcbio/bcbio-nextgen#2975]
Hi there,

I'd like to look into LOH in a tumor/normal pair like this:

```
upload:
  dir: ./final
details:
  - analysis: variant2
    description: normal1
    metadata:
      phenotype: normal
      batch:  MCC_1
    files: [1N_aligned_sorted_dedub.bam]
    genome_build: hg38
    algorithm:
      platform: illumina
      aligner: false
      quality_format: standard
      variantcaller: samtools
      svcaller: [gatk-cnv, titancna, purecn]
  - analysis: variant2
    description: tumor1
    metadata:
      phenotype: tumor
      batch:  MCC_1
    files: [1T_aligned_sorted_dedub.bam]
    genome_build: hg38
    algorithm:
      platform: illumina
      aligner: false
      quality_format: standard
      variantcaller: samtools
      svcaller: [gatk-cnv, titancna, purecn]
```
However, after the variant calling and at the start of TitanCNA I get the following error message:

> ipyparallel.error.CompositeError: one or more exceptions from call to method: detect_sv
> [0:apply]: AssertionError: Did not find compatible variant calling files for TitanCNA inputs
> [0:apply]: IndexError: list index out of range

I could nowhere in the documentation/code find which variant caller combinations can be used together with titanCNA, could you give me some insights?

Thank you,
Lukas
