### ISSUE TITLE
ChrY variants on Female sample

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#2983]
Even thought I specified that the sample had sex female I see variants in ChrY, Is this normal?

**Comment by roryk** [comment]
Hi Konstantinos,

It is normal to see variants on the Y chromosome, even in a female sample. If you look in the multiqc report there should be some metrics regarding what the predicted genders of your sample are, so you can check if there is a swap. Even if there wasn't a swap, there are trace reads that align to Y t hat can be enough to call a variant there as well.

**Comment by kokyriakidis** [comment]
Hi Rory!

Why don't you just exclude Y chromosome when sex female is defined, so It is easier for downstream analysis?

**Comment by roryk** [comment]
The sample might not really be a female!

**Comment by kokyriakidis** [comment]
Hi Rory!

One more thing. I specified in my config file: effects: vep, but the line I get are like that:

```
chrY	56874973	rs6568306	C	G	141.0	PASS	AC=1;AF=1;AN=1;CALLERS=gatk-haplotype,strelka2;DP=4;FS=0;MLEAC=1;MLEAF=1;MMQ=60,45;MQ=45.62;MQ0=0;QD=28.08;SOR=0.693;rs_ids=rs6568306	GT:AD:DP:GQ:PL	1:0,4:4:99:151,0

```
The template I used is:
```
details:
- algorithm:
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - strelka2
  analysis: variant2
  description: 178F
  files:
  - /mnt/36642bae-9ec9-4100-88a2-ac173a20ea16/WORKDIR/BRAZILIANS/178F/input/SRR6701493_1.fastq.gz
  - /mnt/36642bae-9ec9-4100-88a2-ac173a20ea16/WORKDIR/BRAZILIANS/178F/input/SRR6701493_2.fastq.gz
  genome_build: hg38
  metadata:
    sex: female
fc_name: 178F
upload:
  dir: ../final
```

There should have been VEP anntoation, right?
