### ISSUE TITLE
error to use PoN(panel of normal) as background for CNVkit

### ISSUE THREAD

**Issue by HyunjunNam** [bcbio/bcbio-nextgen#2997]
I made a PoN by using CNKkit below,
`pon_build-cnvkit-background.cnn`

Then I tried to use this *.cnn file as background (PoN) to running CNVkit, but It did not run on them. (It did run well without *.cnn )
This is yaml file that I used for this,

```
details:
- algorithm:
    aligner: bwa
    align_split_size: 5000000
    recalibrate: false
    realign: false
    variantcaller: false
    remove_lcr: true
    svcaller: [cnvkit]
    background:
      cnv_reference:
        cnvkit: /PoN/testsample/pon_build-cnvkit-background.cnn
  analysis: variant2
  description: NTP17-004880
  files:
  - ../input/testsanple_R1_001.fastq.gz
  - ../input/testsample_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: test
upload:
  dir: ../final
```
Is this yaml file correct?
 As I know, once I made reference file (*.cnn/PoN), I can use it continuously for the different analysis, instead of making PoN  every time again. Is it right?
