### ISSUE TITLE
samtools sort: couldn't allocate memory for bam_mem

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#3092]
Hi,

The first full variant calling run on our shiny new cluster has failed with this error: `samtools sort: couldn't allocate memory for bam_mem`

It looks like the command that's failing is `unset JAVA_HOME && /share/apps/rosalind/bcbio-nextgen/master/galaxy/../anaconda/bin/bwa mem   -c 250 -M -t 28  -R '@RG\tID:C1690\tPL:illumina\tPU:C1690\tSM:C1690' -v 1 /share/apps/rosalind/bcbio-nextgen/master/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /scratch/semlucas/bcbio/PC-WGS-gatk/work/align_prep/C1690_1690_R1.fastq.gz 1 80000000) <(grabix grab /scratch/semlucas/bcbio/PC-WGS-gatk/work/align_prep/C1690_1690_R2.fastq.gz 1 80000000)  | /share/apps/rosalind/bcbio-nextgen/master/galaxy/../anaconda/bin/samtools sort -n -@ 28 -m 2G -O bam -T /scratch/semlucas/bcbio/PC-WGS-gatk/work/bcbiotx/tmp862fn1pz/C1690-sort-1_80000000-sorttmp-namesort -o /scratch/semlucas/bcbio/PC-WGS-gatk/work/bcbiotx/tmp862fn1pz/C1690-sort-1_80000000.bam -`

The cluster has 28 cpus and 128G RAM per node, so that samtools sort command should be well within the available memory. Any ideas on what might be going on?

Debug log file attached:
[bcbio-nextgen-debug-sionne200213.log](https://github.com/bcbio/bcbio-nextgen/files/4196323/bcbio-nextgen-debug-sionne200213.log)

**Comment by ohofmann** [comment]
What is your job scheduler? If I read the comment right it looks like you end up with only 2GB per thread which might be a bit tight; 3-4G/core is a better bet for most bwa-mem tasks.

**Comment by DrMcStrange** [comment]
The scheduler is PBSPro. I've got `bcbio_system.yaml` set to use 4G per core, so I'm not sure why samtools is only asking for 2G...

**Comment by roryk** [comment]
Hi Bennet,

Do you think you could pass on the bcbio_system.yaml you are using and the log/bcbio-nextgen-debug.log file so we can take a look? The call to bwa/samtools there should be respecting the 4G per core setting, and looking at both of those will help us figure out why it is not.

**Comment by DrMcStrange** [comment]
Hi Rory,

The bcbio-nextgen-debug.log is attached in my original message above. Here's the bcbio_system.yaml:

```
---
# Configuration file specifying system details for running an analysis pipeline
# These pipeline apply generally across multiple projects. Adjust them in sample
# specific configuration files when needed.

# -- Base setup

# Define resources to be used for individual programs on multicore machines.
# These can be defined specifically for memory and processor availability.
# - memory: Specify usage for memory intensive programs. The indicated value
#           specifies the wanted *per core* usage.
# - cores: Define cores that can be used for multicore programs. The indicated
#          value is the maximum cores that should be allocated for a program.
# - jvm_opts: specify details
resources:
  # default options, used if other items below are not present
  # avoids needing to configure/adjust for every program
  default:
    memory: 4G
    cores: 28
    jvm_opts: ["-Xms750m", "-Xmx3500m"]
  # Can also set program specific options
  # gatk:
  #   jvm_opts: ["-Xms500m", "-Xmx3500m"]
  snpeff:
    jvm_opts: ["-Xms750m", "-Xmx3g"]
  qualimap:
    memory: 4g
  express:
    memory: 8g
  dexseq:
    memory: 10g
  macs2:
    memory: 8g
  seqcluster:
    memory: 8g

# Location of galaxy configuration file, which has pointers to reference data
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#reference-genome-files
galaxy_config: universe_wsgi.ini


# -- Additional options for specific integration, not required for standalone usage.

# Galaxy integration. Required for retrieving information from Galaxy LIMS.
#galaxy_url: http://your/galaxy/url
#galaxy_api_key: your_galaxy_api_key

# Details for hooking automated processing to a sequencer machine.
# Not required if running standalone pipelines.
# analysis:
#   # Can specify a different remote host to initiate
#   # the copy from. This is useful for NFS shared filesystems
#   # where you want to manage the copy from the base machine.
#   copy_user:
#   copy_host:
#   store_dir: /store4/solexadata
#   base_dir: /array0/projects/Sequencing
#   worker_program: nextgen_analysis_server.py
```

**Comment by DrMcStrange** [comment]
Any ideas on this? The resource request lines in the log appear to be requesting 4G for samtools, but for some reason the actual commands specify `-m 2G`.

**Comment by naumenko-sa** [comment]
Thanks for reporting!

I think memory setting decreases here:
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py#L38

for you it is from 4G to 2G.

In my runs I'm using 7G and getting 3G in samtools sort. That handles well most of typical WES and WGS cases.
```
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
```

```
[2019-07-14T07:57Z] unset JAVA_HOME && /n/app/bcbio/dev/anaconda/bin/bwa mem  -c 250 -M -t 7  -R '@RG\tID:pre293T\tPL:illumina\tPU:pre293T\tSM:pre293T' -v 1 /n/app/bcbio/dev/genomes/Hsapiens/hg38/bwa/hg38.fa <(grabix grab /path/sample_1.fq.gz 720000001 800000000) <(grabix grab /path/sample_2.fq.gz 720000001 800000000)  | /n/app/bcbio/dev/anaconda/bin/samtools sort -n -@ 7 -m 3G -O bam -T /path/sample-sort-720000001_800000000-sorttmp-namesort -o /path/sample-sort-720000001_800000000.bam -
```

I don't fully understand the motivation and logic of memory adjustment. Probably, we need to fix the adjustment or default memory setting to process the typical projects better.

Sergey
