### ISSUE TITLE
Trouble running dbNSFP

### ISSUE THREAD

**Issue by tathey** [bcbio/bcbio-nextgen#3122]
I was previously having issues running bcbio-nextgen on the AshkenaziTrio data set from ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio

I raised the issue here: [#3002 ](https://github.com/bcbio/bcbio-nextgen/issues/3002) and the solution was to remove dbNSFP which seemed to resolve the issue.  Now that everything seems to be running properly without dbNSFP, I'd like to work on getting dbNSFP running with the pipeline.

I just tried adding it back in and sure enough the pipeline stalled again.  I've attached some files that might be useful in helping me debug. Please let me know if there's anything else you might need.

[AshkenaziFam.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/4313704/AshkenaziFam.yaml.txt)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4313708/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4313709/bcbio-nextgen-commands.log)
[AshkenaziFam-ensemble-annotated-cre.vcfanno-combine.conf.txt](https://github.com/bcbio/bcbio-nextgen/files/4313716/AshkenaziFam-ensemble-annotated-cre.vcfanno-combine.conf.txt)
[AshkenaziFam-ensemble-annotated-cre.vcfanno-combine.lua.txt](https://github.com/bcbio/bcbio-nextgen/files/4313717/AshkenaziFam-ensemble-annotated-cre.vcfanno-combine.lua.txt)

Thanks,
Taryn

**Comment by naumenko-sa** [comment]
Hi Taryn @tathey !

Thanks for reporting!
Unfortunately, I cannot reproduce the bug.

I'm running:
`bcbio_nextgen.py ../config/ashkenazim.yaml -n 7`

ashkenazim.yaml:
```
details:
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - samtools
    - platypus
    - freebayes
    vcfanno:
    - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/config/cre.vcfanno.conf
  analysis: variant2
  description: HG002_NA24385_son
  files:
  - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/input/HG002_NA24385_son.chr22.bam
  genome_build: hg38
  metadata:
    batch: ashkenazi_fam
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - samtools
    - platypus
    - freebayes
    vcfanno:
    - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/config/cre.vcfanno.conf
  analysis: variant2
  description: HG003_NA24149_father
  files:
  - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/input/HG003_NA24149_father.chr22.bam
  genome_build: hg38
  metadata:
    batch: ashkenazi_fam
- algorithm:
    aligner: bwa
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    mark_duplicates: true
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller:
    - gatk-haplotype
    - samtools
    - platypus
    - freebayes
    vcfanno:
    - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/config/cre.vcfanno.conf
  analysis: variant2
  description: HG004_NA24143_mother
  files:
  - /n/data1/cores/bcbio/naumenko/ashkenazim_trio/input/HG004_NA24143_mother.chr22.bam
  genome_build: hg38
  metadata:
    batch: ashkenazi_fam
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
```

cre.vcfanno.conf:
```
# using prefix vcfanno to discriminate data from vcfanno and vep
[[annotation]]
file="variation/gnomad_exome.vcf.gz"
fields=["AC","nhomalt","AF_popmax","AN"]
names=["vcfanno_gnomad_ac_es","vcfanno_gnomad_hom_es","vcfanno_gnomad_af_es","vcfanno_gnomad_an_es"]
ops=["first","first","first","first"]

[[annotation]]
file="variation/gnomad_genome.vcf.gz"
fields=["AC", "nhomalt","AF_popmax","AN"]
names=["vcfanno_gnomad_ac_gs", "vcfanno_gnomad_hom_gs","vcfanno_gnomad_af_gs","vcfanno_gnomad_an_gs"]
ops=["self","self","self","self"]

[[postannotation]]
fields=["vcfanno_gnomad_ac_es","vcfanno_gnomad_ac_gs"]
op="sum"
name="vcfanno_gnomad_ac"
type="Integer"

[[postannotation]]
fields=["vcfanno_gnomad_hom_es","vcfanno_gnomad_hom_gs"]
op="sum"
name="vcfanno_gnomad_hom"
type="Integer"

[[postannotation]]
fields=["vcfanno_gnomad_af_es","vcfanno_gnomad_af_gs"]
op="max"
name="vcfanno_gnomad_af_popmax"
type="Float"

[[postannotation]]
fields=["vcfanno_gnomad_an_es","vcfanno_gnomad_an_gs"]
op="sum"
name="vcfanno_gnomad_an"
type="Integer"

[[postannotation]]
fields=["vcfanno_gnomad_ac","vcfanno_gnomad_an"]
op="div2"
name="vcfanno_gnomad_af"
type="Float"

[[annotation]]
file="variation/dbsnp-151.vcf.gz"
fields=["ID"]
names=["rs_ids"]
ops=["concat"]

[[annotation]]
file="variation/clinvar.vcf.gz"
fields=["CLNSIG"]
names=["clinvar_pathogenic"]
ops=["concat"]

#dbNSFP v3.4
[[annotation]]
file = "variation/dbNSFP.txt.gz"
names = ["CADD_phred","phyloP20way_mammalian","phastCons20way_mammalian","Vest3_score","Revel_score","Gerp_score"]
columns = [79,111,115,58,70,107]
ops = ["first","first","first","first","first","first"]
```
bcbio runs fine, the resulting ashkenazi_fam-ensemble-annotated.vcf.gz  has the annotations from dbNSFP:

```
gunzip -c ashkenazi_fam-ensemble-annotated.vcf.gz | grep -v "^#"   | grep CADD | head  -n1 | grep "CADD\|Vest3"
chr8	38057098	rs1368272021	G	C	1381.4	PASS	AC=6;AF=1;AN=6;CALLERS=gatk-haplotype,samtools,freebayes;DP=54;ExcessHet=3.0103;FS=0;MLEAC=6;MLEAF=1;MMQ=60,60;MQ=56.08;MQ0=0;QD=33.52;SOR=1.911;CSQ=C|missense_variant|MODERATE|EIF4EBP1|ENSG00000187840|Transcript|ENST00000338825|protein_coding|2/3||ENST00000338825.5:c.163G>C|ENSP00000340691.4:p.Asp55His|203/827|163/357|55/118|D/H|Gac/Cac|rs1368272021|1||1||1|SNV|HGNC|HGNC:3288|YES|1|P1|CCDS6100.1|ENSP00000340691|Q13541||UPI000006E50A||Ensembl|G|G|||deleterious(0)|probably_damaging(1)|PDB-ENSP_mappings:1ej4.B&PDB-ENSP_mappings:1ejh.E&PDB-ENSP_mappings:1ejh.F&PDB-ENSP_mappings:1ejh.G&PDB-ENSP_mappings:1ejh.H&PDB-ENSP_mappings:1wkw.B&PDB-ENSP_mappings:2jgb.B&PDB-ENSP_mappings:2jgc.B&PDB-ENSP_mappings:2v8w.B&PDB-ENSP_mappings:2v8w.F&PDB-ENSP_mappings:2v8x.B&PDB-ENSP_mappings:2v8x.F&PDB-ENSP_mappings:2v8y.B&PDB-ENSP_mappings:2v8y.F&PDB-ENSP_mappings:3hxg.C&PDB-ENSP_mappings:3hxi.C&PDB-ENSP_mappings:3m93.C&PDB-ENSP_mappings:3m94.C&PDB-ENSP_mappings:3u7x.C&PDB-ENSP_mappings:3u7x.D&PDB-ENSP_mappings:4ued.B&PDB-ENSP_mappings:5bxv.B&PDB-ENSP_mappings:5bxv.D&PDB-ENSP_mappings:5ekv.B&PDB-ENSP_mappings:5ekv.D&PDB-ENSP_mappings:5nvn.B&PDB-ENSP_mappings:5nvn.D&PDB-ENSP_mappings:6bcu.X&PDB-ENSP_mappings:6bcu.Z&PDB-ENSP_mappings:6bcx.X&PDB-ENSP_mappings:6bcx.Z&Pfam:PF05456&PANTHER:PTHR12669&PANTHER:PTHR12669:SF14||chr8:g.38057098G>C|||||||||||||||||||||||||||||||||||,C|non_coding_transcript_exon_variant|MODIFIER|EIF4EBP1|ENSG00000187840|Transcript|ENST00000520657|processed_transcript|2/3||ENST00000520657.1:n.71G>C||71/695|||||rs1368272021|1||1|||SNV|HGNC|HGNC:3288||3||||||||Ensembl|G|G|||||||chr8:g.38057098G>C|||||||||||||||||||||||||||||||||||,C|missense_variant|MODERATE|EIF4EBP1|1978|Transcript|NM_004095.4|protein_coding|2/3||NM_004095.4:c.163G>C|NP_004086.1:p.Asp55His|203/827|163/357|55/118|D/H|Gac/Cac|rs1368272021|1||1||1|SNV|EntrezGene|HGNC:3288|YES||||NP_004086.1|||||RefSeq|G|G|||deleterious(0)|probably_damaging(1)|||chr8:g.38057098G>C|||||||||||||||||||||||||||||||||||,C|regulatory_region_variant|MODIFIER|||RegulatoryFeature|ENSR00000852933|promoter_flanking_region||||||||||rs1368272021|1||||1|SNV|||||||||||||||||||||chr8:g.38057098G>C|||||||||||||||||||||||||||||||||||;rs_ids=rs1368272021;CADD_phred=32;phyloP20way_mammalian=1.036000;phastCons20way_mammalian=0.997000;Vest3_score=0.952,0.955;Revel_score=0.787;Gerp_score=5.25	GT:AD:DP:GQ:PL	1/1:0,5:5:15:225,15,0	1/1:0,7:7:21:315,21,0	1/1:0,20:20:60:855,60,0
```

In your error log I can't see any clues.

1. Could you try variant calling in hg38 not grch37?  - that is the key difference between our tests.
2. If you can narrow down the variant that causes the crash, that may help.

Sergey
