### ISSUE TITLE
no rRNA statistics in a big 360 sample bulk RNA-seq run

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3135]
reported by @vbarrera

**Version info**
 - bcbio version: 1.2.0
 - OS name and version: 3.10.0-327.el7.x86_64

**To Reproduce**
 - Exact bcbio command you have used
`bcbio_nextgen.py ../config/${project_name}.yaml -n "$n" -t ipython -s slurm -q short -r t=0-11:59 --retries 3 --timeout 1000`
 - Your sample con
figuration file
it is 360 sample bcbio run 

```
details:
- algorithm:
    aligner: star
  analysis: RNA-seq
  description: S100
  files:
  - /path/S100_R1.fastq.gz
  - /path/S100_R2.fastq.gz
  genome_build: hg38
  metadata:
    sample_id: 80_D
    subtype: triple_negative
# and so on, 360 samples
```

**Observed behavior**
bcbio finishes ok, but in the final/project/multiqc/report/metrics/S100_bcbio.txt. rRNA statistics are not reported:
```
Sequences_flagged_as_poor_quality	0
Sequence_length	35-76
%GC	53
Name	S100
Quality_format	standard
rRNA	NA
rRNA_rate	NA
5'-3'_bias	3.31
Intergenic_Rate	0.0131
Intronic_Rate	0.1624
Exonic_Rate	0.8245
Duplication_Rate_of_Mapped	0.3905190905190905
Average_insert_size	950.1
Total_reads	442356.0
Mapped_reads	419581.0
Mapped_paired_reads	419580.0
Duplicates	0.0
Average_read_length	75.0
sample	S100
RiP_pct	0.000
Duplicates_pct	39.05190905190905
```
project/multiqc/multiqc_data/multiqc_bcbio_metrics.txt does not have rRNA metrics as well

**Expected behavior**
report rRNA stats in multiqc

**Log files**
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4356304/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4356305/bcbio-nextgen-commands.log)
Please attach: `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4356307/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4356309/bcbio-nextgen-commands.log)
