### ISSUE TITLE
hisat2_read_statistics.py syntax error

### ISSUE THREAD

**Issue by tony-travis** [bcbio/bcbio-nextgen#3181]
**Version info**
 - bcbio version (bcbio_nextgen.py --version): 1.2.2
 - OS name and version: Ubuntu 18.04.4 LTS

**To Reproduce**
 - Exact bcbio command you have used
/usr/local/bcbio/anaconda/bin/python3.6 /usr/local/bcbio/bin/bcbio_nextgen.py -t ipython -s slurm -q main -n 11 /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/papin/config/papin.yaml -r timelimit=+30-00:00:00
 - Your sample configuration file
```
details:
- algorithm:
    aligner: hisat2
    bcbiornaseq:
      genomeBuild: GRCh38
      interesting_groups:
      - batch
      - group
      - timepoint
      organism: homo sapiens
    kraken: minikraken
    strandedness: firststrand
    tools_on: bcbiornaseq
  analysis: RNA-seq
  description: _WT1_6hr
  files:
  - /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_WT1_6hr_R1.fastq.gz
  - /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_WT1_6hr_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: WT1
    group: TAU
    timepoint: 6hr
```
[...]
```
- algorithm:
    aligner: hisat2
    bcbiornaseq:
      genomeBuild: GRCh38
      interesting_groups:
      - batch
      - group
      - timepoint
      organism: homo sapiens
    kraken: minikraken
    strandedness: firststrand
    tools_on: bcbiornaseq
  analysis: RNA-seq
  description: _231K_3hr
  files:
  - /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_231K_3hr_R1.fastq.gz
  - /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_231K_3hr_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: 231K
    group: TAU-KO
    timepoint: 3hr
fc_name: papin
upload:
  dir: ../final
```
[bcbio-logs.zip](https://github.com/bcbio/bcbio-nextgen/files/4464885/bcbio-logs.zip)

**Observed behavior**
```
[2020-04-09T15:46Z] serenity: Aligning lane _WT1_6hr with hisat2 aligner
[2020-04-09T15:46Z] serenity: Aligning /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_WT1_6hr_R1.fastq.gz and /work/EOC/paganetti/papin/Tau_KO_Papin-64260198/FASTQ_merge/_WT1_6hr_R2.fastq.gz with hisat2.
[2020-04-09T15:46Z] serenity:   File "/usr/local/bcbio/bin/../anaconda/envs/python2/bin/hisat2_read_statistics.py", line 182
[2020-04-09T15:46Z] serenity:     length_map = sorted(length_map.iteritems(), key=lambda (k,v):(v,k), reverse=True)
[2020-04-09T15:46Z] serenity:                                                            ^
[2020-04-09T15:46Z] serenity: SyntaxError: invalid syntax
```

**Expected behavior**
No syntax error

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
This issue has been raised as a Python 3 incompatibility in
[hisat2](https://github.com/DaehwanKimLab/hisat2/issues/236) but the "bcbio_nextgen" env should be running Python 2.
