### ISSUE TITLE
FATAL error, could not open file sjdbGTFfile=None

### ISSUE THREAD

**Issue by fenggm15** [bcbio/bcbio-nextgen#3228]
Hi,
I'm trying to run rna-seq using star and WBcel235(C. elegans genome), but I'm running in to trouble.
$ bcbio_nextgen.py ../config/seqc.yaml -n 8

I get this error:
 GTF not compatible with Qualimap, skipping
and 
FATAL error, could not open file sjdbGTFfile=None

Is there something wrong with my commend? Thank you!

**Comment by naumenko-sa** [comment]
Hi!

1) it sound similar to [this issue](https://github.com/bcbio/bcbio-nextgen/issues/3195)
can you try advice outlined there, i.e. to specify GTF in the config?
2) please provide your YAML config.

Sergey

**Comment by fenggm15** [comment]
Hi Sergey,
Thanks for your reply! Here is my YAML file:

# Template for C. elegans RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: WBcel235
    algorithm:
      quality_format: Standard
      aligner: star
      strandedness: unstranded
upload:
  dir: ../final

Do you suggest me to add more annotations to it?
Thank you!

Best,
Gaomin
________________________________

**Comment by fenggm15** [comment]
Hi,
I add all these annotations to my YAML file, but I still have this problem--"FATAL error, could not open file sjdbGTFfile=None".
Is there anything I can do? Thank you!

My new YAML file is :
# Template for C. elegans RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: WBcel235
    algorithm:
      quality_format: Standard
      aligner: star
## uncomment below if adapter trimming needs to be performed
## most samples will not need this
#      trim_reads: read_through
#      adapters: [truseq, polya]
## uncomment below if strandedness needs to be set
#      strandedness: unstranded
## uncomment below if fusion calling is necessary
#      fusion_caller: [pizzly, oncofuse]
## uncomment below if variant calling is necessary, vardict also supported
#      variantcaller: [gatk-haplotype, vardict]
## uncomment below if you want other expression callers, salmon is run by default
#      expression_caller: [cufflinks, express, stringtie, sailfish, dexseq, kallisto, salmon]
## uncomment below if you want to provide a custom transcriptome FASTA file
#      transcriptome_fasta: your-transcriptome.fa
## uncomment below if you want to provide a custom transcriptome GTF file
#      transcriptome_gtf: your-transcriptome.gtf
## uncomment below if you want to want to provide a FASTA file of spikeins to quantify
#      spikein_fasta: your-spikein.fa
      strandedness: unstranded
upload:
  dir: ../final

**Comment by amizeranschi** [comment]
Hi @fenggm15

You should add the full real paths and file names for your FASTA and GTF file, for the system where you are running bcbio. Something like `/home/fenggm15/WBcel235/WBcel235.fasta`. 

You should also remove the `#` symbol from the beginning. Lines that begin with this symbol are interpreted as comments and they are ignored by bcbio.

In general, the convention is that lines beginning with `##` are comments with explanations for the user, while lines beginning with `#` are actual programming code lines that have been turned into comments so that they get disabled and ignored by the program. `Uncommenting a line` means to by removing the `#` symbol from the beginning to re-enable the code .

So, you probably want your YAML file to look something like below, but make sure to add the real paths to the FASTA and GTF files for the options `transcriptome_fasta` and `transcriptome_gtf`:

```
# Template for C. elegans RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: WBcel235
    algorithm:
      quality_format: Standard
      aligner: star
      strandedness: unstranded
      transcriptome_fasta: /put/the/real/path/here.fasta
      transcriptome_gtf: /put/the/real/path/here.gtf
upload:
  dir: ../final
```

**Comment by fenggm15** [comment]
Hi,
Thanks for your reply! I have my genome data in /share/bcbio-nextgen/genomes/Celegans/WBcel235/seq/WBcel235.fa, however, I don't have rnqseq/WBcel235.gtf under my WBcel235 folder.  I think maybe I didn't download all of them when I install bcbio-nextgene.py. I try to upgrade the bcbio-nextgene by running "bcbio_nextgen.py upgrade -u stable --tools --data --genome WBcel235 --datatarget rnaseq", but I get an error:

yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 19, column 15:
            GitHub:  https://github.com/QuantStack ...
Now I'm considering maybe I should download the genome fasta file and GTF file by myself and upload them to the genome folder.
What do you think? Thanks for your reply!

Best,
Gaomin

**Comment by amizeranschi** [comment]
This seems related to https://github.com/bcbio/bcbio-nextgen/issues/3223 and https://github.com/bcbio/bcbio-nextgen/issues/3180. Try upgrading to the development version:

```
bcbio_nextgen.py upgrade -u development --tools --data --genome WBcel235 --datatarget rnaseq
```

**Comment by fenggm15** [comment]
Hi, 
I tried the development version and it upgrades successfully. But I still can't see the rnaseq file under my genomes file. The program shows as follows:
List of genomes to get (from the config file at '{'genomes': [{'dbkey': 'WBcel235', 'name': 'C elegans (WBcel235)', 'annotations': []}], 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'star'], 'install_liftover': False, 'install_uniref': False}'): C elegans (WBcel235)
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
Is there anything I can change?
Thank you!

**Comment by naumenko-sa** [comment]
Hi @fenggm15 !

Thanks for following up.

We indeed missing transcriptome installation support for _C.elegans_ . 
To install it  manually, you can run:

1. clone cloudbiolinux:
```git clone git@github.com:chapmanb/cloudbiolinux.git```

2. cd to the main dir of C.elegans:
`cd /share/bcbio-nextgen/genomes/Celegans`

3. make sure your python is bcbio python
`which python`
should point to bcbio/anaconda/bin/python

4. generate transcriptome files:
`~/code/cloudbiolinux/utils/prepare_tx_gff.py Celegans WBcel235`
you should see gtf and other files generated in `WBcel235/rnaseq`

5. modify your `genomes/Celegans/WBcel235/seq/WBcel235-resources.yaml`:
(add links to RNA-seq file)
```
version: 18

aliases:
  ensembl: caenorhabditis_elegans_vep_99_WBcel235
  snpeff: WBcel235.86

rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  dexseq: ../rnaseq/ref-transcripts.dexseq.gff3
  refflat: ../rnaseq/ref-transcripts.refFlat
  rRNA_fa: ../rnaseq/rRNA.fa
```
6. Generate STAR index
`bcbio_nextgen.py upgrade -u skip --genomes WBcel235 --aligners star --cores 10`

Let us know if that works for you!

_C.elegans_ is a model organism, so we are going to push gtf annotations to the cloud and create a recipe to allow transcriptome installation via --datatarget rnaseq

Sergey
