### ISSUE TITLE
Support for 3'UTR RNAseq

### ISSUE THREAD

**Issue by mmoisse** [bcbio/bcbio-nextgen#3235]
**Version info**
 - bcbio version: 1.1.9a
 - OS name and version: CentOS Linux release 7.6.1810 (Core)

**To Reproduce**

`bcbio_nextgen.py $dataDir/config/file.yaml -n 1`

The error occurs when you add --noLengthCorrection to the salmon command
```
details:
- algorithm:
    aligner: star
    archive: cram-lossless
    expression_caller:
    - salmon
    - htseq
    save_diskspace: true
    strandedness: secondstrand
  analysis: RNA-seq
  description: GC06
  files:
  - /upload/GC06.R1.fastq.gz
  genome_build: hg19
  metadata:
    batch: 3pUTR
    ped: /config/3pUTR.ped
    phenotype: unaffected
fc_name: RNA_3pUTR
resources:
  salmon:
    options:
    - --noLengthCorrection
upload:
  dir: ../final

```

**Observed behavior**
```
[2020-05-24 18:35:37.466] [jointLog] [critical] Since bias correction relies on modifying effective lengths, you cannot enable bias correction simultaneously with the --noLengthCorrection option.
' returned non-zero exit status 1.
```

**Expected behavior**
That the hardcoded bias flags are lowered then using the --noLengthCorrection option.
