### ISSUE TITLE
Pre-aligned files are duplicate-filtered in ChIP-Seq analysis when not required

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#3237]
**Version info**
 - bcbio version: 1.2.3
 - OS name and version: Ubuntu 18.04 LTS

**To Reproduce**
 - bcbio_nextgen.py -t ipython -s slurm -q main -n $CORES /opt/bcbio/galaxy/bcbio_system.yaml $CONFIG -r timelimit=+60-00:00:00

 - Sample configuration file:
```
details:
- analysis: chip-seq
  genome_build: hg19
  algorithm:
    aligner: false
    bam_clean: fixrg
    mark_duplicates: false
    trim_reads: false
    peakcaller: [macs2]
  resources:
    macs2:
      options: ["-q 0.05"]
```

**Observed behavior**
When using pre-aligned files for ChIP-Seq analysis, although _aligner_ is set to false and _fixrg_ is on, duplicates removal has been applied to aligned files. I re-run with the same configuration setting _mark_duplicates_ to false, but the behavior was still the same.

**Expected behavior**
I expected pre-aligned files not to be duplicate-filtered.

**Log files**
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/4675752/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/4675756/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/4675758/bcbio-nextgen-debug.log)
