### ISSUE TITLE
bcbio_vm error

### ISSUE THREAD

**Issue by dvaka** [bcbio/bcbio-nextgen#3291]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_vm.py run -n 16 sample.yaml
[sample_yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/4873449/sample_yaml.txt)

```
Your sample configuration file:
```
upload:
  dir: /data/NA12878/
details:
  - files: [/data/NA12878/HG001_R1.fastq,/data/NA12878/HG001_R2.fastq]
    description: wgs_HG001
    analysis: 'variant'
    genome_build: hg38
    lane: wgs_HG001
    algorithm:
      aligner: bwa
      trim_reads: false
      mark_duplicates: true
      recalibrate: true
      realign: false
      variantcaller: [gatk-haplotype,freebayes,vardict,strelka2]
      svcaller: [lumpy,manta,gatk-cnv]
      ensemble:
       numpass: 1
       use_filtered: false
      tools_off: [gemini]
      tools_on: [qualimap_full, picard]
```

**Observed behavior**
Error message or bcbio output:
```
Using GATK jar /usr/local/share/bcbio-nextgen/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms750m -Xmx45864m -Djava.io.tmpdir=/mnt/work/bcbiotx/tmpemesijeh -jar /usr/local/share/bcbio-nextgen/anaconda/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar BaseRecalibratorSpark -I /mnt/work/align/wgs_HG001/wgs_HG001-sort.bam --output /mnt/work/bcbiotx/tmpemesijeh/wgs_HG001-sort-recal.grp --reference /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/seq/hg38.fa --spark-master local[16] --conf spark.driver.host=localhost --conf spark.network.timeout=800 --conf spark.executor.heartbeatInterval=100 --conf spark.local.dir=/mnt/work/bcbiotx/tmpemesijeh --known-sites /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg38/variation/dbsnp-153.vcf.gz -L /mnt/work/align/wgs_HG001/wgs_HG001-sort-callable_sample.bed --interval-set-rule INTERSECTION
' returned non-zero exit status 3.
' returned non-zero exit status 1.

```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
