### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3316]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): RHEL 2.6.32-279.el6.x86_64 

**To Reproduce**
Exact bcbio command you have used: Run bcbio as per normal with gatk4 off (using gatk3)
```

```
Your sample configuration file:
```
# SNV + SV calling
---
details:
- algorithm:
    platform: illumina
    quality_format: standard
    aligner: bwa
    save_diskspace: true
    tools_off: [fastqc,gatk4]
    bam_clean: false
    bam_sort: false
    mark_duplicates: true
    recalibrate: false
    realign: gatk
    variant_regions: /mnt/projects/simngl/wgs/pipeline/metadata/SureSelect_v4.bed
    remove_lcr: false
    variantcaller:
      somatic: [freebayes,vardict,varscan,strelka2, mutect2]
      germline: [strelka2, gatk-haplotype, freebayes]
    ensemble:
      numpass: 2
    svcaller: [lumpy,manta,cnvkit]
    indelcaller: false
  analysis: variant2
  description: Pt10_pre-N
  files: [../bam/normal.dir/SRR5134829_1.fastq.gz,../bam/normal.dir/SRR5134829_2.fastq.gz]
  genome_build: GRCh37
  metadata:
    batch: Pt10_pre
    phenotype: normal
- algorithm:
    platform: illumina
    quality_format: standard
    aligner: bwa
    save_diskspace: true
    tools_off: [fastqc,gatk4]
    bam_clean: false
    bam_sort: false
    mark_duplicates: true
    recalibrate: false
    realign: gatk
    variant_regions: /mnt/projects/simngl/wgs/pipeline/metadata/SureSelect_v4.bed
    remove_lcr: false    
    variantcaller: [freebayes,vardict,varscan,strelka2, mutect2]
    svcaller: [lumpy,manta,cnvkit]
    indelcaller: false
    ensemble:
      numpass: 2
  analysis: variant2
  description: Pt10_pre-T
  files: [../bam/tumor.dir/SRR5134764_1.fastq.gz,../bam/tumor.dir/SRR5134764_2.fastq.gz]
  genome_build: GRCh37
  metadata:
    batch: Pt10_pre
    phenotype: tumor
fc_date: '2015-07-31'
fc_name: Pt10_pre
upload:
  dir: ../bcbio_final
```

**Observed behavior**
Error message or bcbio output:
```
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkfilter.py", line 19, in run
    if includes_missingalt(data):
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/site-packages/bcbio/variation/gatkfilter.py", line 274, in includes_missingalt
    return version >= MISSINGALT_VERSION
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Expected behavior**
This appears to be similar to issue #2795, but the fix in version.py is there.
[Error_Log.log](https://github.com/bcbio/bcbio-nextgen/files/4985225/Error_Log.log)

**Log files**
Error log attached.

**Additional context**
