### ISSUE TITLE
floating point exception running freebayes somatic pipeline (vt issue)

### ISSUE THREAD

**Issue by parlar** [bcbio/bcbio-nextgen#3328]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): CentOS Linux release 7.8.2003 (Core)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py -t local -n 20 /path/config.yaml
```
Your sample configuration file:
```
---
upload:
  dir: ../final
details:
  - files: [/home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/Data/Intensities/BaseCalls/cutadapt/18-6036D_S15_R1_001.fastq.gz, /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/Data/Intensities/BaseCalls/cutadapt/18-6036D_S15_R2_001.fastq.gz]
    description: 18-6036D
    metadata:
      batch: B18-6036D
      sex: female
      phenotype: tumor
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      variantcaller: [freebayes]
      min_allele_fraction: 1
      variant_regions: /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/target_bed/twist_target.base.spikein.grch37.s.slop_b10.merge.s.bed
      mark_duplicates: true
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: true

```

**Observed behavior**
Error message or bcbio output:
```
 /home/bcbio-dev/local/share/bcbio/anaconda/bin/freebayes -f /home/bcbio-dev/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/freebayes/X/B18-6036D-X_39911351_69254810-regions.bed --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.01 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off -b /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/align/18-6036D/18-6036D-sort.bam
[2020-08-20T17:09Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/home/bcbio-dev/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /home/bcbio-dev/local/share/bcbio/anaconda/bin/freebayes -f /home/bcbio-dev/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/freebayes/X/B18-6036D-X_39911351_69254810-regions.bed --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.01 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off -b /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/align/18-6036D/18-6036D-sort.bam | bcftools filter -i 'ALT="<*>" || QUAL > 5' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}' | bcftools view  -a - | /home/bcbio-dev/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /home/bcbio-dev/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -q - | vcfuniqalleles | vt uniq - 2> /dev/null | bgzip -c > /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/bcbiotx/tmppem7bb8l/B18-6036D-X_39911351_69254810.vcf.gz
/usr/bin/bash: line 1:  4875 Done                    /home/bcbio-dev/local/share/bcbio/anaconda/bin/freebayes -f /home/bcbio-dev/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --genotype-qualities --strict-vcf --ploidy 2 --targets /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/freebayes/X/B18-6036D-X_39911351_69254810-regions.bed --min-repeat-entropy 1 --no-partial-observations --min-alternate-fraction 0.01 --pooled-discrete --pooled-continuous --report-genotype-likelihood-max --allele-balance-priors-off -b /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/align/18-6036D/18-6036D-sort.bam
      4876                       | bcftools filter -i 'ALT="<*>" || QUAL > 5'
      4877                       | awk -F'      ' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } {print}'
      4878                       | bcftools view -a -
      4879                       | /home/bcbio-dev/local/share/bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)'
      4880                       | vcfallelicprimitives -t DECOMPOSED --keep-geno
      4881                       | vcffixup -
      4882                       | vcfstreamsort
      4883 Floating point exception(core dumped) | vt normalize -n -r /home/bcbio-dev/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -q -
      4885                       | vcfuniqalleles
      4887                       | vt uniq - 2> /dev/null
      4889                       | bgzip -c > /home/bcbio-dev/projects/200327_NB551119_0200_AH5753AFX2/calling/work/bcbiotx/tmppem7bb8l/B18-6036D-X_39911351_69254810.vcf.gz
' returned non-zero exit status 136.

```

**Expected behavior**
Running bcbio 1.2.0 on the same machine but different user, it finishes without issue using the exact same data and yaml config.

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5107252/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/5107254/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5107255/bcbio-nextgen.log)

**Additional context**

When running the last command manually and removing steps in the pipe chain, it seems that the last step using ```vt normalize``` is the problem. However, the same version of vt normalize is used in bcbio-nextgen 1.2.3 and 1.2.0. 

I compared the output between v 1.2.3 and 1.2.0 for the step before vt normalize, and they are virtually identical:

diff shows this:
```
[bcbio-dev@vs478 work]$ diff bcbio-dev.out.txt bcbio.out.txt
142,145c142,145
< ##bcftools_filterVersion=1.10.2+htslib-1.10.2
< ##bcftools_filterCommand=filter -i 'ALT="<*>" || QUAL > 5'; Date=Fri Aug 21 09:29:11 2020
< ##bcftools_viewVersion=1.10.2+htslib-1.10.2
< ##bcftools_viewCommand=view -a -; Date=Fri Aug 21 09:31:49 2020
---
> ##bcftools_filterVersion=1.9+htslib-1.9
> ##bcftools_filterCommand=filter -i 'ALT="<*>" || QUAL > 5'; Date=Fri Aug 21 09:29:22 2020
> ##bcftools_viewVersion=1.9+htslib-1.9
> ##bcftools_viewCommand=view -a -; Date=Fri Aug 21 09:32:00 2020
```
I DON'T understand whats going on here ...
