### ISSUE TITLE
GatherVcfs error (resulting from incorrect FixVcfHeader command?)

### ISSUE THREAD

**Issue by DrMcStrange** [bcbio/bcbio-nextgen#3332]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.1.9a
- OS name and version (`lsb_release -ds`): CentOS Linux 7 (Core)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/ms-families.yaml -n 128
```
Your sample configuration file:
```
details:
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.10
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.10.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.3
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.3.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.4
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.4.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.5
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.5.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.7
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.7.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.8
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.8.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BTCK-1.9
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BTCK-1.9.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY1
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY1.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY2
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY2.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY3
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY3.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY4
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY4.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY5
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY5.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: BY6
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/BY6-ready.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL1
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL1.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL2
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL2.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL3
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL3.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: F
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL4
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL4.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL5
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL5.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
- algorithm:
    aligner: false
    bam_clean: fixrg
    jointcaller: gatk-haplotype-joint
    recalibrate: false
    tools_on: gvcf
    variantcaller: gatk-haplotype
  analysis: variant2
  description: CL6
  files:
  - /scratch/bennetm/bcbio-ms-families/ms-families/input/CL6.sorted.markdup.bam
  genome_build: hg19
  metadata:
    batch: MS_families
    sex: M
fc_name: ms-families
upload:
  dir: ../final
resources:
  default:
    memory: 8G
    cores: 8
    jvm_opts: ["-Xms750m", "-Xmx8000m"]
```

**Observed behavior**
Error message or bcbio output:
GatherVcfs throws errors for each sample.
```
ERROR	2020-08-28 00:49:24	GatherVcfs	There was a problem with gathering the INPUT.java.lang.IllegalArgumentException: First record in file /scratch/bennetm/bcbio-ms-families/ms-families/work/gatk-haplotype/chr1/BTCK-1_3-chr1_0_16882788.vcf.gz is not after first record in previous file /scratch/bennetm/bcbio-ms-families/ms-families/work/gatk-haplotype/BTCK-1_3-chrM_0_16571-fixheader.vcf.gz
```
I think maybe this results from FixVcfHeader on chrM sending output to parent directory instead of chrM directory. Command in bcbio-nextgen-commands.log is:
```
[2020-08-27T14:48Z] unset JAVA_HOME && export PATH=/share/apps/rosalind/bcbio-nextgen/master/anaconda/bin:"$PATH" && picard FixVcfHeader HEADER=/scratch/bennetm
/bcbio-ms-families/ms-families/work/bcbiotx/tmpebdn05ae/BY3-chrM_0_16571-fixheader-header.vcf INPUT=/scratch/bennetm/bcbio-ms-families/ms-families/work/gatk-hap
lotype/chrM/BY3-chrM_0_16571.vcf.gz OUTPUT=/scratch/bennetm/bcbio-ms-families/ms-families/work/gatk-haplotype/BY3-chrM_0_16571-fixheader.vcf.gz
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5139353/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5139354/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug-tail.log](https://github.com/bcbio/bcbio-nextgen/files/5139355/bcbio-nextgen-debug-tail.log)
