### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by kdrichards** [bcbio/bcbio-nextgen#3339]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):1.2.0
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/5177374/bcbio-nextgen-debug.log)

Your sample configuration file:

```
details:
  - analysis: variant2
    genome_build: hg38-noalt
    # to do multi-sample variant calling, assign samples the same metadata / batch
    algorithm:
      aligner: bwa
      mark_duplicates: true
      #svcaller: [lumpy, manta, cnvkit]
      recalibrate: gatk
      #realign: false
      variantcaller: 
        somatic:[vardict, strelka2, mutect2]
        germline:[freebayes, gatk-haplotype, strelka2]
      ensemble:
        numpass: 2
        use_filtered: false
      variant_regions: /data/GCBCNIDCR/Refs/GencodeRefSeqExons_hg38noAlt.bed
      remove_lcr: true
      effects: snpeff
      coverage_interval: regional
      coverage: /data/GCBCNIDCR/Refs/GATK_bundle/hg38/NRC_Targets_hg38.bed
      tools_off: [vsqr, gemini]
      tools_on: qualimap
```

**Observed behavior**
Error message or bcbio output:
```
BCBIO compilation (parallel) fails  with error:
AttributeError: 'NoneType' object has no attribute 'endswith' 
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
