### ISSUE TITLE
qualimap out of memory

### ISSUE THREAD

**Issue by nitishnih** [bcbio/bcbio-nextgen#3345]
Hi,

I am running an RNA-Seq variants pipeline based on https://bcbio-nextgen.readthedocs.io/en/latest/contents/rnaseq_variants.html

Here's my config:
```
details:
- algorithm:
    aligner: star
    strandedness: unstranded
    variantcaller: vardict
  analysis: RNA-seq
  description: HK-Group1_20-test
  files:
  - ../input/Group1_20_R1.fastq.gz
  - ../input/Group1_20_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: Group1_20
fc_name: Group1_20
resources:
  default:
    cores: 8
    memory: 10G
    jvm_opts:
    - -Xms8000m
    - -Xmx32000m
upload:
  dir: ../final
```

This is on a cluster with SLURM scheduler. The following relevant SBATCH options were used:
```
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=80G
```

At the end of the debug log, I see the following:
```
Traceback (most recent call last):
  File "/usr/local/apps/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/apps/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset DISPLAY && export LD_PRELOAD=/usr/local/apps/bcbio-nextgen/anaconda/lib/libfreetype.so && export PATH=/usr/local/apps/bcbio-nextgen/anaconda/bin:"$PATH" &&  export JAVA_OPTS='-Xms32m -Xmx4g -Djava.io.tmpdir=/lscratch/65532956/work/bcbiotx/tmpjxsd2rcu/HK-Group1_20-test' &&  /usr/local/apps/bcbio-nextgen/galaxy/../anaconda/bin/qualimap rnaseq -outdir /lscratch/65532956/work/bcbiotx/tmpjxsd2rcu/HK-Group1_20-test -a proportional -bam /lscratch/65532956/work/qc/HK-Group1_20-test/qualimap_rnaseq/HK-Group1_20-test-downsample.bam -p non-strand-specific --paired -gtf /usr/local/apps/bcbio-nextgen/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf
Java memory size is set to 1200M
Launching application...
detected environment java options -Xms32m -Xmx4g -Djava.io.tmpdir=/lscratch/65532956/work/bcbiotx/tmpjxsd2rcu/HK-Group1_20-test
QualiMap v.2.2.2-dev
Built on 2019-11-11 14:05
Selected tool: rnaseq
Thu Sep 24 10:51:37 EDT 2020		WARNING	Output folder already exists, the results will be saved there
Initializing regions from /usr/local/apps/bcbio-nextgen/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf...
Initialized 100000 regions...
Initialized 200000 regions...
Initialized 300000 regions...
Initialized 400000 regions...
Initialized 500000 regions...
Initialized 600000 regions...
Initialized 700000 regions...
Initialized 800000 regions...
Initialized 900000 regions...
Initialized 1000000 regions...
Initialized 1100000 regions...
Initialized 1200000 regions...
Initialized 1300000 regions...
Initialized 1400000 regions...
Initialized 1500000 regions...
Initialized 1600000 regions...
Initialized 1700000 regions...
Initialized 1800000 regions...
Initialized 1900000 regions...
Initialized 2000000 regions...
Initialized 2100000 regions...
Initialized 2200000 regions...
Initialized 2300000 regions...
Initialized 2400000 regions...
Initialized 2500000 regions...
WARNING: out of memory!
Qualimap allows to set RAM size using special argument: --java-mem-size
Check more details using --help command or read the manual.
' returned non-zero exit status 1.
```

It seems qualimap is not taking advantage of the memory I have allocated and set in the configuration. Is there a workaround for this?
