### ISSUE TITLE
atacseq ataqv report not present in final upload

### ISSUE THREAD

**Issue by adammaikai** [bcbio/bcbio-nextgen#3357]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.3
- OS name and version (`lsb_release -ds`): Ubuntu 16.04.7

**To Reproduce**
Exact bcbio command you have used:
```
cd $workspace && bcbio_nextgen.py \
	-w template $template_yaml \
	$metadata \
	$workspace \
	--workdir $workspace

bcbio_nextgen.py \
	$workspace/"${base_meta%.*}"/config/"${base_meta%.*}".yaml \
	-n 32 \
	--workdir $workspace
```
Your sample configuration file:
```
date: '2020-10-06 10:27:01.233366'
upload: /scratch/atacseq/final
bcbio_system: /shared/workspace/software/bcbio/galaxy/bcbio_system.yaml
samples:
- description: X2506_NPB
  dirs:
    config: /shared/workspace/software/bcbio/galaxy
    fastq: null
    flowcell: null
    galaxy: /shared/workspace/software/bcbio/galaxy
    work: /scratch/atacseq
  genome_build: hg38
  genome_resources:
    aliases:
      ensembl: homo_sapiens_merged_vep_100_GRCh38
      human: true
      snpeff: GRCh38.86
    rnaseq:
      dexseq: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.dexseq.gff3
      gene_bed: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.bed
      rRNA_fa: ../rnaseq/rRNA.fa
      refflat: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.refFlat
      transcriptome_index:
        tophat: ../rnaseq/tophat/hg38_transcriptome.ver
      transcripts: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf
      transcripts_mask: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts-mask.gtf
    srnaseq:
      mint_lookup: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/LookupTable.tRFs.MINTmap_v1.txt
      mint_other: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/OtherAnnotations.MINTmap_v1.txt
      mint_space: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/tRNAspace.Spliced.Sequences.MINTmap_v1.fa
      mirbase_hairpin: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/hairpin.fa
      mirbase_mature: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/mature.fa
      mirdeep2_fasta: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/Rfam_for_miRDeep.fa
      srna_transcripts: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/srna-transcripts.gtf
      trna_fasta: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/srnaseq/trna_mature_pre.fa
    variation:
      1000g: null
      clinvar: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/clinvar.vcf.gz
      cosmic: ../variation/cosmic.vcf.gz
      dbnsfp: ../variation/dbNSFP.txt.gz
      dbscsnv: ../variation/dbscSNV.txt.gz
      dbsnp: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/dbsnp-153.vcf.gz
      editing: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/editing/RADAR.bed.gz
      encode_blacklist: null
      esp: ../variation/esp.vcf.gz
      exac: ../variation/exac.vcf.gz
      gc_profile: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/coverage/gc/GC_profile.1000bp.cnp
      genesplicer: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/genesplicer
      genotype2phenotype: ../variation/G2P.csv
      germline_het_pon: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/germline_het_pon.bed.gz
      gnomad_exome: ../variation/gnomad_exome.vcf.gz
      gnomad_genome: ../variation/gnomad_genome.vcf.gz
      lcr: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/coverage/problem_regions/repeats/LCR.bed.gz
      polyx: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/coverage/problem_regions/repeats/polyx.bed.gz
      qsignature: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/qsignature.txt
      sv_repeat: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/coverage/problem_regions/repeats/sv_repeat_telomere_centromere.bed
      train_1000g: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/1000G_phase1.snps.high_confidence.vcf.gz
      train_hapmap: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/hapmap_3.3.vcf.gz
      train_indels: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/Mills_and_1000G_gold_standard.indels.vcf.gz
      train_omni: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/variation/1000G_omni2.5.vcf.gz
    version: 41
  metadata:
    batch: null
    phenotype: ''
    replicate: rep1
  sam_ref: /shared/workspace/software/bcbio/genomes/Hsapiens/hg38/seq/hg38.fa
  summary:
    metrics:
      '%GC': '47'
      Average_insert_size: 133.7
      Average_read_length: 101.0
      Duplicates: 26165319.0
      Mapped_paired_reads: 169587534.0
      Mapped_reads: 169882828.0
      Name: X2506_NPB
      Quality format: standard
      RiP: 42915359
      Sequence length: 30-101
      Sequences flagged as poor quality: '0'
      Total_reads: 170737294.0
```

**Observed behavior**
Error message or bcbio output:
```
I have found the command to execute ataqv in the commands log:

/shared/workspace/software/bcbio/galaxy/../anaconda/bin/ataqv --peak-file /scratch/atacseq/macs2/X2506_NPB-full/X2506_NPB-full_peaks.narrowPeak --name X2506_NPB --metrics-file /scratch/atacseq/bcbiotx/tmps0ur81dz/X2506_NPB.ataqv.json.gz --tss-file /scratch/atacseq/qc/X2506_NPB/ataqv/TSS.bed --autosomal-reference-file /scratch/atacseq/qc/X2506_NPB/ataqv/autosomal.txt --ignore-read-groups --mitochondrial-reference-name chrM --tss-extension 1000 None /scratch/atacseq/align/X2506_NPB/X2506_NPB-sort-shifted.bam

But I do not see the results in the final upload. The qc directory in each sample contains a fastqc and a samtools output. There is also a multiqc combined output.
```

**Expected behavior**
Shouldn't there be an ataqv summary for each sample or file all combined samples?

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5425261/bcbio-nextgen-commands.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5425262/bcbio-nextgen.log)

**Additional context**
