### ISSUE TITLE
miRNA counts are empty

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3368]
Hello everyone and especially @lpantano !

One of the bcbio users on O2 hit and an error with bcbio template:
```
upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star # any other aligner is supported.
      # change adapter according project
      adapters: ["TGGAATTCTCGGGTGC"] 
      expression_caller: [trna, seqcluster, mirdeep2]
      # expression_caller: [trna, seqcluster, mirdeep2, mirge] Read docs to know how to use
      # miRge tools: https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#smallrna-seq
      species: mmu
    genome_build: mm10
#resources:
#  atropos: 
#    options: ["-u 4", "-u -4"]
#  mirge: 
#    options: ["-lib $PATH_TO_LIBS_FOLDER"]
```

The run was successul, but there is no miRNA counts.
Files final/sample/mirbase-ready.counts are empty.

log files have 'mirdeep2 failed' message.

Let us know if you have any thoughts!
Sergey
