### ISSUE TITLE
Calculation of callable genome areas and the nomap_split_targets can take 600GB and more in main bcbio_nextgen.py

### ISSUE THREAD

**Issue by WimSpee** [bcbio/bcbio-nextgen#3376]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.1.5

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py analysis.yaml -t ipython  -n 101 -s sge  -q main.regular -r vf=5G,h_rss=50G
```
Your sample configuration file: (repeated for many samples)
```
details:
- algorithm:
    aligner: false
    coverage_interval: genome
    effects: false
    jointcaller: gatk-haplotype-joint
    mark_duplicates: false
    nomap_split_targets: 1000
    ploidy:
      default: 2
    realign: false
    recalibrate: false
    tools_off:
    - gemini
    variantcaller: false
  analysis: variant2
  description: sample_X
  files:
  - sample_X_input.bam
  genome_build: {REFERENCE_GENOME}
  lane: sample_X
  metadata:
    batch: DA_1234
  vrn_file: sample_X_input-gatk-haplotype.vcf.gz
```

**Observed behavior**

It can take a long time and a lot of memory to calculate the callable genome areas and the nomap_split_targets. This is because the BAM file of each sample is inspected for areas with(out) coverage.  If running a  whole genome joint analysis with a few hundred samples, this takes a lot of memory (e.g. we have noticed 600GB of memory required by the main bcbio_nextgen.py script, and multiple hours of wall time)

**Expected behavior**
By default less time and especially less memory needed to calculate callable genome areas and the nomap_split_targets. These values I think can easily and efficiently be calculated from just the NNNNNN stretches (of e.g. 250+bp ) in the reference genome.  
The BAM files then would not have to be touched. 

Or a way to pass in a nomap_split_targets file to work around this issue.
