### ISSUE TITLE
Bcbio not picking up rerun

### ISSUE THREAD

**Issue by matthdsm** [bcbio/bcbio-nextgen#3381]
**Version info**
- 1.1.5
- Ubuntu 16.04

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen ../config/config.yaml -n 75
```
Your sample configuration file:
```
fc_name:
upload:
  dir: ../final
globals:
  analysis_regions: /references/Hsapiens/hg38/coverage/capture_regions/CMGG_WES_analysis_ROI_v2.bed
  coverage_regions: /references/Hsapiens/hg38/coverage/capture_regions/CMGG_WES_analysis_ROI_v2.bed
details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
      ped:
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
        - gemini
        - coverage_perbase
        - picard
      tools_off:
        - gatk4
      archive: cram-lossless
    # add the path to your files here
    files:
```

**Observed behavior**
Analysis freezes when restarted after interruption.

**Expected behavior**
When an analysis is interrupted, bcbio should pick up where it left off.

**Additional Context**
We're running bcbio in a fixed environment, but conda got screwed up. We've had to reinstall the complete env and are encountering the issue above. We've tried installing the desired version using the `--revision` option of the install script, but that option seems to be completely ignored. As an alternative, I've downloaded the pinned release and pip installed in the conda env.
