### ISSUE TITLE
bcbio_setup_genome.py for scRNAseq

### ISSUE THREAD

**Issue by BrianLohman** [bcbio/bcbio-nextgen#3394]
Hello,

I am trying to setup a custom genome reference so that I can run the scRNAseq pipeline: https://bcbio-nextgen.readthedocs.io/en/latest/contents/single_cell.html

It looks like the function do do this is ```bcbio_setup_genome.py``` but its use to prep scRNAseq references is never mentioned (or I missed it). Also, the scRNAseq docs indicated that RapMap is used to generate alignments, which looks to require its own index. RapMap is also not an option for the ```setup_genomes.py -i``` argument.

Should I be using a different program to prep the reference and get it organized where bcbio can find it?

My experiments have run across many errors that others have, notably the empty ```tool-data/sam_fa_indices.loc``` as in #2234 (directory does not exist) but that might be a symptom of trying to use the wrong script to setup the reference. 

Thanks for your help

**Comment by roryk** [comment]
Hi Brian,

Hope you are well. Good question. Since the single-cell pipeline is just running Rapmap, it doesn't need a custom genome installation, you can provide your own FASTA of transcripts to quantitate along with a GTF file describing the transcripts by setting the `transcriptome_fasta` option and the `transcriptome_gtf` option. You will still need to set a valid `genome_build` but bcbio will just ignore it and use the `transcriptome_fasta` and `transcriptome_gtf` entries instead. Let me know if that doesn't get you going.

**Comment by BrianLohman** [comment]
Hi Rory,

Thanks for your reply. I tried specifying a valid ```genome_build``` option but bcbio threw an error when it could not find such a genome (I did the install with the ```--nodata``` flag). After installing the hg38 genome data bcbio will launch but throws an error. I am unsure if this is because bcbio is using the hg38 genome data or if it's an error in one of my config files. I have included the error logs here:
[bcbio_error.txt](https://github.com/bcbio/bcbio-nextgen/files/5717097/bcbio_error.txt)


I don't know what the key error could refer to. 'CB2' is not a sample name, does not appear in the yaml config file, or in the first few reads. 

yaml config:
```
details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /scratch/general/pe-nfs1/u0806040/natalie/sc_stickle/config/sample_barcodes.csv
    transcriptome_fasta: /scratch/general/pe-nfs1/u0806040/natalie/reference/Gasterosteus_aculeatus.BROADS1.cds.all.fa
    transcriptome_gtf: /scratch/general/pe-nfs1/u0806040/natalie/reference/Gasterosteus_aculeatus.BROADS1.102.gtf
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: Natalie_Steinel
  files:
    - /scratch/general/pe-nfs1/u0806040/natalie/sc_stickle/input/stickle_1.fq.gz
    - /scratch/general/pe-nfs1/u0806040/natalie/sc_stickle/input/stickle_2.fq.gz
  genome_build: hg38
  metadata: {}
fc_name: sc_stickle
upload:
  dir: /scratch/general/pe-nfs1/u0806040/natalie/sc_stickle/final
```

sample_barcodes.csv
```
CTCTCTAT,uninjected_1
TATCCTCT,alum_1
GTAAGGAG,npcgg_1
ACTGCATA,alum_2
AAGGAGTA,npcgg_2
CTAAGCCT,uninjected_2
CGTCTAAT,npcgg_3
TCTCTCCG,uninjected_3
TCGACTAG,alum_3
```

Input directory has 2 fastq.gz files (1 for R1 and and one for R2). Head of R1:
```
@A01061:44:HW3F2DRXX:1:1101:1298:1016 1:N:0:ATAGAGAG
ACTATACTGTGTCTCACCCTTAGTTTGGGGCGATGGCTGAACTTTGTGCATCTTTATGATTTTAAACGTTCCACATCCTCCTCCTA
+
FFFFFF,FFFFFFFFFFFF:FFFFF:F,FF:FF:F::FFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFF,FFFFFFF,FFFFFFF
@A01061:44:HW3F2DRXX:1:1101:1967:1016 1:N:0:ATAGAGAG
ACTTCTCCGGAATCGTTTGCGTCGCCGCACTGGGCGCCTCGCGGCGCCTGTCTCCGCCACTCCAGGTCCGGGAATCTGAACCCAGC
+
FFFFFFFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@A01061:44:HW3F2DRXX:1:1101:2148:1016 1:N:0:ATAGAGAG
AGCCACAAGCCAGTTATCCCTGTGGTAACTTTTCTGACACCTCCTGCTTAAAACCCAAAACGCCAGAAGGATCGTGAGGCCCCGCT
```
Thanks for your help,

Brian
