### ISSUE TITLE
NF fraction bam in ATAC seq has reads only from one strand

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#3398]
Hello everyone!

In a ATAA-seq run:
```
details:
- analysis: chip-seq
  genome_build: mm10
  algorithm:
    aligner: bwa
    quality_format: standard
    trim_reads: read_through
    adapters: [nextera, nextera2, polya]
    peakcaller: macs2
    chip_method: atac
    keep_duplicates: False
    keep_multimapped: False
  resources:
    macs2:
      options: ["-g mm"]
upload:
  dir: /project/results
```

sample-NF.bam has reads almost exclusively on one strand:
```bash
$ samtools view -F 16 sample-NF.bam | wc -l
5695995
$ samtools view -f 16 sample-NF.bam | wc -l
2596
```
while sample-ready.bam has them on both strands (35 mln/35mln).
Are we losing counts when creating the NF file? 

SN
