### ISSUE TITLE
pindel works?

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#3411]
Hi,
Could not find much documentation about pindel. Is the bcbio wrapper working for pindel? I don't see anything related to pindel in the log files.
Thanks!
Segun

**Comment by naumenko-sa** [comment]
Hi!

I was not able to run (mutect1/pindel) with the latest gatk3.x and java1.8 or 1.7 in bcbio1.2.5.

The configuration snippet should be:
```yaml
variantcaller: mutect
indelscaller: pindel
tools_off: gatk4
```
Have you tried installing an older version of gatk and run with java1.7 in PATH similar to #2861?

Sergey
