### ISSUE TITLE
bcbio v1.2.4 ChipSeq fills log file with millions of bedpe "marked as paired: skipping" warnings

### ISSUE THREAD

**Issue by mchimenti** [bcbio/bcbio-nextgen#3433]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.4
- OS name and version (`lsb_release -ds`): "CentOS Linux release 7.8.2003 (Core)"

**To Reproduce**
Exact bcbio command you have used:  
```
Here is the command that I believe is causing the warnings: 

/Dedicated/IIHG-argon/bcbio-1.2.4/galaxy/../anaconda/bin/bedtools bamtobed -bedpe -i /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/align/SW872_YAP5SA_rep1_input/SW872_YAP5SA_rep1_input-sort_chrom-noMito.nsorted.bam | awk 'BEGIN{OFS="\t"}{print $1,$2,$4,$6,$9,$10}' | sort | uniq -c | awk 'BEGIN{mt=0;m0=0;m1=0;m2=0}($1==1){m1=m1+1} ($1==2){m2=m2+1}{m0=m0+1}{mt=mt+$1} END{printf "%d,%d,%d,%d\n", mt,m0,m1,m2}' >> /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/bcbiotx/tmpd5td86f2/SW872_YAP5SA_rep1_input-atac-metrics.csv
```
**Your sample configuration file:**
```
details:
- algorithm:
    aligner: bwa
    antibody: narrow
    chip_method: chip
    peakcaller: macs2
    quality_format: standard
    trim_reads: atropos
  analysis: chip-seq
  description: SW872_CAMTA1_rep1_ChIP
  files:
  - /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/merged/SW872_CAMTA1_rep1_ChIP_R1.fastq.gz
  - /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/merged/SW872_CAMTA1_rep1_ChIP_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: camta1_rep1
    phenotype: chip
- algorithm:
    aligner: bwa
    antibody: narrow
    chip_method: chip
    peakcaller: macs2
    quality_format: standard
    trim_reads: atropos
  analysis: chip-seq
  description: SW872_CAMTA1_rep1_input
  files:
  - /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/merged/SW872_CAMTA1_rep1_input_R1.fastq.gz
  - /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/merged/SW872_CAMTA1_rep1_input_R2.fastq.gz
  genome_build: GRCh37
```

**Observed behavior**
Error message or bcbio output:
```
This message occurs _millions of times_ in the log file: 
*****WARNING: Query D00689:433:CDT3LANXX:8:1110:18082:60094#AGCCTATC is marked as paired, but its mate does not occur next to it in your BAM file. Skipping.
```

**Expected behavior**
I would expect that since the command is apparently calling a name-sorted BAM file, that 'bedpe' wouldn't throw this error.  

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/5929979/bcbio-nextgen-commands.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/5929980/bcbio-nextgen.log)

[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31693:4366 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31711:29825 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31729:20306 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31756:18975 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31846:32315 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:31955:21919 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32045:17159 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32072:3208 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32145:33332 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32253:5181 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32398:15765 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32425:4100 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32479:12305 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32633:24659 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32696:13996 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32696:14027 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32705:21559 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32759:11600 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32768:36918 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32796:25160 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32859:23359 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32877:3662 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:06Z] *****WARNING: Query A00876:127:H25WVDRXY:2:2278:32922:22373 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
[2021-02-05T03:08Z] Removing multimapped reads from /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/align/SW872_YAP5SA_rep1_input/SW872_YAP5SA_rep1_input-sort_chrom-noMito.bam.
[2021-02-05T03:08Z] sambamba 0.7.1
[2021-02-05T03:08Z]  by Artem Tarasov and Pjotr Prins (C) 2012-2019
[2021-02-05T03:08Z]     LDC 1.20.0 / DMD v2.090.1 / LLVM7.0.0 / bootstrap LDC - the LLVM D compiler (0.17.6)
[2021-02-05T03:10Z] Index BAM file: SW872_YAP5SA_rep1_input-sort_chrom-noMito.unique.bam
[2021-02-05T03:11Z] Removing duplicates from /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/align/SW872_YAP5SA_rep1_input/SW872_YAP5SA_rep1_input-sort_chrom-noMito.unique.bam, saving as /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/align/SW872_YAP5SA_rep1_input/SW872_YAP5SA_rep1_input-sort_chrom-noMito.unique-noduplicates.bam.
[2021-02-05T03:11Z] sambamba 0.7.1
[2021-02-05T03:11Z]  by Artem Tarasov and Pjotr Prins (C) 2012-2019
[2021-02-05T03:11Z]     LDC 1.20.0 / DMD v2.090.1 / LLVM7.0.0 / bootstrap LDC - the LLVM D compiler (0.17.6)
[2021-02-05T03:12Z] Index BAM file: SW872_YAP5SA_rep1_input-sort_chrom-noMito.unique-noduplicates.bam
[2021-02-05T03:13Z] Remove blacklist regions from /Shared/Bioinformatics/data/mchiment/tanas/project_chipseq_h3k27_feb2021/project/work/align/SW872_YAP5SA_rep1_input/SW872_YAP5SA_rep1_input-sort_chrom-noMito.unique-noduplicates.bam
**Additional context**
