### ISSUE TITLE
gatk-haplotype-joint 'File2TileDBBinaryException'

### ISSUE THREAD

**Issue by adammaikai** [bcbio/bcbio-nextgen#3442]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 16.04.7 LTS

**To Reproduce**
Exact bcbio command you have used:
```
cd $workspace &&  bcbio_nextgen.py \
	-w template $template_yaml \
	$metadata \
	$workspace/*vcf.gz \
	--workdir $workspace

bcbio_nextgen.py \
	$workspace/"${base_meta%.*}"/config/"${base_meta%.*}".yaml \
	-n 1 \
	--workdir $workspace
```
Your sample configuration file:
```
# Template for joint genotyping of gvcf inputs created with GATK
---
details:
  - analysis: variant2
    genome_build: hg38
    # to do multi-sample variant calling, assign samples the same metadata / batch
    algorithm:
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      exclude_regions: [altcontigs, highdepth, lcr]
      effects: vep
    resources:
      gatk-haplotype-joint:
        options: ["--genomicsdb-vcf-buffer-size 16384000"]
upload:
  dir: final
```

**Observed behavior**
Error message or bcbio output:
```
terminate called after throwing an instance of 'File2TileDBBinaryException'
  what():  File2TileDBBinaryException : read_one_line_fully && "Buffer did not have space to hold a line fully - increase buffer size"
Using GATK jar /shared/workspace/software/bcbio/anaconda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms681m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/shared/workspace/projects/tanaka/work/joint/gatk-haplotype-joint/tanaka_merged_germline/chr1/bcbiotx/tmpyzvi2nqr -jar /shared/workspace/software/bcbio/anaconda/share/gatk4-4.1.9.0-0/gatk-package-4.1.9.0-local.jar GenomicsDBImport --reader-threads 1 --genomicsdb-workspace-path tanaka_merged_germline-chr1_0_248956422_genomicsdb -L chr1:1-248956422 --sample-name-map /shared/workspace/projects/tanaka/work/bcbiotx/tmpia87xzkv/tmp267vb06i.tsv
' returned non-zero exit status 250.
```

**Expected behavior**
Adjusting parameters ```["--genomicsdb-vcf-buffer-size 16384000"]``` does not seem to affect the error I am getting. Maybe the parameters aren't being passed to the script? Is my config file improperly setup?
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6080198/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6080199/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6080200/bcbio-nextgen.log)

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**

**Comment by naumenko-sa** [comment]
Hi @adammaikai !

Thanks for the detailed report and sorry about the issue!
I think you have diagnosed it correctly:

GATK links
- https://github.com/broadinstitute/gatk/issues/6150
- https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2020-01-07-2019-07-10/24420-GenomicsDBImport-error-File2TileDBBinaryException

i.e. to fix it, we need to add an option ```--genomicsdb-vcf-buffer-size 16384000``` to `GenomicsDBImport` call.
I've added support of custom options for this command.

Please update to bcbio development:
```
bcbio_nextgen.py -u development
```

and try again by setting
```yaml
details
...
resources:
  GenomicsDBImport:
    options: ["--genomicsdb-vcf-buffer-size", "16384000"]
```

Please note the syntax: resources at the top level of the YAML, and options is a list.

#3448

Sergey
