### ISSUE TITLE
bcbio-prioritize error: java.lang.RuntimeException: EOF while reading string

### ISSUE THREAD

**Issue by chatchawit** [bcbio/bcbio-nextgen#3454]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 20.04.1 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio-prioritize -Xms750m -Xmx25480m known -i /san/test/wes-tn/work/structural/LU147-01/lumpy/LU147-11-LU147-svs-smoove.genotyped-duphold-filter-effects.vcf.gz -o /san/tmp/LU147-11-lumpy-prioritize.vcf.gz -k /san/bcbio/genomes/Hsapiens/hg38/coverage/prioritize/cancer/civic-2018-12-27.bed.gz
```
Your sample configuration file:
```
details:
- algorithm:
    aligner: bwa
    coverage_interval: regional
    exclude_regions: [lcr]
    hlacaller: optitype
    mark_duplicates: true
    min_allele_fraction: 2
    nomap_split_targets: 100
    remove_lcr: true
    recalibrate: false
    save_diskspace: true
    svcaller: [gatk-cnv, lumpy, manta]
    svprioritize: cancer/civic
    svvalidate:
      DEL: /san/data/dream-syn3-crossmap/truth_DEL.bed
      DUP: /san/data/dream-syn3-crossmap/truth_DUP.bed
      INV: /san/data/dream-syn3-crossmap/truth_INV.bed
    validate: /san/data/dream-syn3-crossmap/truth_small_variants.vcf.gz
    validate_regions: /san/data/dream-syn3-crossmap/truth_regions.bed
    variantcaller:
      somatic: [mutect2]
      germline: [gatk-haplotype]
    variant_regions: /san/data/lib/S07604624_Covered.bed
  analysis: variant2
  description: LU147-11
  files:
    - /san/data/fq/LU147-11_L4_1.fq.gz
    - /san/data/fq/LU147-11_L4_2.fq.gz
  genome_build: hg38
  metadata:
    batch: LU147
    phenotype: normal
- algorithm:
    aligner: bwa
    coverage_interval: regional
    exclude_regions: [lcr]
    hlacaller: optitype
    mark_duplicates: true
    min_allele_fraction: 2
    nomap_split_targets: 100
    remove_lcr: true
    recalibrate: false
    save_diskspace: true
    svcaller: [gatk-cnv, lumpy, manta]
    svprioritize: cancer/civic
    svvalidate:
      DEL: /san/data/dream-syn3-crossmap/truth_DEL.bed
      DUP: /san/data/dream-syn3-crossmap/truth_DUP.bed
      INV: /san/data/dream-syn3-crossmap/truth_INV.bed
    validate: /san/data/dream-syn3-crossmap/truth_small_variants.vcf.gz
    validate_regions: /san/data/dream-syn3-crossmap/truth_regions.bed
    variantcaller:
      somatic: [mutect2]
      germline: [gatk-haplotype]
    variant_regions: /san/data/lib/S07604624_Covered.bed
  analysis: variant2
  description: LU147-01
  files:
    - /san/data/fq/LU147-01_L1_1.fq.gz
    - /san/data/fq/LU147-01_L1_2.fq.gz
  genome_build: hg38
  metadata:
    batch: LU147
    phenotype: tumor
upload:
  dir: /san/test/wes-tn/final
```

**Observed behavior**
Error message or bcbio output:
```
2021-04-02 14:07:03 bioinformatics ERROR [bcbio.prioritize.main] -
                   bcbio.prioritize.main.main
                                          ...
                  bcbio.prioritize.main/-main       main.clj:   35
               bcbio.prioritize.main/-main/fn       main.clj:   36
                           clojure.core/apply       core.clj:  630
                                          ...
                 bcbio.prioritize.known/-main      known.clj:  236
            bcbio.prioritize.known/prioritize      known.clj:  206
                                          ...
                    bcbio.prioritize.known/fn      known.clj:  188
      bcbio.prioritize.known/parse-intersects      known.clj:  161
                            clojure.core/into       core.clj: 6600
                          clojure.core/reduce       core.clj: 6519
                  clojure.core.protocols/fn/G  protocols.clj:   13
                    clojure.core.protocols/fn  protocols.clj:  101
            clojure.core.protocols/seq-reduce  protocols.clj:   30
                             clojure.core/seq       core.clj:  137
                                          ...
                          clojure.core/map/fn       core.clj: 2624
          bcbio.prioritize.known/combine-hits      known.clj:  123
                          clojure.core/reduce       core.clj: 6519
                  clojure.core.protocols/fn/G  protocols.clj:   13
                    clojure.core.protocols/fn  protocols.clj:  101
            clojure.core.protocols/seq-reduce  protocols.clj:   30
                             clojure.core/seq       core.clj:  137
                                          ...
                          clojure.core/map/fn       core.clj: 2616
                             clojure.core/seq       core.clj:  137
                                          ...
                          clojure.core/map/fn       core.clj: 2624
       bcbio.prioritize.known/combine-hits/fn      known.clj:  121
bcbio.prioritize.known/combine-hits/parse-hit      known.clj:  101
                      clojure.edn/read-string        edn.clj:   45
                      clojure.edn/read-string        edn.clj:   46
                                          ...
java.lang.RuntimeException: EOF while reading string
```

**Expected behavior**

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
My aim is to run the Workflow1 - T/N.

[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6249883/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6249884/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6249885/bcbio-nextgen-commands.log)
