### ISSUE TITLE
Your example's launching error

### ISSUE THREAD

**Issue by NstVasileva** [bcbio/bcbio-nextgen#3474]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.5 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/cancer-dream-syn3.yaml -n 8
```
Your sample configuration file:
```
# Cancer tumor/normal calling evaluation using synthetic dataset 3
# from the ICGC-TCGA DREAM challenge:
# https://www.synapse.org/#!Synapse:syn312572/wiki/62018
---
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    remove_lcr: true
    variantcaller: vardict
    variant_regions: ../input/NGv3.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  analysis: variant2
  description: syn3-normal
  #files: ../input/synthetic.challenge.set3.normal.bam
  files:
    - ../input/synthetic_challenge_set3_normal_NGv3_1.fq.gz
    - ../input/synthetic_challenge_set3_normal_NGv3_2.fq.gz
  genome_build: hg38
  metadata:
    batch: syn3
    phenotype: normal
- algorithm:
    aligner: bwa
    mark_duplicates: true
    remove_lcr: true
    variantcaller: vardict
    variant_regions: ../input/NGv3.bed
    validate: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth.vcf.gz
    validate_regions: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_regions.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  #   svvalidate:
  #     DEL: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DEL.bed
  #     DUP: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_DUP.bed
  #     INS: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INS.bed
  #     INV: ../input/synthetic_challenge_set3_tumor_20pctmasked_truth_sv_INV.bed
  analysis: variant2
  description: syn3-tumor
  #files: ../input/synthetic.challenge.set3.tumor.bam
  files:
    - ../input/synthetic_challenge_set3_tumor_NGv3_1.fq.gz
    - ../input/synthetic_challenge_set3_tumor_NGv3_2.fq.gz
  genome_build: hg38
  metadata:
    batch: syn3
    phenotype: tumor
upload:
  dir: ../final
```

**Observed behavior**
Error message or bcbio output:
```
 File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/variation/bedutils.py", line 52, in check_bed_contigs
    "This is typically due to chr1 versus 1 differences in BED file and reference.")
ValueError: Contigs in BED file /mnt/biodata/cancer-dream-syn3/input/NGv3.bed not in reference genome:
 ['X', 'Y', '20', '22', '5', '16', '1', '18', '7', '12', '2', '4', '13', '8', '17', '14', '9', '21', '6', '3', '15', '11', '19', '10']
This is typically due to chr1 versus 1 differences in BED file and reference.
```

**Expected behavior**
As it's command from your example's launching - i expected that everything will be okay. https://bcbio-nextgen.readthedocs.io/en/latest/contents/somatic_variants.html  (workflow1)

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6335341/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6335342/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/6335343/bcbio-nextgen-debug.log)

**Additional context**
