### ISSUE TITLE
Small germline variants example doesn't work

### ISSUE THREAD

**Issue by NstVasileva** [bcbio/bcbio-nextgen#3479]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.8
- OS name and version (`lsb_release -ds`): Ubuntu 18.04.5 LTS

**To Reproduce**
Exact bcbio command you have used:
```
 bcbio_nextgen.py ../config/NA12878.yaml -n 8
```
Your sample configuration file: NA12878.yaml
```
details:
  - files:
    - /mnt/biodata/validate_giab/input/NA12878_1.fq.gz
    - /mnt/biodata/validate_giab/input/NA12878_2.fq.gz
    description: NA12878
    metadata:
      sex: female
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      variantcaller: gatk-haplotype
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: giab-NA12878/truth_regions.bed
      variant_regions: /mnt/biodata/validate_giab/input/nexterarapidcapture_expandedexome_targetedregions.hg38.bed
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 8G
upload:
  dir: ../final

```

**Observed behavior**
Error message or bcbio output:

```
Command 'set -o pipefail; gunzip -c /mnt/biodata/validate_giab/input/NA12878_1.fq.gz | /usr/local/share/bcbio-nextgen/anaconda/bin/bgzip --threads 3 -c /dev/stdin > /mnt/biodat                       a/validate_giab/work/bcbiotx/tmpkymjub7a/NA12878_1.fq.gz
gzip: /mnt/biodata/validate_giab/input/NA12878_1.fq.gz: invalid compressed data--format violated
' returned non-zero exit status 1.
```

```bash
gunzip -c /mnt/biodata/validate_giab/input/NA12878_1.fq.gz | 
/usr/local/share/bcbio-nextgen/anaconda/bin/bgzip --threads 3 -c /dev/stdin > \
/mnt/biodata/validate_giab/work/bcbiotx/tmpkymjub7a/NA12878_1.fq.gz
gzip: /mnt/biodata/validate_giab/input/NA12878_1.fq.gz: invalid compressed data--format violated
```

**Expected behavior**
Workflow1: validate hg38 calls -------> doesn't work

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

**Additional context**
