### ISSUE TITLE
Recommendations for tumor-only variant calling

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3504]
Hi everyone,

I have some **Tumor only Illumina data** in my possession and I want to call **both Somatic and Germline variants**. 
My usecase is to detect ALL Somatic and Germline variants of a Tumor only exome sample.

I have some questions:

1. Does Mutect2 detect BOTH Somatic and Germline and just tag Somatic variants with "SOMATIC" in the end? Or do I have to run also HaplotypeCaller to detect all Germline Variants from my Tumor-only exome sample?

2. I want to achieve the highest RECALL. This is my goal and not Precision. Are there any options I have to use to disable any filtering done to the final set of variants?

3. If I follow the Somatic variant calling user story what should I specify in the yaml file to call both Germline and Somatic variants?

 ```
variantcaller:
   somatic: [vardict, strelka2, mutect2]
   germline: [freebayes, gatk-haplotype, strelka2]
ensemble:
   numpass: 2
```
or 
```
variantcaller: [mutect2, vardict]
```
Does the first configuration (specifying both somatic and germline callers) work fow tumor only? In the user story it says "For tumor/normal somatic samples, bcbio can call both somatic (tumor-specific) and germline (pre-existing) variants." but I want to clarify it.

EDIT: I get the message "ValueError: MuTect, MuTect2 and Strelka2 somatic calling requires normal sample or panel" when I try to run the following config yaml with tumor only bam. So I guess Mutect does not support tumor only without panel.

```
---
details:
- algorithm:
    aligner: false
    mark_duplicates: false
    maxcov_downsample: false
    min_allele_fraction: 1
    realign: false
    recalibrate: false
    remove_lcr: false
    effects: snpeff
    tools_off: [collectsequencingartifacts, tumoronly-prioritization, vardict_somatic_filter, contamination]
    tools_on: [noalt_calling] 
    background: /media/kokyriakidis/PRODUCTION/Mutect2-exome-panel.vcf
    variantcaller:
    - mutect2
    - vardict 
    - freebayes
    - gatk-haplotype
    use_lowfreq_filter: false
    ensemble:
      numpass: 1
      use_filtered: true
    variant_regions: /media/kokyriakidis/PRODUCTION/B/config/Sureselect.v6.refseq.ensembl.noUTR.notfound.targetbp.hg19.bed 
  analysis: variant2
  files:
    - /media/kokyriakidis/PRODUCTION/B/input/B.bam
  genome_build: hg19
  description: B
  metadata:
    batch: Bs
    phenotype: tumor
upload:
  dir: ../final
```

Thank you for your time,
KK
