### ISSUE TITLE
error_sex_check on true with variant calling GVCF output

### ISSUE THREAD

**Issue by JenkoB** [bcbio/bcbio-nextgen#3506]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.7
- OS name and version (`lsb_release -ds`): Ubuntu 18.04

Your sample configuration file: 
```
details:
- algorithm:
    aligner: bwa
    archive: cram-lossless
    recalibrate: gatk
    tools_on:
    - gvcf
    variant_regions: /beds/xgen-exome-research-panel-v2-targets-GRCh37-50-flanking.bed
    variantcaller:
    - gatk-haplotype
  analysis: variant2
  description: 0591
  files:
  - /home/user/Analysis/test_bcbio/fastq/0591_R1.fastq.gz
  - /home/user/Analysis/test_bcbio/fastq/0591_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 0591_1
    phenotype: unknown
    sex: female

```

**Observed behavior**
There is missing Sex column in multiqc_report.html under General statistic part. How can we change configuration file, that we would be able to see sex column in multiqc_report, even when having GVCF output?

 When we have the same configuration file, only without;
 `   tools_on:
    - gvcf
`
we are able to see Sex column in multiqc_report.

Additionally, we have a question how can we set `error_sex_check: false` from false to true in multiqc_config.yaml file? 
Or where can we define that we wish to have sex check in multi qc report? 

**Expected behavior**
Having an error sex check in multiqc_report also when having GVCF as output.

Thank you,

Barbara Jenko Bizjan
