### ISSUE TITLE
ensemble calling issue

### ISSUE THREAD

**Issue by halimaach** [bcbio/bcbio-nextgen#3511]
Hi,
I am getting an error when the ensemble calling starts. I have tried to fix it by changing to 
ensemble:
  numpass: 2 
according to a previous issue. But it didn't work. 

[2021-07-19T07:03Z] multiprocessing: calculate_sv_bins
[2021-07-19T07:03Z] multiprocessing: calculate_sv_coverage
[2021-07-19T07:03Z] multiprocessing: normalize_sv_coverage
[2021-07-19T07:03Z] Timing: hla typing
[2021-07-19T07:03Z] Resource requests: freebayes, gatk, gatk-haplotype, picard, vardict; memory: 4.00, 4.00, 4.00, 4.00, 4.00; cores: 16, 16, 16, 16, 16
[2021-07-19T07:03Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-07-19T07:03Z] Timing: alignment post-processing
[2021-07-19T07:03Z] multiprocessing: piped_bamprep
[2021-07-19T07:03Z] Timing: variant calling
[2021-07-19T07:03Z] multiprocessing: variantcall_sample
[2021-07-19T07:03Z] multiprocessing: concat_variant_files
[2021-07-19T07:03Z] Timing: joint squaring off/backfilling
[2021-07-19T07:03Z] Resource requests: bcbio_variation, fastqc, gatk, gemini, kraken, preseq, qsignature, sambamba, samtools, snpeff; memory: 4.00, 4.00, 4.00, 4.00, 4.00, 4.00, 4.00, 4.00, 4.00, 3.00; cores: 16, 16, 16, 16, 16, 16, 16, 16, 16, 1
[2021-07-19T07:03Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2021-07-19T07:03Z] Timing: variant post-processing
[2021-07-19T07:03Z] multiprocessing: postprocess_variants
[2021-07-19T07:03Z] Finalizing variant calls: Herz2, freebayes
[2021-07-19T07:03Z] Calculating variation effects for Herz2, freebayes
[2021-07-19T07:03Z] Annotate VCF file: Herz2, freebayes
[2021-07-19T07:03Z] Filtering for Herz2, freebayes
[2021-07-19T07:03Z] Prioritization for Herz2, freebayes
[2021-07-19T07:03Z] Germline extraction for Herz2, freebayes
[2021-07-19T07:03Z] Finalizing variant calls: Herz2, gatk-haplotype
[2021-07-19T07:03Z] Calculating variation effects for Herz2, gatk-haplotype
[2021-07-19T07:03Z] Annotate VCF file: Herz2, gatk-haplotype
[2021-07-19T07:03Z] Filtering for Herz2, gatk-haplotype
[2021-07-19T07:03Z] Removing variants with missing alts from /home/uni08/alachram/project/work/gatk-haplotype/Herz2-effects.vcf.gz.
[2021-07-19T07:03Z] Prioritization for Herz2, gatk-haplotype
[2021-07-19T07:03Z] Germline extraction for Herz2, gatk-haplotype
[2021-07-19T07:03Z] Finalizing variant calls: Herz2, vardict
[2021-07-19T07:03Z] Calculating variation effects for Herz2, vardict
[2021-07-19T07:03Z] Annotate VCF file: Herz2, vardict
[2021-07-19T07:03Z] Filtering for Herz2, vardict
[2021-07-19T07:03Z] Prioritization for Herz2, vardict
[2021-07-19T07:03Z] Germline extraction for Herz2, vardict
[2021-07-19T07:03Z] multiprocessing: split_variants_by_sample
[2021-07-19T07:03Z] Timing: prepped BAM merging
[2021-07-19T07:03Z] Timing: validation
[2021-07-19T07:03Z] multiprocessing: compare_to_rm
[2021-07-19T07:03Z] Timing: ensemble calling
[2021-07-19T07:03Z] multiprocessing: combine_calls
[2021-07-19T07:03Z] Ensemble consensus calls for Herz2: freebayes,gatk-haplotype,vardict
[2021-07-19T07:03Z] Ensemble calling: Herz2
[2021-07-19T07:03Z] Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: For input string: "R", for input source: /home/uni08/alachram/project/work/ensemble/Herz2/freebayes/Herz2-effects-filter-annotated-somatic-priority-noeff-nomultiallelic_tumorOnly_noFilteredCalls.vcf.gz
[2021-07-19T07:03Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:75)
[2021-07-19T07:03Z] 	at htsjdk.tribble.TabixFeatureReader.<init>(TabixFeatureReader.java:59)
[2021-07-19T07:03Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:85)
[2021-07-19T07:03Z] 	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:66)
[2021-07-19T07:03Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-07-19T07:03Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[2021-07-19T07:03Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-07-19T07:03Z] 	at java.lang.reflect.Method.invoke(Method.java:607)
[2021-07-19T07:03Z] 	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
[2021-07-19T07:03Z] 	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
[2021-07-19T07:03Z] 	at bcbio.variation.variantcontext$get_vcf_header.invoke(variantcontext.clj:144)
[2021-07-19T07:03Z] 	at bcbio.variation.variantcontext$get_samples.invoke(variantcontext.clj:150)
[2021-07-19T07:03Z] 	at bcbio.variation.vcfsample$consistent_order.invoke(vcfsample.clj:108)
[2021-07-19T07:03Z] 	at bcbio.variation.ensemble$consensus_calls.invoke(ensemble.clj:109)
[2021-07-19T07:03Z] 	at bcbio.variation.ensemble$_main.doInvoke(ensemble.clj:132)
[2021-07-19T07:03Z] 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2021-07-19T07:03Z] 	at clojure.core$apply.invoke(core.clj:630)
[2021-07-19T07:03Z] 	at bcbio.variation.core$_main.doInvoke(core.clj:35)
[2021-07-19T07:03Z] 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
[2021-07-19T07:03Z] 	at bcbio.variation.core.main(Unknown Source)
[2021-07-19T07:03Z] Caused by: java.lang.NumberFormatException: For input string: "R"
[2021-07-19T07:03Z] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[2021-07-19T07:03Z] 	at java.lang.Integer.parseInt(Integer.java:491)
[2021-07-19T07:03Z] 	at java.lang.Integer.valueOf(Integer.java:581)
[2021-07-19T07:03Z] 	at htsjdk.variant.vcf.VCFCompoundHeaderLine.<init>(VCFCompoundHeaderLine.java:171)
[2021-07-19T07:03Z] 	at htsjdk.variant.vcf.VCFFormatHeaderLine.<init>(VCFFormatHeaderLine.java:49)
[2021-07-19T07:03Z] 	at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:211)
[2021-07-19T07:03Z] 	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
[2021-07-19T07:03Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:88)
[2021-07-19T07:03Z] 	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:41)
[2021-07-19T07:03Z] 	at htsjdk.tribble.TabixFeatureReader.readHeader(TabixFeatureReader.java:73)
[2021-07-19T07:03Z] 	... 19 more
[2021-07-19T07:03Z] Uncaught exception occurred

**Comment by naumenko-sa** [comment]
Hi @halimaach !

Could you please provide the full yaml config file or link to the 'previous issue'?

Sergey

**Comment by halimaach** [comment]
Hi @naumenko-sa,


Here is the full yaml config file content I used:

---
details:
  - files: [/home/uni08/alachram/project/input/Herz2.recal.bam]
    lane: Herz2
    description: Herz2
    analysis: variant2
    genome_build: hg19
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: false
      recalibrate: false
      realign: false
      variantcaller: [freebayes, gatk-haplotype, vardict]
      ensemble:
        numpass: 2
        format-filters: [DP < 4]
        classifiers: 
          balance: [AD, FS, Entropy]
          calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        classifier-params:
          type: svm
        trusted-pct: 0.65     
      # for targetted projects, set the region
      variant_regions: /home/uni08/alachram/project/input/final.bed
    metadata:
        phenotype: tumor


And here is the link to the previous issue:
https://github.com/bcbio/bcbio-nextgen/issues/1535


I actually retried the analysis with this yaml config file content shown below and it worked but I didn't get variants from ensemble calls:

---
details:
- files:
    - /home/uni08/alachram/project/input/Herz2.recal.bam
  genome_build: hg19
  description: Herz2
  analysis: variant2
  algorithm:
    aligner: false
    mark_duplicates: false
    maxcov_downsample: false
    min_allele_fraction: 1
    realign: false
    recalibrate: false
    remove_lcr: false
    effects: snpeff
    tools_off: [collectsequencingartifacts, tumoronly-prioritization, vardict_somatic_filter, contamination]
    tools_on: [noalt_calling] 
    variantcaller: [freebayes, gatk-haplotype, vardict]
    use_lowfreq_filter: false
    ensemble:
      numpass: 1
      use_filtered: true
    variant_regions: /home/uni08/alachram/project/input/final.bed
  metadata:
    batch: Bs
    phenotype: tumor


Thanks for your help,
Halima

**Comment by halimaach** [comment]
Hi @naumenko-sa ,

Here is the full yaml config file I used

```yml

---
details:
  - files: [/home/uni08/alachram/project/input/Herz2.recal.bam]
    lane: Herz2
    description: Herz2
    analysis: variant2
    genome_build: hg19
    algorithm:
      aligner: false
      recalibrate: false
      realign: false
      variantcaller: [freebayes, gatk-haplotype, vardict]
      ensemble:
        numpass: 2
        format-filters: [DP < 4]
        classifiers: 
          balance: [AD, FS, Entropy]
          calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        classifier-params:
          type: svm
        trusted-pct: 0.65     
      variant_regions: /home/uni08/alachram/project/input/final.bed
    metadata:
        phenotype: tumor
```

And here is the link to the previous issue:
https://github.com/bcbio/bcbio-nextgen/issues/1535

Thanks
Halima

**Comment by naumenko-sa** [comment]
Hi @halimaach Halima!

Thanks for clarifying! 

The last config worked for me with:
```
- bcbio1.2.8
- hg38 reference
- freebayes,1.3.2
- vardict-java,1.8.2
- gatk4,4.2.0.0
```

I've got the following amounts of variants:
```
ensemble: 2515
freebayes: 576
gatk-haplotype: 551
vardict: 2414
```

Ensemble vcf is a union with numpass:1 and the majority of the variants are coming from vardict.

What are the versions you are running?

The first version of the config:
```yaml
ensemble:
  numpass: 2
  format-filters: [DP < 4]
  classifiers: 
    balance: [AD, FS, Entropy]
    calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
    classifier-params:
      type: svm
    trusted-pct: 0.65   
```
could be problematic since, to my knowledge, nobody touched the classifier aspect in a while,
people used just a simpler voting approach which showed good performance and is very intuitive to use
(high numpass increases precision, low pass for high specificity).

Sergey

**Comment by halimaach** [comment]
Hi @naumenko-sa Sergey,

I have used the last config with numpass: 2 and with the following versions

```yml

- bcbio1.2.8
- hg19 reference
- freebayes,1.3.2
- vardict-java,1.8.2
- gatk4,4.2.0.0

```
It worked properly with no errors.
I have also added Mutect2 with a panel of normal and the config below. However, I didn't notice any variant from Mutect2 in the ensemble calls? Usually are Mutect2 calls also considered into the ensemble analysis?


```yml
details:
- files:
    - /home/uni08/alachram/ASIV/input/Herz10.recal.bam
  genome_build: hg19
  description: Herz2
  analysis: variant2
  algorithm:
    aligner: false
    mark_duplicates: false
    maxcov_downsample: false
    min_allele_fraction: 0.01
    realign: false
    recalibrate: false
    remove_lcr: false
    #effects: snpeff
    tools_off: [collectsequencingartifacts, tumoronly-prioritization, vardict_somatic_filter, contamination]
    tools_on: [svplots] 
    background: /home/uni08/alachram/project/input/pon.vcf.gz
    variantcaller: [mutect2, freebayes, gatk-haplotype, vardict]
    use_lowfreq_filter: false
    ensemble:
      numpass: 2
      use_filtered: true
    variant_regions: /home/uni08/alachram/project/input/final.bed
  metadata:
    batch: Bs
    phenotype: tumor

```
Moreover, is it possible to get the amounts of variants from each caller in the pipeline?

Thanks for your help
Halima
