### ISSUE TITLE
crash after process that cleans-up & merges octopus thread outputs looks for a vcf that isn't there

### ISSUE THREAD

**Issue by mjsduncan** [bcbio/bcbio-nextgen#3513]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):  1.2.9a
- OS name and version (`lsb_release -ds`):  Ubuntu 20.10

**To Reproduce**
Exact bcbio command you have used:  
```
bcbio_nextgen.py ../config/psi13.yaml -n 8
```
Your sample configuration file:
```
fc_date: '070221'
fc_name: psi13
upload:
  dir: ../final
globals:
  regions: /home/mozi/biosrc/bcbio/genomes/Hsapiens/hg38/coverage/capture_regions/Exome-Agilent_V6.bed
details:
  - files:
    - ../input/SA01-ready.bam
    description: SA01
    metadata:
      sex: female
      batch: batch
    analysis: variant2
    genome_build: hg38
    algorithm:
      trim_reads: false
      aligner: false
      recalibrate: false
      variantcaller: [octopus, freebayes, gatk-haplotype]
      variant_regions: regions
      ensemble:
        numpass: 2
      svcaller: [cnvkit, lumpy, manta]
      effects: false
      save_diskspace: true
      remove_lcr: true
      tools_off: gemini
      tools_on: [lumpy_usecnv, svplots]

... [x 24 more samples]
```

**Observed behavior**
Error message or bcbio output:
```
subprocess.CalledProcessError: Command 'set -o pipefail; zcat /mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp1wrqhze2/batch-chrY_57082054_57227415.legacy.vcf.gz | sed 's/fileformat=VCFv4.3/fileformat=VCFv4.2/' | sed 's/,\*\([A-Z]\)/,\1/' | sed 's/ID=PS,Number=1,Type=String/ID=PS,Number=1,Type=Integer/' | grep -v ^##contig | bcftools annotate -h /mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp1wrqhze2/batch-chrY_57082054_57227415-contig_header.txt | bgzip -c > /mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp1wrqhze2/batch-chrY_57082054_57227415.vcf.gz
gzip: /mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp1wrqhze2/batch-chrY_57082054_57227415.legacy.vcf.gz: No such file or directory
Failed to open -: unknown file type
' returned non-zero exit status 255.
```

**Expected behavior**
no errors & production of final outputs

**Log files**
Please attach (10MB max): `bcbio-nextgen.log`, `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen.log](https://github.com/bcbio/bcbio-nextgen/files/6850496/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/6850497/bcbio-nextgen-commands.log)

**Additional context**

the tail of the debug log file (21.3Mb) doesn't give any indication of errors, with final messages from the middle of threads:
```
$ tail work/log/bcbio-nextgen-debug.log 
[2021-07-14T13:17Z] [2021-07-14 09:17:50] <INFO>               -             100%           6m 52s                 -
[2021-07-14T13:17Z] [2021-07-14 09:17:50] <INFO> Finished calling 859,998bp, total runtime 2d 6h
[2021-07-14T13:17Z] [2021-07-14 09:17:50] <INFO> Calls have been written to "/mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp6pn8o36y/batch-chr19_48446056_58617616.vcf.gz"
[2021-07-14T13:17Z] 09:17:50.614 INFO  ProgressMeter -        chr19:4247046            147.3                  3250             22.1
[2021-07-14T13:17Z] 09:17:51.215 INFO  ProgressMeter -       chr20:48645815              1.5                    40             26.7
[2021-07-14T13:17Z] [2021-07-14 09:17:51] <INFO> Legacy VCF file written to "/mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp6pn8o36y/batch-chr19_48446056_58617616.legacy.vcf.gz"
```
but all the regions seem to be processed...
```
$ ls work/octopus/chr20/
batch-chr20_0_16243359-regions.bed
batch-chr20_0_16243359-regions-nolcr.bed
batch-chr20_0_16243359.vcf.gz
batch-chr20_0_16243359.vcf.gz.tbi
batch-chr20_16273268_32366516-regions.bed
batch-chr20_16273268_32366516-regions-nolcr.bed
batch-chr20_16273268_32366516.vcf.gz
batch-chr20_16273268_32366516.vcf.gz.tbi
batch-chr20_32367663_48626111-regions.bed
batch-chr20_32367663_48626111-regions-nolcr.bed
batch-chr20_32367663_48626111.vcf.gz
batch-chr20_32367663_48626111.vcf.gz.tbi
batch-chr20_48627515_64444167-regions.bed
batch-chr20_48627515_64444167-regions-nolcr.bed
batch-chr20_48627515_64444167.vcf.gz
batch-chr20_48627515_64444167.vcf.gz.tbi

$ ls work/octopus/
chr1                     chr17_KI270909v1_alt    chr3
chr10                    chr18                   chr4
chr11                    chr19                   chr4_GL000008v2_random
chr12                    chr19_KI270938v1_alt    chr5
chr13                    chr1_KI270706v1_random  chr6
chr14                    chr1_KI270711v1_random  chr7
chr14_GL000009v2_random  chr1_KI270766v1_alt     chr7_KI270803v1_alt
chr14_KI270846v1_alt     chr2                    chr8
chr15                    chr20                   chr8_KI270821v1_alt
chr15_KI270850v1_alt     chr21                   chr9
chr16                    chr22                   chrUn_KI270742v1
chr17                    chr22_KI270879v1_alt    chrX
chr17_KI270857v1_alt     chr22_KI270928v1_alt    chrY
```
and the crash happened when the clean-up process tried to access a vcf that was never made because the bed file was empty after filtering for low complexity regions?

**gzip: /mnt/sdb2/home/mozi/psi13/work/bcbiotx/tmp1wrqhze2/batch-chrY_57082054_57227415.legacy.vcf.gz: No such file or directory**

```
$ ll work/octopus/chrY/
total 116
drwxrwxr-x  2 mozi mozi  4096 Jul 14 20:21 ./
drwxrwxr-x 41 mozi mozi  4096 Jul 14 20:22 ../
-rw-rw-r--  1 mozi mozi 10832 Jul  4 00:36 batch-chrY_0_16618816-regions.bed
-rw-rw-r--  1 mozi mozi  8301 Jul  4 00:36 batch-chrY_0_16618816-regions-nolcr.bed
-rw-rw-r--  1 mozi mozi 27516 Jul  4 05:25 batch-chrY_0_16618816.vcf.gz
-rw-rw-r--  1 mozi mozi   297 Jul  4 05:25 batch-chrY_0_16618816.vcf.gz.tbi
-rw-rw-r--  1 mozi mozi  8073 Jul  3 05:43 batch-chrY_17578139_57076143-regions.bed
-rw-rw-r--  1 mozi mozi  8257 Jul  3 05:43 batch-chrY_17578139_57076143-regions-nolcr.bed
-rw-rw-r--  1 mozi mozi 20867 Jul  3 05:44 batch-chrY_17578139_57076143.vcf.gz
-rw-rw-r--  1 mozi mozi   156 Jul  3 05:44 batch-chrY_17578139_57076143.vcf.gz.tbi
-rw-rw-r--  1 mozi mozi   552 Jul 13 03:31 batch-chrY_57082054_57227415-regions.bed
==>  -rw-rw-r--  1 mozi mozi     0 Jul 13 03:31 batch-chrY_57082054_57227415-regions-nolcr.bed
```
the temp directory of the missing file was also missing after the crash:
```
$ ls work/bcbiotx/
tmp0robabsg  tmp8ukh8yej  tmpe8f5s1q7  tmphjzq2ati  tmprrw1ygr9  tmpwddveflc
tmp12bh_w9s  tmpas8ryj59  tmpel5f17j4  tmplmyc8iyp  tmptiju7hth  tmpy3khjdsa
tmp4jqmqir3  tmpbamb2kse  tmpgle47ymw  tmpoq_pvp7h  tmpurw1jci4  tmpye7atmrw
tmp4ngciykn  tmpdzii0q73  tmph4djxn9b  tmpp_o2jud5  tmpuwz7obtk  tmpytz_n9jy
```
... so my best guess is that an empty bed file was created after filtering for low complexity regions that eventually resulted in expected files that didn't exist...
