### ISSUE TITLE
Samtools variant call error

### ISSUE THREAD

**Issue by sysbiocoder** [bcbio/bcbio-nextgen#3525]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/calling.yaml -n 36

```
Your sample configuration file:
```
upload:
  dir: ../final
details:
  - files: [NA12878_S14_R1_001.fastq.gz, NA12878_S14_R2_001.fastq.gz]
    description: NA12878
    metadata:
      sex: female
      batch: batch1
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      tools_on: true
      mark_duplicates: true
      variantcaller: [samtools]    
      remove_lcr: true
      quality_format: Standard
      coverage_interval: regional
      recalibrate: false
      merge_bamprep: true
      variant_regions: Exome_plus_RefSeq_Gencode_targets_hg38_plus10.bed
      clinical_reporting: true
```

**Observed behavior**
Error message or bcbio output:
```

```/opt/bcbio/stable/anaconda/bin/bcftools mpileup -f /opt/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa -d 8000 -a DP -a AD -R /home/hg3810bp/config/samtools/chrY/batch1-chrY_57082132_57227415-regions-nolcr.bed /home/hg3810bp/config/align/NA12878/NA12878-sort.bam | /opt/bcbio/stable/anaconda/bin/bcftools call -v -m - | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } \
 {print}' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $5) } {print}' | vt normalize -n -q -r /opt/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa - | sed 's/VCFv4.2/VCFv4.1/' | \
 sed 's/,Version=3>/>/' | sed 's/,Version="3">/>/' | sed 's/Number=R/Number=./' | bgzip -c > /home/hg3810bp/config/bcbiotx/tmpvbk7wqdr/batch1-chrY_57082132_57227415.vcf.gz


Failed to open -: unknown file type
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
```

**Expected behavior**

**Log files**
[bcbio-nextgen.log.issue3525.txt](https://github.com/bcbio/bcbio-nextgen/files/7108052/bcbio-nextgen.log.issue3525.txt)
