### ISSUE TITLE
multiprocessing hangs at calc_callable_loci

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#36]
Test system: Debian Wheezy 
bcbio-nextgen version: git
Setup: 12 8-core VMs clustered using SGE

I tested the pipeline with one MiSeq run from our laboratory, and it hangs on the calc_callable_loci step.

Command line:

```
IPYTHONDIR=/mnt/data/software/ipython bcbio_nextgen.py -s sge -q main.q -t ipython -n 96 /mnt/data/references/bcbio_system.yaml ../config/project1.yaml
```

(`main.q` is my queue)

This is what the log says

```
[2013-07-04 14:35] MN-07: Combining fastq and BAM files ('', 'Sample_mysample')
[2013-07-04 14:36] MN-07: multiprocessing: calc_callable_loci
```

(MN-07 is one of our nodes)

pstree on the node itself shows

```
job_starter.sh(20704)───python(20705)─┬─java(20756)
                                      ├─python(20775)─┬─java(24104)
                                      │               └─{python}(21046)
                                      ├─python(20776)─┬─java(24118)
                                      │               └─{python}(20998)
                                      ├─python(20777)───{python}(20931)
                                      ├─python(20778)─┬─java(24047)
                                      │               └─{python}(21031)
                                      ├─python(20779)─┬─java(24028)
                                      │               └─{python}(20964)
                                      ├─python(20780)─┬─java(24085)
                                      │               └─{python}(21045)
                                      ├─python(20781)─┬─java(24066)
                                      │               └─{python}(20970)
                                      ├─python(20782)─┬─java(24002)
                                      │               └─{python}(20948)
                                      ├─{python}(20710)
                                      ├─{python}(20711)
                                      ├─{python}(20712)
                                      ├─{python}(20713)
                                      ├─{python}(20714)
                                      ├─{python}(20783)
                                      └─{python}(20784)
```

All the java processes are zombie processes.

Current project definition:

```
details:
- algorithm:
    aligner: bwa
    coverage_depth: high
    coverage_interval: regional
    mark_duplicates: false
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk
    trim_reads: false
    write_summary: true
  analysis: variant2
  lane: 1
  description: Sample_mysample
  variant_regions: /mnt/data/projects/miSeq/regions/miSeq.bed
  metadata:
      batch: Batch1
  files:
  - /mnt/data/projects/miSeq/raw_data/Sample_mysample_R1.fastq.gz
  - /mnt/data/projects/miSeq/raw_data/Sample_mysample_R2.fastq.gz
  genome_build: hg19
- algorithm:
    aligner: bwa
    coverage_depth: high
    coverage_interval: regional
    mark_duplicates: false
    platform: illumina
    quality_format: Standard
    realign: gatk
    recalibrate: gatk
    variantcaller: gatk
    trim_reads: false
    write_summary: true
  analysis: variant2
  lane: 2
  description: Sample_mysample2
  metadata:
      batch: Batch1
  files:
  - /mnt/data/projects/miSeq/raw_data/Sample_mysample2_R1.fastq.gz
  - /mnt/data/projects/miSeq/raw_data/Sample_mysample2_R2.fastq.gz
  genome_build: hg19
  variant_regions: /mnt/data/projects/miSeq/regions/miSeq.bed
fc_date: '130703'
fc_name: project1
```

I can supply other logs as needed. The GATK version used is 2.5-2-gf57256b. Java is 1.7 (same version on all nodes).
