### ISSUE TITLE
Smoove Lumpy error in structural variation pipeline (error related to samtools)

### ISSUE THREAD

**Issue by prasundutta87** [bcbio/bcbio-nextgen#3633]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): v1.2.9
- OS name and version (`lsb_release -ds`): Red Hat Enterprise Linux release 8.5 (Ootpa)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/NA12878-sv.yaml -n 16
```

Your yaml configuration file:
```
# Evaluate structural variant calling on NA12878 whole genome data,
# using validated deletions and insertions from the Genome in a Bottle svclassify project
# https://groups.google.com/d/msg/genome-in-a-bottle/v3EDUgZT0Xo/eGYsQlJk2JMJ
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
details:
- algorithm:
    aligner: bwa
    align_split_size: false
    exclude_regions: [lcr]
    recalibrate: false
    realign: false
    tools_off: [collectsequencingartifacts]
    variantcaller: false
    svcaller: [lumpy, manta, cnvkit, metasv, wham]
    svvalidate:
      DEL: ../input/giab-svclassify-deletions-2015-05-22.bed
      INS: ../input/giab-svclassify-insertions-2015-05-22.bed
  analysis: variant2
  description: NA12878
  files:
  - ../input/NA12878_1_1000000_reads.fastq
  - ../input/NA12878_2_1000000_reads.fastq
  genome_build: hg38
  metadata:
    batch: ceu
    sex: female
upload:
  dir: ../final

```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/8310984/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/8310985/bcbio-nextgen-debug.log)
