### ISSUE TITLE
bgzip error

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3639]
I am running mutation calling and HLA with optitype (separatily), and I'm encountering the same error involving bgzf

Error: unhandled exception: invalid bgzf file [ValueError]
[hla.config.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/8360792/hla.config.yaml.txt)

```yaml
# HLA genotyping
---
details:
- algorithm:
    platform: illumina
    quality_format: standard
    aligner: bwa
    save_diskspace: true
    hlacaller: optitype
  analysis: variant2
  resources:
    gatk:
      jvm_opts:
      - -Xms500m
      - -Xmx8g  
  description: TCGA-LN-A49U-H-N
  files: [/scratch/users/astar/gis/simngl/bcbioruns/TCGA-ESCA/bams/BATCH01/288a2fed-c644-49cb-a064-e4f4d14eb664/3d7ac912c7f1a18e7ca131bcc08fa3fc_gdc_realn.bam]
  genome_build: hg38
  metadata:
    batch: TCGA-LN-A49U-H
    phenotype: normal
- algorithm:
    platform: illumina
    quality_format: standard
    aligner: bwa
    save_diskspace: true
    hlacaller: optitype
  analysis: variant2
  description: TCGA-LN-A49U-H-T
  files: [/scratch/users/astar/gis/simngl/bcbioruns/TCGA-ESCA/bams/BATCH01/3b9319c1-307d-48d7-a49d-921c66e77bf4/c226f9156a8b9310d47d9b26d703c576_gdc_realn.bam]
  genome_build: hg38
  metadata:
    batch: TCGA-LN-A49U-H
    phenotype: tumor
fc_date: '2015-07-31'
fc_name: TCGA-LN-A49U-H
upload:
  dir: ../bcbio_final
```

Seek your assistance in resolving this issue; I am attaching my yaml files, as well as the last 200 lines of the log file.

Thank you.

[wxs.config.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/8360789/wxs.config.yaml.txt)
[wxs.error.txt](https://github.com/bcbio/bcbio-nextgen/files/8360790/wxs.error.txt)
[hla.error.txt](https://github.com/bcbio/bcbio-nextgen/files/8360791/hla.error.txt)
[hla.config.yaml.txt](https://github.com/bcbio/bcbio-nextgen/files/8360799/hla.config.yaml.txt)
