### ISSUE TITLE
Stripping underscores from otherwise numeric identifiers

### ISSUE THREAD

**Issue by ameynert** [bcbio/bcbio-nextgen#3656]
I've been trying to hunt down where this is happening in [the template](https://github.com/bcbio/bcbio-nextgen/blob/v1.2.8/bcbio/workflow/template.py) but not getting anywhere. Any suggestions? I'm happy to implement a fix if someone can point me to the bit of code that is causing this.

Essentially, some of the sample and family ids we work with are in the format [0-9]{5-6}_[0-9]{6}. The underscores are stripped out when the CSV file is combined with the template YAML to create the config YAML for bcbio.

**Version info**
- bcbio 1.2.8
- Red Hat Enterprise Linux release 8.5 (Ootpa)

**To Reproduce**
Exact bcbio command you have used:

```
bcbio_nextgen.py -w template ${bcbio_template} family.csv *.fastq.gz
```

CSV file
```
samplename,description,batch,sex,phenotype,paternal_id,maternal_id,variant_regions
134116_457300,134116_457300,19875_457300,1,1,0,0,/path/to/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
134113_457300,134113_457300,19875_457300,1,2,134116_457300,134114_457300,/path/to/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
134114_457300,134114_457300,19875_457300,2,1,0,0,/path/to/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
```

YAML output - note the batch, maternal id, and paternal id have had their underscores stripped.

```
details:
- algorithm:
    adapters:
    - nextera2
    - polyg
    align_split_size: false
    aligner: bwa
    effects: vep
    effects_transcripts: all
    indelcaller: false
    mark_duplicates: true
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: true
    remove_lcr: true
    tools_on:
    - vep_splicesite_annotations
    trim_reads: fastp
    variant_regions: /mnt/e1000/home/u035/u035/shared/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
    variantcaller: gatk-haplotype
  analysis: variant2
  description: '134113_457300'
  files:
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134113_457300_R1.fastq.gz
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134113_457300_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: 19875457300
    maternal_id: 134114457300
    paternal_id: 134116457300
    phenotype: 2
    sex: 1
- algorithm:
    adapters:
    - nextera2
    - polyg
    align_split_size: false
    aligner: bwa
    effects: vep
    effects_transcripts: all
    indelcaller: false
    mark_duplicates: true
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: true
    remove_lcr: true
    tools_on:
    - vep_splicesite_annotations
    trim_reads: fastp
    variant_regions: /mnt/e1000/home/u035/u035/shared/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
    variantcaller: gatk-haplotype
  analysis: variant2
  description: '134114_457300'
  files:
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134114_457300_R1.fastq.gz
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134114_457300_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: 19875457300
    maternal_id: 0
    paternal_id: 0
    phenotype: 1
    sex: 2
- algorithm:
    adapters:
    - nextera2
    - polyg
    align_split_size: false
    aligner: bwa
    effects: vep
    effects_transcripts: all
    indelcaller: false
    mark_duplicates: true
    platform: illumina
    quality_format: standard
    realign: false
    recalibrate: true
    remove_lcr: true
    tools_on:
    - vep_splicesite_annotations
    trim_reads: fastp
    variant_regions: /mnt/e1000/home/u035/u035/shared/resources/exome_targets/Twist_Exome_RefSeq_targets_hg38.plus15bp.bed
    variantcaller: gatk-haplotype
  analysis: variant2
  description: '134116_457300'
  files:
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134116_457300_R1.fastq.gz
  - /mnt/e1000/home/u035/u035/shared/scratch/alison-testing/work/47/6839aae069257be6671edeb69f9527/134116_457300_R2.fastq.gz
  genome_build: hg38
  metadata:
    batch: 19875457300
    maternal_id: 0
    paternal_id: 0
    phenotype: 1
    sex: 1
fc_name: '19875_457300'
upload:
  dir: ./results
```
