### ISSUE TITLE
setting -ploidy in yaml crashes gatk because existing default causes error:  "Argument 'ploidy/sample-ploidy' cannot be specified more than once."

### ISSUE THREAD

**Issue by mjsduncan** [bcbio/bcbio-nextgen#3668]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`):  Ubuntu 22.04 LTS

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/call1_samples.yaml -n 1
```

Your yaml configuration file:
```
---
upload:
  dir: ../final
fc_date: '220728'
fc_name: call1
details:
  - files: ../input/B1-ready.bam
    description: 'B1'
    genome_build: BDGP6
    metadata:
      batch: 3x5
      sex: female
    analysis: variant2
    algorithm:
      aligner: false
      recalibrate: false
      variant_regions: ../input/B1-callable.bed
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
    resources:
      gatk:
        jvm_opts: ["-Xms2g", "-Xmx8g"]
        options: ["--sample-ploidy 250", "--max-genotype-count 31626"]
      tmp:
        dir: /mnt/dm/tmp
  - files: ../input/B2-ready.bam
 ...
 [14 more samples]
```
shell output after individual samples get called with vcfs in *work/gatk-halplotype*:
```
***********************************************************************
A USER ERROR has occurred: Illegal argument value: Argument 'ploidy/sample-ploidy' cannot be specified more than once.
***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
Using GATK jar /home/mozi/biosrc/bcbio/anaconda/share/gatk4-4.2.6.1-1/gatk-package-4.2.6.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false  \
-Dsamjdk.compression_level=2 -Xms1g -Xmx7g -XX:+UseSerialGC  \
-Djava.io.tmpdir=/mnt/dm/tmp/tmp0b273n8o -jar /home/mozi/biosrc/bcbio/anaconda/share/gatk4-4.2.6.1-1/gatk-package-4.2.6.1-local.jar  \
 GenotypeGVCFs --variant gendb:///mnt/dm/flies/work/call1/work/joint/gatk-haplotype-joint/3x5/2L/3x5-2L_0_770517_genomicsdb  \
-R /home/mozi/biosrc/bcbio/genomes/Dmelanogaster/BDGP6/seq/BDGP6.fa --output /mnt/dm/tmp/tmpbdeqmdop/3x5-2L_0_770517.vcf.gz  \
-L 2L:1-770517 -ploidy 2 --sample-ploidy 250 --max-genotype-count 31626
' returned non-zero exit status 1.
```
above is tail of `bcbio-nextgen-commands.log`
