### ISSUE TITLE
Questions : use of joint calling with octopus and gnomad genome

### ISSUE THREAD

**Issue by Titos789** [bcbio/bcbio-nextgen#3683]
Hi,

Just used bcbio-nextgen for the first time. We would like to use octopus for 10 WGS variant calling and would like to have a multisample vcf. In the bcbio next-gen doc we saw that the jointcaller option supports with HaplotypeCaller and FreeBayes. Is there a possibility to jointly call the variants with octopus?

My second question concerns the use of gnomad genome. Unless I'm mistaken, by default bcbio next-gen uses gnomad exome. What command should I add in the config file to also have the frequencies of gomad genome. For annotation I use vep.

Thanks in advance,

```

details:
  - analysis: variant2
    genome_build: hg38
    description:
    metadata:
      batch:
      phenotype:
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: gatk
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [gemini,eog,dbscsnv,dbnsfp]
      tools_on:
        - vep_splicesite_annotations
    files: 
```
