### ISSUE TITLE
tabix error on effects-ploidyfix.vcf.gz

### ISSUE THREAD

**Issue by hongenxu** [bcbio/bcbio-nextgen#3706]
Dear authors,

when I tabix the effects-ploidyfix.vcf.gz, I got the errors as follows, 

_[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?
The offending line was: ""
[E::hts_idx_push] Unsorted positions on sequence #71: 521207 followed by 1
tbx_index_build failed: /public/home/zzumag02/Projects/1shenbing/bcbio/family-3312870/work/bcbiotx/tmpsd9_adut/3312870-effects-ploidyfix.vcf.gz
' returned non-zero exit status 1._

if I sort the effects-ploidyfix.vcf.gz by bcftools sort, it works. I cannot find where this file was created.

thanks,
hongen

**Version info**
- bcbio version (`bcbio_nextgen.py --version`):  1.2.9
- OS name and version (`lsb_release -ds`): CentOS Linux release 7.6.1810 (Core)

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py --separators R  -w template /public/home/zzumag02/Projects/bcbio_yaml/kidney_wes.yaml family-3312870.csv  /public/home/zzumag02/Projects/1shenbing/merged/3312870-2_R1.fastq.gz /public/home/zzumag02/Projects/1shenbing/merged/3312870-2_R2.fastq.gz
cd family-3312870/work
bcbio_nextgen.py ../config/family-3312870.yaml -n 32
```

Your yaml configuration file:
```
details:
- algorithm:
    aligner: bwa
    coverage: /public/home/zzumag02/Projects/bedfiles/Exome-T600V1G.bed
    mark_duplicates: true
    platform: Illumina
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_off:
    - upload_alignment
    tools_on:
    - qualimap_full
    variantcaller: gatk-haplotype
    vcfanno:
    - dbnsfp
  analysis: variant2
  description: 3312870-2
  files:
  - /public/home/zzumag02/Projects/1shenbing/merged/3312870-2_R1.fastq.gz
  - /public/home/zzumag02/Projects/1shenbing/merged/3312870-2_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: 3312870
    maternal_id: 0
    paternal_id: 0
    phenotype: 2
    sex: female
fc_name: family-3312870
upload:
  dir: ../final
```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.

[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/11171953/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/bcbio/bcbio-nextgen/files/11171955/bcbio-nextgen-debug.log)
