### ISSUE TITLE
KeyError: 'MB1' ' returned non-zero exit status 1. when running umis

### ISSUE THREAD

**Issue by juychen** [bcbio/bcbio-nextgen#3740]
**Version info**
- bcbio version (`bcbio_nextgen.py --version`): 1.2.9
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py /usersdata/junyichen/data/risi_0201/risi_0201/endo_rishi.yaml -n 20
```

Your yaml configuration file:
```
details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /usersdata/junyichen/data/risi_0201/risi_0201/barcodes_given.txt
    # transcriptome_fasta: /home/jholab/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.fa
    # transcriptome_gtf: /home/jholab/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: Endometrioma_rishi_0201
  files:
  - /usersdata/junyichen/data/risi_0201/risi_0201/SUB15154_R1.fastq.gz
  - /usersdata/junyichen/data/risi_0201/risi_0201/SUB15154_R2.fastq.gz
  - /usersdata/junyichen/data/risi_0201/risi_0201/SUB15154_R3.fastq.gz
  - /usersdata/junyichen/data/risi_0201/risi_0201/SUB15154_R4.fastq.gz
  genome_build: hg38
  metadata: {}
fc_name: endometrioma_rishi_0201
upload:
  dir: /usersdata/junyichen/output/risi_0201/final
```

**Log files (could be found in work/log)**
Please attach (10MB max):  `bcbio-nextgen-commands.log`, and `bcbio-nextgen-debug.log`.
[bcbio-nextgen-debug.log](https:/
[bcbio-nextgen-commands.log](https://github.com/bcbio/bcbio-nextgen/files/14177047/bcbio-nextgen-commands.log)
/github.com/bcbio/bcbio-nextgen/files/14177043/bcbio-nextgen-debug.log)
