### ISSUE TITLE
Memory setting for the GATK not honored

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#377]
This is with latest master.

``` yaml

  gatk:
    jvm_opts: ["-Xms750m", "-Xmx1800M"]
    dir: /mnt/data/programs/gatk/

```

However:

```
CalledProcessError: Command 'java -Xms375m -Xmx900M -Djava.io.tmpdir=/mnt/data/projects/normalpanels/work/tmp/tmpnlzcJD -jar /mnt/data/programs/gatk/GenomeAnalysisTK.jar
```

Notice the Xmx setting. This causes a failure because the GATK runs out of Java heap space.
