### ISSUE TITLE
_JAVA_OPTIONS can throw off version number detection of Java tools

### ISSUE THREAD

**Issue by mjafin** [bcbio/bcbio-nextgen#529]
Depending on how the version detection is done, funny things can happen. Instead of having this in `toolplus-packages.yaml`

```
gatk:
  name: gatk
  version: 2014.2-3.1.7-10-g867c2fb
mutect:
  name: mutect
  version: 1.1.6-appistry
```

we got this:

```
gatk:
  name: gatk
  version: 'Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=1

    2014.2-3.1.7-10-g867c2fb'
mutect:
  name: mutect
  version: 1.1.6-appistry
```
