### ISSUE TITLE
De-duplication with biobambam hangs

### ISSUE THREAD

**Issue by anastazie** [bcbio/bcbio-nextgen#560]
Dear Brad,
I am newbie in DNASeq NGS analysis. I am using bcbio-nextgen modified gatk template.
I started pipeline with 2 input .fastq.gz files for paired end Illumina reads for two samples. During analysis, error occured: 

`SAM/BAM file SAMFileReader{directory} is malformed: BAM file has a read with mismatching number of bases and base qualities. Offender: HWI-ST992:151:C3A49ACXX:4:2201:14969:67090 [39 bases] [0 quals]`

But sorted BAM files were already created. Because of that, I used these BAM files as an input with disabled aligner. When I start the script now, the following output is produced:

```
[2014-08-24 21:07] Using input YAML configuration: /home/pasha/bcbio-nextgen/bcbio-nextgen/scripts/ket_22.8.2014.yaml
[2014-08-24 21:07] Checking sample YAML configuration: /home/pasha/bcbio-nextgen/bcbio-nextgen/scripts/ket_22.8.2014.yaml
[2014-08-24 21:07] Testing minimum versions of installed programs
[2014-08-24 21:07] Resource requests: sambamba, samtools; memory: 2.0; cores: 1, 16
[2014-08-24 21:07] Configuring 2 jobs to run, using 16 cores each with 32.2g of memory reserved for each job
[2014-08-24 21:07] Timing: alignment preparation
[2014-08-24 21:07] multiprocessing: prep_align_inputs
[2014-08-24 21:07] Timing: alignment
[2014-08-24 21:07] multiprocessing: process_alignment
[2014-08-24 21:07] De-duplication with biobambam
[2014-08-24 21:07] De-duplication with biobambam
```

I am running the script on a server with 64 cores (passing the -n64 argument), but `top` shows that there is only single process running (bcbio_nextgen.py), consuming 100% CPU (i.e. one core). I would expect that biobambam process would start, but it's not the case. Even after few hours, `top` shows only the `bcbio_nextgen.py` process running on 100%. Do you have any ideas, what could be wrong?

`top` output:

```
top - 21:46:51 up 12 days, 10:18,  1 user,  load average: 1.00, 0.99, 0.95
Tasks: 414 total,   1 running, 413 sleeping,   0 stopped,   0 zombie
Cpu(s):  1.5%us,  0.1%sy,  0.0%ni, 98.4%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  528344612k total, 525508444k used,  2836168k free,   220948k buffers
Swap: 536809468k total,     5412k used, 536804056k free, 505427604k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                              
22144 pasha     20   0  872m  95m  15m S  100  0.0  26:19.01 bcbio_nextgen.p                                                                                                      
22499 pasha     20   0 17604 1588  976 R    1  0.0   0:01.08 top 
```

`ps -x` output:

```
  PID TTY      STAT   TIME COMMAND
20976 ?        S      0:00 sshd: pasha@pts/1   
20977 pts/1    Ss     0:01 -bash
22144 pts/1    Sl    26:59 /usr/local/share/bcbio-nextgen/anaconda/bin/python -E /usr/local/bin/bcbio_nextgen.py /home/pasha/bcbio-nextgen/bcbio-nextgen/scripts/ket_22.8.2014.yam
22259 pts/1    Sl     0:00 /usr/local/share/bcbio-nextgen/anaconda/bin/python -E /usr/local/bin/bcbio_nextgen.py /home/pasha/bcbio-nextgen/bcbio-nextgen/scripts/ket_22.8.2014.yam
22260 pts/1    Sl     0:00 /usr/local/share/bcbio-nextgen/anaconda/bin/python -E /usr/local/bin/bcbio_nextgen.py /home/pasha/bcbio-nextgen/bcbio-nextgen/scripts/ket_22.8.2014.yam
22270 pts/1    S      0:00 /bin/bash -c set -o pipefail; /usr/local/bin/bammarkduplicates tmpfile=/home/pasha/bcbio-nextgen/tmp/tmpORGlH2/Ket884-sort-reorder-fixrgs-gatkfilter-de
22271 pts/1    S      0:00 /bin/bash -c set -o pipefail; /usr/local/bin/bammarkduplicates tmpfile=/home/pasha/bcbio-nextgen/tmp/tmpDQU2Hg/Ket891-sort-reorder-fixrgs-gatkfilter-de
22272 pts/1    S      0:00 /usr/local/bin/bammarkduplicates tmpfile=/home/pasha/bcbio-nextgen/tmp/tmpORGlH2/Ket884-sort-reorder-fixrgs-gatkfilter-dedup-markdup markthreads=16 I=/
22273 pts/1    S      0:00 /usr/local/bin/bammarkduplicates tmpfile=/home/pasha/bcbio-nextgen/tmp/tmpDQU2Hg/Ket891-sort-reorder-fixrgs-gatkfilter-dedup-markdup markthreads=16 I=/
22501 pts/1    R+     0:00 ps x
```

My configuration file:

```
test_run: true
upload:
    dir: /home/pasha/nastya_ngs/ket_ngs
details:
    # to do multi-sample variant calling, assign samples the same metadata / batch
  - files: [file1-sort.bam]
    description: Ket884
    analysis: variant2
    genome_build: GRCh37
    metadata:
      batch: ket
      sex: male
    algorithm:
      aligner: false
      bam_clean: picard
      bam_sort: false
      quality_format: illumina
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      platform: illumina
      coverage_interval: genome
  - files: [file2-sort.bam]
    description: Ket891
    analysis: variant2
    genome_build: GRCh37
    metadata:
      batch: ket
      sex: female
    algorithm:
      aligner: false
      bam_clean: picard
      bam_sort: false
      quality_format: illumina
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      platform: illumina
      coverage_interval: genome
```

Thanks for any hints,

Nastya
