### ISSUE TITLE
pybedtools MalformedBedLineError

### ISSUE THREAD

**Issue by anastazie** [bcbio/bcbio-nextgen#593]
Hi, 
I am doing SNP calling on human DNASeq Illumina NGS data.
I performed analysis using bc-bio nextgen and it was successful.
Then I tried to perfom analysis with bcbio-nextgen using concatenated fastq files from two different runs (each sample had two runs: human DNA cleaned from bacteria and non-cleaned DNA) and now I have problems with running bcbio-nextgen.
Firstly I needed to increase number of open files.
I then started analysis again and got following error:

```
...........................................................................
/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pybedtools/cbedtools.so in pybedtools.cbedtools.IntervalFile.__next__ (pybedtools/cbedtools.cpp:8685)()
    675 
    676 
    677 
    678 
    679 
--> 680 
    681 
    682 
    683 
    684 

MalformedBedLineError: malformed line: ['10', '42354']
___________________________________________________________________________

```

Any idea how can I fix it?

Thanks,
Nastya

P.S.: Here is my YAML file

```
details:
    # to do multi-sample variant calling, assign samples the same metadata / batch
  - files: [/home/pasha/Ket_genomes/K884-all_NoIndex_R1.fastq.gz, /home/pasha/Ket_genomes/K884-all_NoIndex_R2.fastq.gz]
    description: Ket884_all
    analysis: variant2
    genome_build: GRCh37
    metadata:
      batch: ket
      sex: male
    algorithm:
      aligner: bwa
      mark_duplicates: picard
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      platform: illumina
      quality_format: Standard
      coverage_interval: genome
  - files: [/home/pasha/Ket_genomes/K891-all_NoIndex_R1.fastq.gz, /home/pasha/Ket_genomes/K891-all_NoIndex_R2.fastq.gz]
    description: Ket891_all
    analysis: variant2
    genome_build: GRCh37
    metadata:
      batch: ket
      sex: female
    algorithm:
      aligner: bwa
      mark_duplicates: picard
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      platform: illumina
      quality_format: Standard
      coverage_interval: genome
```
