### ISSUE TITLE
Using multi-batch "may" break paired tumor-normal analyis

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#702]
I have the same control for multiple analyses, and I noticed these errors:

``` python

ValueError: Found normal sample without tumor in batch ['20663-tumor1_vs_control', '20663-tumor2_vs_control', '20663-tumor3_vs_control']: ['20663-control']
```

But I have these in the configuration files (example for the first):

``` yaml

  metadata:
    batch: 20663-tumor1_vs_control
    phenotype: tumor
```

And the relevant control:

``` yaml

  metadata:
    batch: [20663-tumor1_vs_control, 20663-tumor2_vs_control, 20663-tumor3_vs_control]
    phenotype: normal
```

I also ensured I had the correct batches in the other 2 samples I didn't post here. I also wonder if this is also the cause for #701.
